### ISSUE TITLE
Upgrade to xunit 2 and xbehave 2

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#1001]
Because xunit 1 is just so 2013 :stuck_out_tongue_winking_eye: 

Benefits:
- xunit 2.0
  - This will _probably_ get rid the intermittent (9/10) build failures which we see in Travis CI, which I believe is a problem which only manifests in xunit 1.x, on low spec VMs (some kind race condition)
  - parallel test exec
  - self contained VS runner support
  - test collections
  - nicer console output
  - other new xunit 2.0 features - http://xunit.github.io/release-notes/2015-03-16.html
- xbehave 2.0
  - support for all new xunit 2.0 features
  - all steps following a failed step in a scenario are reported as skipped instead of failed, drastically reducing noise in test output
  - other minor changes - https://github.com/xbehave/xbehave.net/wiki/Changes-in-version-2.0
- moving off obsolete platforms which are purely in maintenance mode

Blockers:
- xunit 2.0 currently does not work in Mono, due to a bug in Mono, but this has been fixed and is awaiting release. See https://github.com/xunit/xunit/issues/158
- AutoFixture.Xunit is still tied to xunit 1.x - see https://github.com/AutoFixture/AutoFixture/pull/294
- xbehave 2.0 is still in RC, but RTM should be in the next week or two - see https://github.com/xbehave/xbehave.net/issues/144

**Comment by adamralph** [comment]
Note that we can probably spin off an issue to upgrade the acceptance tests first, since they are not blocked by AutoFixture,Xunit, and that in itself should fix Travis since, at the moment, only the acceptance tests are run there.

**Comment by adamralph** [comment]
But of course, an update to the acceptance tests is still dependent on the Mono fix.

**Comment by filipw** [comment]
Fixed by #1194
