### ISSUE TITLE
Cannot compile custom AutofacNancyBootstrapper with ScriptCs on Mac

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#1004]
From http://stackoverflow.com/questions/29276493/cannot-compile-custom-autofacnancybootstrapper-with-scriptcs-on-mac

**Comment by c0ntinuum** [comment]
Thanks Adam ;) I'm glad that it wasn't my code that was the problem. I'll continue hacking on my app on scriptcs under Windows until we can find out what the issue is.

**Comment by filipw** [comment]
that's a mono bug

**Comment by adamralph** [comment]
has it been raised with them?

**Comment by filipw** [comment]
no because i don't know what really the bug is here yet 
works on mono on windows though so it's definitely a mono quirk
