### ISSUE TITLE
Use packageSourceCredentials when interacting with feeds

### ISSUE THREAD

**Issue by aarondandy** [scriptcs/scriptcs#1018]
While `scriptcs -I` does check other feeds for packages that are listed in my NuGet.Config it does not send any credentials in the requests that are found in the `packageSourceCredentials` element.

**Comment by glennblock** [comment]
Good catch. With nuget supporting secure repos we should. Wanna take this?

**Comment by aarondandy** [comment]
It looks like Chocolatey is "Doing It Right" so I may investigate how they do it first. I'll look into it a bit more before I commit to doing it as I really don't know enough about NuGet yet. This is important enough for me that I will probably end up learning more about NuGet though and obviously I have some feeds that require authentication that I can work with.

**Comment by glennblock** [comment]
Fabulous! :-)

**Comment by aarondandy** [comment]
I have a fork and am looking into this.

I was wrong about Chocolatey doing it right, those calls I was watching in Fiddler were directly from nuget.exe .

**Comment by filipw** [comment]
This was fixed in 0.17.0
