### ISSUE TITLE
Namespaces are not be properly imported for usings within Script Libraries when in the REPL

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#1025]
Based on my testing of the new scriptcs-couchbase script pack, I noticed that using statements within the Script Library do not appear to actually get properly picked up when in the REPL.

Outside the REPL they work fine.

**Comment by glennblock** [comment]
Found the issue, one line fix coming.

**Comment by glennblock** [comment]
It turns out there was an issue for Namespaces and References, and not just for the REPL.

**Comment by khellang** [comment]
Closed with #1027
