### ISSUE TITLE
ERROR: Script compilation failed: error CS0246:

### ISSUE THREAD

**Issue by moiseyo** [scriptcs/scriptcs#1030]
I'm trying to write script  using external libraries ( Oracle) 

My code:
using Oracle.ManagedDataAccess.Client;
using Oracle.ManagedDataAccess.Types; 
using  System.IO;
.....

Thank you   look  setting bellow 

What did I miss?

I'm getting error 
.................
ERROR: Script compilation failed: error CS0246: The type or namespace name 'Oracle' could not be found (are you missing a using directive or an assembly reference?).

I put Oracle dlls in the same direcory

  15,117 000.01-TWO2015WEB_BASELINE.csx
   5,052 000.02 - CREATE ROLE VIEW_TWO2015.csx
   6,541 000.03 - LOOKUP_DATA.csx
   1,706 000.05 - Create_mv_efc15_min_ver.csx
   3,416 000.09 - redeploy_reports.csx
  13,312 CSharp.Coderbits.dll
 374,784 Newtonsoft.Json.dll
,934,720 Oracle.ManagedDataAccess.dll
   4,098 oraclehelpers.csx
     732 packages.config
   5,120 ScriptCs.Coderbits.dll
   5,120 ScriptCs.Contracts.dll
 168,520 System.Net.Http.Formatting.dll
      88 test.csx
 358,184 TWO.2015baselinescript.csx
   4,734 two.dbupdate.csx

And package file 

?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="CSharp.Coderbits" version="1.0.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebApi.Client" version="4.0.30506.0" targetFramework="net451" />
  <package id="Microsoft.Net.Http" version="2.0.20710.0" targetFramework="net451" />
  <package id="Newtonsoft.Json" version="4.5.6" targetFramework="net451" />
  <package id="odp.net.managed" version="121.1.2" targetFramework="net40" />
  <package id="Oracle.ManagedDataAccess" version="12.1.021" targetFramework="net451" />
  <package id="ScriptCs.Coderbits" version="1.0.3" targetFramework="net451" />
  <package id="ScriptCs.Contracts" version="0.4.0" targetFramework="net451" />
</packages>

**Comment by adamralph** [comment]
Hi @moiseyo, please see https://github.com/scriptcs/scriptcs/wiki/Writing-a-script#referencing-assemblies

**Comment by filipw** [comment]
The DLLs should be placed in the `bin` folder
