### ISSUE TITLE
Oracle Problem command.Parameters.Add( "report_sql", OracleDbType.Clob );

### ISSUE THREAD

**Issue by moiseyo** [scriptcs/scriptcs#1033]
I have an application   create an Oracle database  11 or 12 
this Application has  2 problems I do not have  explanation :+1: 
1) I have scripts in @" ..." format  and if script less 1000 bytes It runs fine(  i checked via  debug  that  scripts or OK and can be executed via SQLPLUS with the same  credentials it produces the error  ORA-00911: invalid character )  the came  code  VS 2013    runs Ok 

2)    the function suppose  to put CLOB in record does not  produce  any results and no errors or warnings 

  
public static void ApplyFile(string file_name, int id)
    {
        try
        {
            
            char [] value;
            value = System.Text.Encoding.ASCII.GetString( File.ReadAllBytes(file_name)).ToCharArray();
            if (debug)
            {
                // foreach ( char c in value)
                    // Console.Write(c);
            }
            OracleCommand command= new OracleCommand();
            var connString = string.Format("User Id={0}; password={1};Data Source={2}; Pooling=false;", Username, Password, Database);
            using (OracleConnection connection = new OracleConnection(connString))
            {	
                string script=" update  report_type  set REPORT_SQL=:report_sql where REPORT_TYPE_ID=:report_type_id ";    
                connection.Open();
                command.Connection=connection;
                command.CommandText=script;
                using (OracleTransaction transaction = connection.BeginTransaction())
                {
                    try
                    {
                        
                        if (debug)
                        {
                            Console.WriteLine("script:'{0}'", script);
                            Console.WriteLine("file_name:'{0}',Id:{1}",file_name,id);
                        }
                                    var clob = new OracleClob( connection );
                        clob.Write( value, 0, value.Length );
                        
                        OracleParameter parameter = command.Parameters.Add( "report_sql", OracleDbType.Clob );
                        parameter.Value = clob;
                        OracleParameter parameter_id = command.Parameters.Add( "report_type_id", OracleDbType.Int32 );
                        
                        parameter_id.Value = id;
                         if (debug)
                            {
                            Console.WriteLine("values {0}-<{1}", parameter_id.Value, parameter.Value);
                            }
                      
                      
                       int retCode= command.ExecuteNonQuery();
                        if (debug)
                            {
                            Console.WriteLine("RetCode:{0}",retCode);
                            Console.WriteLine("");
                            }
                      
                        transaction.Commit();
                    }
                    catch
                    {
                        transaction.Rollback();
                        throw;
                    }
                }
            }

        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            Console.WriteLine(ex.StackTrace);
            Environment.Exit(2);
        }
    }

**Comment by moiseyo** [comment]
I have found the problems
1)  In multiline script it need to be in BEGIN ... END; braces
2) use  transaction commit.

**Comment by adamralph** [comment]
@moiseyo thanks for following up. So the issue wasn't related to scriptcs then.
