### ISSUE TITLE
Make ScriptExecutor references methods virtual

### ISSUE THREAD

**Issue by lukebuehler** [scriptcs/scriptcs#1036]
When hosting scriptcs and using the ScriptExecutor it'd be nice to have a way to be notified if any assemblies or namespaces change.

I see two ways of doing this.  
1) Extending the IScriptExecutor interface to have an event or action that is called.
2) Making all the ```AddReferences```, ```RemoveReferences```, etc methods virtual, so they can be overwritten with functionality that notifies.

**Comment by adamralph** [comment]
I see no issue with making those methods virtual.

**Comment by glennblock** [comment]
@lukebuehler can you give a bit more context on why you need this?

**Comment by lukebuehler** [comment]
@glennblock, as I'm hosting scriptcs in CShell I'd like to update the UI whenever a new reference is added.

So when I type in the REPL:

     #r "System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

I'd like the ```System.Configuration``` assembly to show up in my UI...

For what I'm doing now:   
https://github.com/lukebuehler/CShell/blob/dev/Src/CShell.Core/IReplScriptExecutorFactory.cs 
https://github.com/lukebuehler/CShell/blob/dev/Src/CShell.Hosting/ReplScriptExecutor.cs#L206

**Comment by filipw** [comment]
great we need it for omnisharp too

**Comment by khellang** [comment]
Just throwing it out there; observable collections? Not sure what to do with the assembly reference dictionaries, though. Something like an ObservableDictionary?

**Comment by glennblock** [comment]
ObservableCollection<T> or using something like IObservable<T>

**Comment by glennblock** [comment]
@lukebuehler makes sense, thanks.

**Comment by lukebuehler** [comment]
@filipw, yep, I wanted to mention code completion too! I need it for that as well.

**Comment by lukebuehler** [comment]
@glennblock , @khellang , right now the ```AssemblyReferences``` are immutable. I do like this. So I think any event that changes the refs should originate from ```ScriptExecutor```, and not the collections themselves.

If we do wanna make those notifications part of scriptcs then we should either add  
1) specific events like ```event EventHandler<EventArgs> AssemblyReferencesChanged;``` and ```event EventHandler<EventArgs> NamespacesChanged;```
2) or implement ```INotifyPropertyChanged``` for a more generic solution.

**Comment by adamralph** [comment]
Would it be enough to just make the `AddXXX` methods virtual?

**Comment by glennblock** [comment]
Adding the events doesn't hurt as long as they are no-op if there are no
subscribers. The problem is it is a breaking change if we add it to the
interface. Making the members virtual seems safest and then hosters can
plug in a derived version that adds notification.

**Comment by lukebuehler** [comment]
Yeah, I think virtual it would be the least invasive. So unless this is a feature you'd be interested to add, let's just take this path. I'll create a PR

**Comment by adamralph** [comment]
@lukebuehler thanks!

**Comment by lukebuehler** [comment]
On a side note, while we are at: The assembly refs are immutable but the namespaces are not.
I could do this: ```scriptExecutor.Namespaces.Add("hhaha i avoided the add methods");```
Should this not be immutable?

**Comment by glennblock** [comment]
+1
