### ISSUE TITLE
Make ScriptExecutor namespaces immutable and make import/remove methods virtual

### ISSUE THREAD

**Issue by lukebuehler** [scriptcs/scriptcs#1040]
See discussions here: #1036

1) Replace ```IScriptExecutor.Namespaces``` with ```IReadOnlyCollection<string> Namespaces { get; }``` (Possibly a breaking change if people add namespaces directly to this collection, but they shouldn't be anyhow)

2) make Import / Remove Namespaces methods virtual

Any input? Will prep PR

**Comment by adamralph** [comment]
I've already change #1036  to be the 'make methods virtual' issue. This issue can be for immutable namespaces. It is a separate thing, and breaking.

**Comment by adamralph** [comment]
Oh sorry, I see what you mean now, this was just for namespace methods to be virtual. I've reverted the title.

**Comment by adamralph** [comment]
Whilst we're here, shall we change `ImportNamespaces` to `AddNamespaces`?

'import' seems at odds with 'remove' and also diverges from the 'add' used for the references overloads.

**Comment by lukebuehler** [comment]
@adamralph, np. It would make it more inline with the references method, but it would make it more of a breaking change... right now, I doubt anybody is changing the namespace collection in their code, but they are using ```ImportNamespaces()```. It's up to you guys.

**Comment by adamralph** [comment]
Also, if we are aligning the behaviour of the namespace methods with the references methods then we should suppress duplicates and not throw exceptions for calls which remove non-existent namespaces.

**Comment by lukebuehler** [comment]
What about this?
https://github.com/lukebuehler/scriptcs/commit/10f5730087e1a2d602ed90b19ec3cd8c7ad57425

**Comment by adamralph** [comment]
:+1: LGTM!

OK, let's leave the `ImportNamespaces()` for now then. You're right, that will probably break people, but the other changes probably won't.

**Comment by glennblock** [comment]
Let's not break people, people ;-)
