### ISSUE TITLE
Problems with XML Serialization

### ISSUE THREAD

**Issue by grbd** [scriptcs/scriptcs#1048]
Hi,
I've been having problems with xml serialization of custom class's with the error

    ERROR: Script execution failed: Identifier 'Submission#0' is not CLS-compliant.
    Parameter name: ident.

It seems to be when I call XmlSerializer with a custom class
This doesn't work

        Type t1 = typeof (List<SourcePackage>);
        var oXs = new XmlSerializer(t1);

This does work

        Type t1 = typeof (List<string>);
        var oXs = new XmlSerializer(t1);

I tried scattering [CLSCompliant(false)] above all my class's without much luck
I then tried [assembly: CLSCompliantAttribute(true)], but this just results in a different error regardless of where I put the statement

    error CS1730: Assembly and module attributes must precede all other elements defined in a file except using clauses and extern alias declarations.

**Comment by adamralph** [comment]
@grbd unfortunately `Submission#0` is a type name prefix assigned by Roslyn which we can't control. If you declare a class in your script, this ends up as a nested class with it's parent being the class which Roslyn creates to contain the script.

Perhaps you could try using a different XML serializer?

**Comment by grbd** [comment]
It's the default xml serializer included within the .Net framework
I was hoping there might be a way to turn off cls on the assembly level as a quick fix
but it sounds like this might be a Roslyn related issue

**Comment by filipw** [comment]
yeah all classes declared in script are de facto nested classes. They can be visible (public) but from serializer's standpoint, it will want to serializer the outer class too

**Comment by adamralph** [comment]
@grbd 

> It's the default xml serializer included within the .Net framework

In my experience, this serializer has many shortcomings.

A few ideas for how to proceed:

1. Serialize into JSON instead. This will remove the need to serialize the type name.
1. Find a better XML serializer, e.g. https://www.nuget.org/packages?q=xml+serializer
1. Investigate why the type generated by Roslyn is marked CLS compliant when it isn't.
  1. This could be a Roslyn bug. We are still using the old Roslyn CTP and nothing will get fixed there, but perhaps the newer Roslyn scripting bits don't suffer from this problem. Work is ongoing to move scriptcs to the new Roslyn packages but it is still in early stages (https://github.com/scriptcs/scriptcs-engines)
  1. This could be something we can control via the Roslyn API, in which case a scriptcs change could fix this issue.

**Comment by grbd** [comment]
I've switched to using Linq which seems to work fine

    /// <summary> Deserialize XML File into List of class's. </summary>
    public static List<SourcePackage> Deserialize_List(XElement xelement)
    {
        List<SourcePackage> ret = new List<SourcePackage>();
        foreach (XElement item in xelement.Elements("SourcePackage")) {
            SourcePackage newitem = new SourcePackage();
            var xName = item.Element("Name");
            var xVersion = item.Element("Version");
            var xFileName = item.Element("FileName");
            var xExtractSubDir = item.Element("ExtractSubDir");
            var xDownloadUrl = item.Element("DownloadUrl");
            if (xName != null) newitem.Name = xName.Value;
            if (xVersion != null) newitem.Version = xVersion.Value;
            if (xFileName != null) newitem.FileName = xFileName.Value;
            if (xExtractSubDir != null) newitem.ExtractSubDir = xExtractSubDir.Value;
            if (xDownloadUrl != null) newitem.DownloadUrl = xDownloadUrl.Value;
            ret.Add(newitem);
        }
        return ret;
    }
