### ISSUE TITLE
ScriptPackSession.References assumes namespaces are assemblies in RoslynScriptEngine.Execute

### ISSUE THREAD

**Issue by fir3pho3nixx** [scriptcs/scriptcs#1049]
Hi

I can see the ScriptPackSession is assuming namespaces are assemblies when I put a break point on RoslynScriptEngine.Execute line 77. 

Can you give me a bump in the right direction? 

Thanks

Gav

**Comment by filipw** [comment]
what do you mean "is assuming namespaces are assemblies" ?

**Comment by fir3pho3nixx** [comment]
In the Execute method of the RoslynScriptEngine the variable "executionReferences.Paths" assumes namespaces to be assemblies at the following code fragment:

        public ScriptResult Execute(
            string code,
            string[] scriptArgs,
            AssemblyReferences references,
            IEnumerable<string> namespaces,
            ScriptPackSession scriptPackSession)
        {
            Guard.AgainstNullArgument("scriptPackSession", scriptPackSession);
            Guard.AgainstNullArgument("references", references);

            Logger.Debug("Starting to create execution components");
            Logger.Debug("Creating script host");

            var executionReferences = references.Union(scriptPackSession.References);

            SessionState<Session> sessionState;

            var isFirstExecution = !scriptPackSession.State.ContainsKey(SessionKey);

            if (isFirstExecution)
            {
                code = code.DefineTrace();
                var host = _scriptHostFactory.CreateScriptHost(
                    new ScriptPackManager(scriptPackSession.Contexts), scriptArgs);

                ScriptLibraryWrapper.SetHost(host);
                Logger.Debug("Creating session");

                var hostType = host.GetType();
                ScriptEngine.AddReference(hostType.Assembly);
                var session = ScriptEngine.CreateSession(host, hostType);
                var allNamespaces = namespaces.Union(scriptPackSession.Namespaces).Distinct();

                foreach (var reference in executionReferences.Paths)
                {
                    Logger.DebugFormat("Adding reference to {0}", reference);
    //-- HERE >>
					session.AddReference(reference);
                }

**Comment by filipw** [comment]
i am sorry but i still don't understand.
it doesn't assume namespaces to be references, it assumes references to be references

**Comment by fir3pho3nixx** [comment]
![image](https://cloud.githubusercontent.com/assets/607402/7759185/2c0511ac-0007-11e5-865e-1101271ab700.png)

**Comment by fir3pho3nixx** [comment]
![image](https://cloud.githubusercontent.com/assets/607402/7759206/5d5b7e08-0007-11e5-9235-387dcfaf051f.png)

**Comment by filipw** [comment]
well you must have something in your code that added "FluentlyWindsor" to references (i.e. `#r FluentlyWindsor` directive)

scriptcs would never just take your namespace and treat as assembly :smile:

**Comment by fir3pho3nixx** [comment]
Indeed, I did inject this dependency here. I am trying to work out where the problem is though. Do you think you could do a test by referencing a compiled assembly from ./scriptcs_bin and execute a class method but give it funky namespace?

**Comment by fir3pho3nixx** [comment]
My use case uses ScriptPacks

**Comment by filipw** [comment]
maybe your script imports a reference to "FluentlyWindsor" rather than importing a namespace "FluentlyWindsor", it sure looks like that

**Comment by fir3pho3nixx** [comment]
Ok, 

So my script is: 

    using deploycs.scripts;
    var deploycs = Require<DeployCs>();

The pre compiled code living in ./scriptcs_bin for DeployCs right now is:

		using System;
		using System.Reflection;
		using Castle.Windsor;
		using FluentlyWindsor;
		using ScriptCs.Contracts;

		namespace deploycs.scripts
		{
			public class DeployCs : IScriptPackContext
			{
				private readonly IWindsorContainer container;

				public DeployCs()
				{
					//container = FluentWindsor.NewContainer(Assembly.GetExecutingAssembly()).WithArrayResolver().WithInstallers().Create();
				}

				public void Get(Action<IWindsorContainer> @get)
				{
					@get(container);
				}

				public void Terminate()
				{
					//container.Dispose();
				}
			}
		}

**Comment by fir3pho3nixx** [comment]
The superfluous "using FluentlyWindsor" here (which is compiled code btw) is causing your execute to fail.

**Comment by fir3pho3nixx** [comment]
I am just not sure how it all hangs together.

**Comment by filipw** [comment]
you have another class in that dll, implementing `IScriptPack` or extending `ScriptPack` base class

in there, in the initialize method, I am sure you are calling `session.AddReference("FluentlyWindsor");` which is incorrect since such assembly does not exist

**Comment by filipw** [comment]
in fact I just decompiled your dll and that's exactly what is happening

![screenshot 2015-05-21 23 37 57](https://cloud.githubusercontent.com/assets/1710369/7759528/715877fc-0012-11e5-9a4c-03b1993ae7d5.png)

**Comment by fir3pho3nixx** [comment]
That help me along, thank you

**Comment by fir3pho3nixx** [comment]
Perhaps we need a better error message here? What do you think?

**Comment by filipw** [comment]
well but what error message though? your script pack told it to import an assembly that doesn't exist, so the error was "assembly does not exist" :smile:

**Comment by fir3pho3nixx** [comment]
So the error tells first time ScriptPacker's this is the case?

**Comment by fir3pho3nixx** [comment]
You win

**Comment by fir3pho3nixx** [comment]
Still getting #786. Thanks for all your help :)
