### ISSUE TITLE
Current Script Directory

### ISSUE THREAD

**Issue by grbd** [scriptcs/scriptcs#1050]
Hi,
I'm looking for a way to determine the current directory of a running script at run time
so far I've tried the following

Environment.CurrentDirectory = Working Directory (not the same as the directory the script is located in)
Assembly.GetExecutingAssembly().Location = Blank
AppDomain.CurrentDomain.BaseDirectory = Path to the scriptcs.exe

The Env.ScriptArgs is just the list of arguments passed to the app
this also doesn't contain the script directory

any ideas?

**Comment by khellang** [comment]
This sounds like a dupe of #225

**Comment by grbd** [comment]
Yep its the same thing, I did search for anything similar but didn't find anything off hand
