### ISSUE TITLE
Returning output from ScriptCs

### ISSUE THREAD

**Issue by goldytech** [scriptcs/scriptcs#1051]
Hi,

Is it possible to return a object / value from scriptcs .csx file ?

Problem statement

I have one .csx file , which read a csv file and store its data in a list object
Now i want to use this output of first .csx file as a input for another .csx file which will process this object.

Kindly help

**Comment by khellang** [comment]
You can return a value from a script, but it would only result in scriptcs outputting a (JSON) serialized representation of the result to the console when the script is finished running, like this:

![image](https://cloud.githubusercontent.com/assets/582487/7810655/49b7960c-03a4-11e5-8655-f8a2c89c7ae8.png)

This doesn't allow you to "pick up" the result of another script. What you could do is assign the "return value" to a variable in the script, then once you've `#load`'ed it, you can use the same variable in the next script, like this:

![image](https://cloud.githubusercontent.com/assets/582487/7810743/08238dc6-03a5-11e5-960b-ab2deace9650.png)

**Comment by goldytech** [comment]
Thanks for the help.
