### ISSUE TITLE
ScriptCs is a load of codswollop ... 

### ISSUE THREAD

**Issue by fir3pho3nixx** [scriptcs/scriptcs#1052]
Now that I have your attention, seriously guys keep at it. This stuff is amazing. In the few hours I have spent on it I have managed to create a scripting DSL using ScriptPack's which I must say has re-invigorated my zeal for .NET again(required some debugging but I got there in the end). The fact that it is portable to alternative OS's is also a massive win. Good Job! This is probably the project that stopped me from crossing over to NodeJs entirely. Thank you. 

:)

**Comment by adamralph** [comment]
LOL... thanks for the kind words!

https://twitter.com/adamralph/status/605825666240552961

**Comment by fir3pho3nixx** [comment]
Jesus, clearly I am a "late adopter". Will checkout bau and stop this deploycs nonsense. Interestingly though, I haphazardly fell on a similar fluent interface for doing command automation with a functional spin. Not too dissimilar from bau. I needed an answer that was NOT powershell or msbuild.  

	using deploycs.scripts;

	var deploycs = Require<DeployCs>();

	var applicationPoolName = "My Test App Pool";

	deploycs
		.@if(x => x.@check<AppPoolExists>(applicationPoolName))
		.@then(x => x.@do<AppPoolDelete>(applicationPoolName));

	deploycs
		.@do(x => x.@using<AppPoolCreate>(new {
			applicationPoolName = applicationPoolName,
			identityType = ProcessModelIdentityType.NetworkService,
			applicationPoolIdentity = string.Empty,
			password = string.Empty,
			managedRuntimeVersion = "v4.5",
			autoStart = true,
			enable32BitAppOnWin64 = false,
			managedPipelineMode = ManagedPipelineMode.Integrated, 
			queueLength = 1000,
			idleTimeout = TimeSpan.FromMinutes(5), 
			periodicRestartPrivateMemory = 1000,
			periodicRestartTime = TimeSpan.FromMinutes(5)
		}));

**Comment by fir3pho3nixx** [comment]
The learning continues ... :)

**Comment by adamralph** [comment]
Interesting! Generally, the value of Bau lies in task dependency specification and selective invocation, but if the command invocation aspect does, in isolation, provide value to you then great! Bau doesn't *really* have an equivalent of your `@if()` method but ultimately you can write any delegate you like in a task body so you can achieve the same effect. At some point conditional task execution could indeed be lifted up to being a first class member of the DSL.

**Comment by glennblock** [comment]
Great to hear Gav!

**Comment by fir3pho3nixx** [comment]
@adamralph - Think you have a good point here. The @if was a c# brain fart based on predicates and actions(no tests, still exploring, just love lamda's). Branching as a first class concept perhaps adds too much complexity and encapsulating this inside a task minimises the nastiness you will find out there in the wild because it is indeed isolated(no side effects) and it remains really simple. This resonates well with NodeJs projects and it just works. Furthermore if you consider MSBuild and Powershell these are first class concepts but the cost is learning a naf syntax followed by some horrific build scripts in the wild that scare the bejesus out of even the most seasoned developers because of branch based logic based on epic configuration stimuli. 

Surprised you did not give me beans for using Castle Windsor as my choice for composition. I did that just because I could. MEF is great and people reading this should know this is a first class citizen with scriptcs, sometimes we follow the hard path purely because it is fun :)

Watch this space for contributions!
