### ISSUE TITLE
Housekeeping of file system artifacts created by NuGet.Core

### ISSUE THREAD

**Issue by RossHammer** [scriptcs/scriptcs#1053]
When you have a scriptcs_packages.config every time a script is run in that directory a copy of the nuget package shows up in %TEMP%/nuget and doesn't get cleaned up. We are using scriptcs to automate some server actions an found this directory was using 10GB of disk space after a couple days of running. 

Here is an example:

scriptcs_packages.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net45" />
</packages>
```

json.csx
```c#
using Newtonsoft.Json;

class Test {
    public int Val = 4;
}

Console.WriteLine(JsonConvert.SerializeObject(new Test()));
```

Everytime scriptcs json.csx is run a new directory shows up in %TEMP%/nuget

**Comment by adamralph** [comment]
I've observed this too.

It's a 'feature' of the NuGet.Core API. AFAIK Visual Studio cleans these files periodically but any other apps using the NuGet.Core package, e.g. scriptcs, have to find out for themselves that this magic housekeeping is required.

Anyway, it's a genuine issue which we'll have to cater for, even though it should not be our responsibility as mere consumers of the API.

**Comment by adamralph** [comment]
Taken by @ChrSteinert
