### ISSUE TITLE
Mono: Compilation failure should result in non-zero exit code

### ISSUE THREAD

**Issue by eatdrinksleepcode** [scriptcs/scriptcs#1054]
Environment:
OS X 10.10.2
Mono 4.0.1
ScriptCS 0.14.1

Reproduction steps - :
1. Add the letter "x" to "bug.csx"
2. Run "scriptcs bug.csx"

Expected outcome:
1. A compilation error is reported
2. The process exit code is non-zero

Actual outcome:
1. A compilation error is reported
2. The process exit code is zero

The behavior is correct on Windows 7 on the .NET Framework, where the same steps result in an exit code of 1.

**Comment by khellang** [comment]
Do you have any actual output? It's easier to see which route was taken through the error handling. Something tells me this is a mono bug, since it works correctly on the .NET framework.

**Comment by khellang** [comment]
It might be some Mono exit code FUBAR. Maybe we could try checking if an alternative to returning an `int` from `Main` would work? http://www.mono-project.com/docs/tools+libraries/tools/gendarme/rules/portability/#exitcodeislimitedonunixrule

**Comment by eatdrinksleepcode** [comment]
Windows/.NET (cmd):
```
Z:\bau>echo x > bug.csx
Z:\bau>type bug.csx
x
Z:\bau>scriptcs bug.csx
ERROR: Script compilation failed: Z:\bau\bug.csx(1,1): error CS0103: The name 'x' does not exist in the current context.
Z:\bau>echo %errorlevel%
1
```
Windows/.NET (git shell):
```
$ echo x > bug.csx
$ cat bug.csx
x
$ scriptcs bug.csx
ERROR: Script compilation failed: z:\bau\bug.csx(1,1): error CS0103: The name 'x' does not exist in the current context.
$ echo $?
1
```
Mac/Mono:
```
:echo x > bug.csx
:cat bug.csx
x
:scriptcs bug.csx
(3,1): error CS0103: The name `x' does not exist in the current context
:echo $?
0
```

**Comment by adamralph** [comment]
I remember trying to solve this before and I hit a wall, but perhaps @khellang's link is the key.

Perhaps we should add an `AppDomain.UnhandledException` handler which dumps the exception message and stack trace and then does `Environment.Exit(1)`.

**Comment by adamralph** [comment]
This isn't a Mono bug. It's a bug in our Mono engine. If you run in Windows specifying `-M mono` the same problem occurs.

**Comment by filipw** [comment]
fixed by https://github.com/scriptcs/scriptcs/pull/1216
