### ISSUE TITLE
Upgrade to Roslyn packages 1.0.0 rc2

### ISSUE THREAD

**Issue by filipw** [scriptcs/scriptcs#1059]
The engines developed under https://github.com/scriptcs/scriptcs-engines should be merged in here, into the `dev` branch.

This should be done after https://github.com/scriptcs/scriptcs-engines/issues/10

**Comment by filipw** [comment]
Actually, now that I think of it, probably the reverse is true. It would be better to first merge in here as RC2 version and then upgrade in place later.

**Comment by adamralph** [comment]
If RC2 is on NuGet (even unlisted) then I agree, may as well get it in here ASAP.

**Comment by filipw** [comment]
It's a `pre` so it needs bundling regardless

**Comment by adamralph** [comment]
Ah, forgot about the `pre`. Did we decide on a solution for that yet?

**Comment by filipw** [comment]
Ultimately we need to use packages from here https://www.myget.org/gallery/roslyn-nightly.
Let's just dump them into a `lib` folder for now?

**Comment by adamralph** [comment]
Yeah, that's fine.

**Comment by filipw** [comment]
the work is underway here.. https://github.com/filipw/scriptcs/tree/feature/roslyn-engines-rc2

only 8 failing tests :smile:
