### ISSUE TITLE
else keyword not correctly parsed

### ISSUE THREAD

**Issue by gsscoder** [scriptcs/scriptcs#1060]
I was writing a script getting the following error:
```bash
(1,1): error CS1525: Unexpected symbol `else' 
```

To verify that the problem is really about the `else` keyword I've reduced it to the following snippet:
```csharp
using System;

var x = true;
if (x) {
	Console.WriteLine("IF {0}", x);
} else {
	Console.WriteLine("ELSE {0}", x);
}
```

I've installed **scriptcs** via `brew` on OS X Yosemite. I can't tell you the version using `sciptcs -Version`, since it fails printing the version.

```bash
➜  temp  brew info scriptcs
scriptcs: stable 0.14.1 (bottled)
Tools to write and execute C#
https://github.com/scriptcs/scriptcs
/usr/local/Cellar/scriptcs/0.14.1 (31 files, 9,9M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/scriptcs.rb
==> Dependencies
Recommended: mono ✔
==> Options
--without-mono
	Build without mono support
```

If you need any other info to solve the issue, please tell me.

**Comment by glennblock** [comment]
Is this in the REPL or within a script?

**Comment by glennblock** [comment]
I just repro'd this. Looks like it is indeed a bug.

**Comment by glennblock** [comment]
@gsscoder what error do you get when you do "scriptcs -Version"?

**Comment by adamralph** [comment]
Does it work if the script looks like this?

```csharp
using System;

var x = true;
if (x)
{
	Console.WriteLine("IF {0}", x);
}
else
{
	Console.WriteLine("ELSE {0}", x);
}
```

**Comment by glennblock** [comment]
Nope. I tried about 5 diff combos. else is just not recognized

**Comment by glennblock** [comment]
"(1,1): error CS1525: Unexpected symbol `else'". I tried also removing
braces, changing to an explicit var. Braces on the same line, braces on
diff lines.

**Comment by adamralph** [comment]
Wow :astonished:

**Comment by glennblock** [comment]
Yup...I am also shocked.

**Comment by gsscoder** [comment]
@adamralph, @glennblock, thanks for replying so fast... !!

It's not in the REPL, it happens running the file reported in the snippet exactly as it was published here.

For the _version_ question:
```zsh
➜  temp  scriptcs -Version
               _       _
 ___  ___ _ __(_)_ __ | |__ ___ ___
/ __|/ __| '__| | '_ \| __// __/ __|
\__ \ (__| |  | | |_) | |_| (__\__ \
|___/\___|_|  |_| .__/ \__\\___|___/
                |_| Version:

➜  temp
```

If I can help reporting other info from my system (OS X, zsh on iTerm, etc...) or anything else, let me know.

**Comment by adamralph** [comment]
lol - there's another bug https://github.com/scriptcs/scriptcs/issues/1055

**Comment by tobiaszuercher** [comment]
whats the state? on windows it's working, but on ubuntu & mac not :(
would be nice to have this one fixed!

**Comment by adamralph** [comment]
@tobiaszuercher this has been fixed by our Mono legend, @ztone, and will be in the 0.15.0 release.

**Comment by tobiaszuercher** [comment]
@adamralph awesome! actually i could remove all `else` as a workaround, but looking forward to update to 0.15.0!
thank you!
