### ISSUE TITLE
Can't install with Chocolatey (Windows 7)

### ISSUE THREAD

**Issue by gsscoder** [scriptcs/scriptcs#1063]
```PowerShell
PS C:\> nuget update -self
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 2.8.5.
NuGet.exe is up to date.
PS C:\> cinst scriptcs
Chocolatey (v0.9.8.20) is installing scriptcs and dependencies. By installing you accept the license for scriptcs and ea
ch dependency you are installing.
The schema version of 'LibGit2Sharp' is incompatible with version 2.1.31022.9038 of NuGet. Please upgrade NuGet to the l
atest version from http://go.microsoft.com/fwlink/?LinkId=213942.

Finished installing 'scriptcs' and dependencies - if errors not shown in console, none detected. Check log for errors if
 unsure.
```

**Comment by adamralph** [comment]
My knee jerk reaction to this is: chocolatey issue.

**Comment by khellang** [comment]
Yeah, choco is using another NuGet.exe than the one you have on your PATH. What happens if you run `cup` first?

**Comment by khellang** [comment]
You're using a really old version of chocolatey as well (0.9.8.20, from dec. 2012), which (naturally) comes with an older version of NuGet.exe. Updating it (by running `choco upgrade`, `chocolatey update` or `cup`) should solve this issue. You can check out the release notes [here](https://github.com/chocolatey/chocolatey/wiki/ReleaseNotes) :smile:

**Comment by gsscoder** [comment]
@khellang, @adamralph,
yes I'll post also to their project issues.

Anyway this what I get, after running `cup` (PS as Admin):
```PowerShell
PS C:\Windows\system32> cup
Chocolatey (v0.9.8.20) is installing chocolatey and dependencies. By installing you accept the license for chocolatey an
d each dependency you are installing.
The schema version of 'LibGit2Sharp' is incompatible with version 2.1.31022.9038 of NuGet. Please upgrade NuGet to the l
atest version from http://go.microsoft.com/fwlink/?LinkId=213942.

Finished installing 'chocolatey' and dependencies - if errors not shown in console, none detected. Check log for errors
if unsure.
PS C:\Windows\system32>
```

**Comment by khellang** [comment]
What about if you `cd` to `C:\Chocolatey\chocolateyinstall` and run `nuget update -self`?

**Comment by gsscoder** [comment]
@khellang, :+1: it workd! `cup` updated itself with same error, than I've restarted another shell and installed `scriptcs` with `choco install scriptcs`.

Now I'm able to start `scriptcs` in a non-admin shell without problems.
This is the version installed:
```PowerShell
PS C:\Users\vmuser> scriptcs -version
               _       _
 ___  ___ _ __(_)_ __ | |__ ___ ___
/ __|/ __| '__| | '_ \| __// __/ __|
\__ \ (__| |  | | |_) | |_| (__\__ \
|___/\___|_|  |_| .__/ \__\\___|___/
                |_| Version: 0.14.1
```

Thanks for support! :)

**Comment by khellang** [comment]
Glad you got it working! :grin::+1:
