### ISSUE TITLE
Cannot use array initializers

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#1070]
From https://github.com/scriptcs/scriptcs/issues/1066#issuecomment-125224907 by @sapiens

This

```C#
string[] Bla= new[]{"Something"};
```

throws.

**Comment by filipw** [comment]
Fixed in https://github.com/scriptcs/scriptcs/pull/1064

**Comment by adamralph** [comment]
Has the fix been proven?

**Comment by adamralph** [comment]
I can't recreate this in 0.15.

**Comment by filipw** [comment]
yeah i verified it

**Comment by adamralph** [comment]
Were you able to reproduce it in 0.15?
