### ISSUE TITLE
const string bug in Mono engine

### ISSUE THREAD

**Issue by khellang** [scriptcs/scriptcs#1076]
If I try to run the following code (on OSX using Mono)

``` csharp
#r Owin;
#r Microsoft.Owin;
#r Microsoft.Owin.Hosting;

using Owin;
using Microsoft.Owin.Hosting;

public static void Configure(IAppBuilder app)
{
    app.UseWelcomePage();
}

const string Url = "http://localhost:8080";

using (WebApp.Start(Url, Configure))
{
    Console.WriteLine("Running at {0}...", Url);
    Console.ReadLine();
}
```

It yields

> Running at ...

When I'd expect it to yield

> Running at http://localhost:8080...

And the Katana app fails silently (does not listen on the given URI).

If I change it to

``` csharp
#r Owin;
#r Microsoft.Owin;
#r Microsoft.Owin.Hosting;

using Owin;
using Microsoft.Owin.Hosting;

public static void Configure(IAppBuilder app)
{
    app.UseWelcomePage();
}

var url = "http://localhost:8080";

using (WebApp.Start(url, Configure))
{
    Console.WriteLine("Running at {0}...", url);
    Console.ReadLine();
}
```

Notice `const string Url` has been replaced by `var url`. Everything works perfectly :smile:

**Comment by adamralph** [comment]
Is it definitely a mono bug? Or is it our bizarre parsing stuff?

**Comment by khellang** [comment]
It's probably our bizarre parsing stuff, but it's mono specific.

**Comment by filipw** [comment]
looks like a mono bug

<img width="265" alt="screenshot 2015-08-05 19 48 34" src="https://cloud.githubusercontent.com/assets/1710369/9093218/fe231290-3baa-11e5-9b2c-a6dd132a79c1.png">

**Comment by adamralph** [comment]
@khellang as I understand that 'mono bug' labels mean 'a bug in mono'. And it looks like it is!

**Comment by khellang** [comment]
Well, mono and mono engine is the same as far as I'm concerned :wink:

**Comment by ztone** [comment]
Same issue as #1073

**Comment by adamralph** [comment]
@ztone I guess the two issues may share some underlying common cause but they feel very different.

In #1073, I sympathise with the Mono design that writing `private static int x = 123;` make no sense in a top level script, and it is only a quirk of Roslyn that allows this to work with the Roslyn engine. The only issue is the weird exception message that Mono gives us.

WRT to this issue, it makes sense to write `const int x = 123;` in top level script. In this case we don't even get an exception message. The assignment just fails silently.

**Comment by ztone** [comment]
@adamralph yeah, took a better look at this and you're right.  The using statement in #1073 before the <code>private static</code> keywords are causing the weird exception which is different from this issue.  This one feels like a genuine mono bug where the <code>const</code> should be supported but the assignment silently fails and instead assigns the default value.  This really needs to be patched in mono.

If no objection I can take this one and #1073.

**Comment by khellang** [comment]
You're my hero, @ztone :wink:

**Comment by adamralph** [comment]
@ztone to the rescue with Mono yet again. Thanks!

**Comment by filipw** [comment]
fixed by https://github.com/scriptcs/scriptcs/pull/1216
