### ISSUE TITLE
Create a package of scriptcs that is portable

### ISSUE THREAD

**Issue by hiredgunhouse** [scriptcs/scriptcs#1077]
I'd like to use scriptcs in my project for automation but I do not want to force it on other developers.
I want to put scriptcs inside a dedicated directory that will be put in the source control and use it from that location so that other developers are not forced to install it to their AppData.
I suppose it is possible to hack my way through it, but I believe that scriptcs should support such scenario anyway.

**Comment by adamralph** [comment]
@hiredgunhouse it is currently possible to download the chocolatey package, unpack it (it is just a zip file) and run scriptcs.exe. This is in fact exactly what I'm doing in the Linux build script for Bau - https://github.com/bau-build/bau/blob/66d6af4def5702b73e5d2646f5d790dd7437f061/.travis.yml#L5-L7

You can also use SVM to do an isolated per-user installation which doesn't touch any shared folders - https://github.com/scriptcs-contrib/svm

**Comment by glennblock** [comment]
This what svm does as well. It is very easy to just run scriptcs from a folder.

**Comment by paulbouwer** [comment]
@hiredgunhouse Have a look at the *Install version from path* section of the [Installing scriptcs versions](https://github.com/scriptcs-contrib/svm/wiki/Installing%20scriptcs%20versions) page on the svm wiki. This provides examples of what @adamralph and @glennblock are talking about.

**Comment by adamralph** [comment]
I guess https://github.com/scriptcs/scriptcs/issues/1061 would also be a solution here. You could install scriptcs as a solution level 'tools' package just like, for example, unit test runners.

**Comment by hiredgunhouse** [comment]
@adamralph that is exactly what I'm talking about, it just seems wrong to have to download the pacakge from chocolatey repository rather than from scriptcs' website or github (or from nuget).

@glennblock, @paulbouwer svm does not solve my problem cause it needs to be installed itself and I don't want to enforce other devs to have to install and/or configure anything (including PowerShell's RemoteSigned policy) cause I don't want them to start complaining.
The best way for me is if my "scriptcs little helper tools" thing just works without them even knowing how it is done and what the dependencies are (sometimes it's just too hard to change other people's mindset and the next best thing you can do is to workaround their hesitance without them even knowing :)

Anyway I can see (from @adamralph's comment) you are working on creating a NuGet packge and this will work for me cause I will be able to use NuGet.exe to download scriptcs and use it in a portable way.
