### ISSUE TITLE
Proposed new syntax for referencing NuGet packages with a script

### ISSUE THREAD

**Issue by PaulStovell** [scriptcs/scriptcs#1081]
When writing a ScriptCS script, you can use `#r` to load assemblies, and `#load` to reference other ScriptCS files:

https://github.com/scriptcs/scriptcs/wiki/Writing-a-script#referencing-assemblies

As far as I know, there's no way to specify which NuGet packages/script packs your script needs inside the script - it has to be specified as a separate packages.config or using `ScriptCS -install`. 

Would a syntax for referencing NuGet packages inside the script be useful? If I sent a PR, would the community be interested in it? 

Something like:

```
#nuget NUnit 2.6.4
#r "nunit.core.dll"
#load setup.csx
// Do stuff
```

This would make it easier to create reusable ScriptCS scripts that can be shared without also having to share packages.config separately. It also makes it more consistent with the two other ways to "import" something.

**Comment by glennblock** [comment]
Hi Paul

We are in discussion with the Roslyn team on this becoming part of the Roslyn spec. The idea is #load will allow you to specify s package name. 

Assuming that is finalized, which should be soon, we would embrace the same for scriptcs.

**Comment by PaulStovell** [comment]
Excellent!

**Comment by jnm2** [comment]
Has there been any progress on this? I'm coming from Cake which has me spoiled with the ability to reference a NuGet package with a single directive.

It's a bit frustrating because all I wanted to do was test a single API. `scriptcs -install Newtonsoft.Json` doesn't work at the command line. (Unable to resolve dependency 'Microsoft.CSharp (≥ 4.0.1)'.)

**Comment by glennblock** [comment]
Which version of scriptcs are you using? There is a pending PR which once I merge should fix all these issues.

As to supporting packages for `#load`, I am not opposed to it, I'll take a look at what it will take.

**Comment by jnm2** [comment]
Not sure which version, `scriptcs -?` doesn't display it.

**Comment by glennblock** [comment]
You must be on mac/linux. Version hasn't been working there for a while
(which there is a pending fix for)

Our latest release 0.17.0 should work but we have another important fix
which has to go out. It will ship with 0.17.1 in a day or two.

**Comment by jnm2** [comment]
Huh. Now I'm confused, cause I'm on win10-x64.

I tracked it down to it being installed by chocolatey at 0.16.1, which must have happened when I installed the VS Code runner? I'm positive I didn't `choco install` it myself.

**Comment by jnm2** [comment]
No version displayed for `scriptcs -?`, and the file I'm running is 0.17.0 according to file properties for the `where scriptcs` location.

**Comment by glennblock** [comment]
Weird. OK.

**Comment by jnm2** [comment]
Wait- the version isn't printed, but the -v option is listed which I missed because I was looking at the top of the output by the usage line. I would expect to see it printed there. `-v` works!

**Comment by glennblock** [comment]
OK. 0.17.1 should fix the error you are seeing. Can you try my 1213 branch? It has a NuGet fix which should address your problem using JSON.NET.

**Comment by jnm2** [comment]
@glennblock Sure. Checked out https://github.com/glennblock/scriptcs/tree/1213. `build` gave me:

>   Restoring NuGet packages...
  System.InvalidOperationException: Unable to find version '1.9.2' of package 'xunit.runners'.
     at NuGet.PackageHelper.ResolvePackage(IPackageRepository repository, String packageId, SemanticVersion version)
     at NuGet.Commands.RestoreCommand.RestorePackage(IFileSystem packagesFolderFileSystem, String packageId, SemanticVe
  rsion version, Boolean packageRestoreConsent, ConcurrentQueue`1 satellitePackages)
     at NuGet.Commands.RestoreCommand.<>c__DisplayClass5.<>c__DisplayClass7.<ExecuteInParallel>b__2()
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
C:\Users\jmusser\Desktop\scriptcs\Build\Build.proj(93,5): error MSB3073: The command ""C:\Users\jmusser\Desktop\scriptc
s\Build\..\.nuget\NuGet.exe" restore -Verbosity detailed -NonInteractive" exited with code 1.

**Comment by glennblock** [comment]
Strange, I just cloned fresh and checked out 1213 and build works fine. 

```
PS C:\src\scriptcs_test\scriptcs> ./build.cmd
  Restoring NuGet packages...
  ScriptCs.Contracts -> C:\src\scriptcs_test\scriptcs\src\ScriptCs.Contracts\b
  in\Release\ScriptCs.Contracts.dll
  ScriptCs.Core -> C:\src\scriptcs_test\scriptcs\src\ScriptCs.Core\bin\Release
  \ScriptCs.Core.dll
  ScriptCs.Engine.Mono -> C:\src\scriptcs_test\scriptcs\src\ScriptCs.Engine.Mo
  no\bin\Release\ScriptCs.Engine.Mono.dll
  ScriptCs.Hosting -> C:\src\scriptcs_test\scriptcs\src\ScriptCs.Hosting\bin\R
  elease\ScriptCs.Hosting.dll
  ScriptCs.Engine.Roslyn -> C:\src\scriptcs_test\scriptcs\src\ScriptCs.Engine.
  Roslyn\bin\Release\ScriptCs.Engine.Roslyn.dll
  ScriptCs.Engine.Mono.Tests -> C:\src\scriptcs_test\scriptcs\test\ScriptCs.En
  gine.Mono.Tests\bin\Release\ScriptCs.Engine.Mono.Tests.dll
  ScriptCs.Core.Tests -> C:\src\scriptcs_test\scriptcs\test\ScriptCs.Core.Test
  s\bin\Release\ScriptCs.Core.Tests.dll
  ScriptCs -> C:\src\scriptcs_test\scriptcs\src\ScriptCs\bin\Release\scriptcs.
  exe
  ScriptCs.Engine.Roslyn.Tests -> C:\src\scriptcs_test\scriptcs\test\ScriptCs.
  Engine.Roslyn.Tests\bin\Release\ScriptCs.Engine.Roslyn.Tests.dll
  ScriptCs.Tests -> C:\src\scriptcs_test\scriptcs\test\ScriptCs.Tests\bin\Rele
  ase\ScriptCs.Tests.dll
  ScriptCs.Hosting.Tests -> C:\src\scriptcs_test\scriptcs\test\ScriptCs.Hostin
  g.Tests\bin\Release\ScriptCs.Hosting.Tests.dll
  ScriptCs.Tests.Acceptance -> C:\src\scriptcs_test\scriptcs\test\ScriptCs.Tes
  ts.Acceptance\bin\Release\ScriptCs.Tests.Acceptance.dll
  xUnit.net MSBuild runner (32-bit .NET 4.0.30319.42000)
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\src\scriptcs_test\scriptcs\test\ScriptCs.Core.Tests\bin\Re
  lease\ScriptCs.Core.Tests.dll
    Tests: 230, Failures: 0, Skipped: 0, Time: 1.709 seconds
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\src\scriptcs_test\scriptcs\test\ScriptCs.Engine.Mono.Tests
  \bin\Release\ScriptCs.Engine.Mono.Tests.dll
    Tests: 58, Failures: 0, Skipped: 0, Time: 2.812 seconds
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\src\scriptcs_test\scriptcs\test\ScriptCs.Engine.Roslyn.Tes
  ts\bin\Release\ScriptCs.Engine.Roslyn.Tests.dll
    Tests: 27, Failures: 0, Skipped: 0, Time: 4.227 seconds
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\src\scriptcs_test\scriptcs\test\ScriptCs.Hosting.Tests\bin
  \Release\ScriptCs.Hosting.Tests.dll
    Tests: 89, Failures: 0, Skipped: 0, Time: 2.269 seconds
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\src\scriptcs_test\scriptcs\test\ScriptCs.Tests\bin\Release
  \ScriptCs.Tests.dll
    Tests: 45, Failures: 0, Skipped: 0, Time: 1.206 seconds
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\src\scriptcs_test\scriptcs\test\ScriptCs.Tests.Acceptance\
  bin\Release\ScriptCs.Tests.Acceptance.dll
C:\src\scriptcs_test\scriptcs\Build\Build.proj : warning : ScriptCs.Tests.Acce ptance.Packages.PackageContainsAFrameworkAssemblyReference: Failing with a pat h length exception
C:\src\scriptcs_test\scriptcs\Build\Build.proj : warning : ScriptCs.Tests.Acce ptance.ScriptLibraries.UsingAMethodInAScriptLibraryInTheRepl: Failing with a p ath length exception
    Tests: 101, Failures: 0, Skipped: 2, Time: 98.113 seconds
  Building NuGet packages...

**** BUILD SUCCESSFUL ***
```

**Comment by jnm2** [comment]
I replaced `/.nuget/NuGet.exe` with `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe` and it started working.

**Comment by jnm2** [comment]
I have to take a break, but this si what I've got so far:

```
C:\Users\jmusser\Desktop\scriptcs>build
  Restoring NuGet packages...
  ScriptCs.Contracts -> C:\Users\jmusser\Desktop\scriptcs\src\ScriptCs.Contracts\bin\Release\ScriptCs.Contracts.dll
  ScriptCs.Core -> C:\Users\jmusser\Desktop\scriptcs\src\ScriptCs.Core\bin\Release\ScriptCs.Core.dll
  ScriptCs.Engine.Mono -> C:\Users\jmusser\Desktop\scriptcs\src\ScriptCs.Engine.Mono\bin\Release\ScriptCs.Engine.Mono.dll
  ScriptCs.Hosting -> C:\Users\jmusser\Desktop\scriptcs\src\ScriptCs.Hosting\bin\Release\ScriptCs.Hosting.dll
  ScriptCs.Engine.Roslyn -> C:\Users\jmusser\Desktop\scriptcs\src\ScriptCs.Engine.Roslyn\bin\Release\ScriptCs.Engine.Roslyn.dll
  ScriptCs.Engine.Mono.Tests -> C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Engine.Mono.Tests\bin\Release\ScriptCs.Engine.Mono.Tests.dll
  ScriptCs.Hosting.Tests -> C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Hosting.Tests\bin\Release\ScriptCs.Hosting.Tests.dll
  ScriptCs.Core.Tests -> C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Core.Tests\bin\Release\ScriptCs.Core.Tests.dll
  ScriptCs.Engine.Roslyn.Tests -> C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Engine.Roslyn.Tests\bin\Release\ScriptCs.Engine.Roslyn.Tests.dll
  ScriptCs -> C:\Users\jmusser\Desktop\scriptcs\src\ScriptCs\bin\Release\scriptcs.exe
  ScriptCs.Tests -> C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Tests\bin\Release\ScriptCs.Tests.dll
  ScriptCs.Tests.Acceptance -> C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Tests.Acceptance\bin\Release\ScriptCs.Tests.Acceptance.dll
  xUnit.net MSBuild runner (32-bit .NET 4.0.30319.42000)
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Core.Tests\bin\Release\ScriptCs.Core.Tests.dll
    Tests: 230, Failures: 0, Skipped: 0, Time: 1.111 seconds
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Engine.Mono.Tests\bin\Release\ScriptCs.Engine.Mono.Tests.dll
    Tests: 58, Failures: 0, Skipped: 0, Time: 2.346 seconds
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Engine.Roslyn.Tests\bin\Release\ScriptCs.Engine.Roslyn.Tests.dll
    Tests: 27, Failures: 0, Skipped: 0, Time: 2.807 seconds
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Hosting.Tests\bin\Release\ScriptCs.Hosting.Tests.dll
    Tests: 89, Failures: 0, Skipped: 0, Time: 1.768 seconds
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Tests\bin\Release\ScriptCs.Tests.dll
    Tests: 45, Failures: 0, Skipped: 0, Time: 0.774 seconds
  xunit.dll:     Version 1.9.2.1705
  Test assembly: C:\Users\jmusser\Desktop\scriptcs\test\ScriptCs.Tests.Acceptance\bin\Release\ScriptCs.Tests.Acceptance.dll
C:\Users\jmusser\Desktop\scriptcs\Build\Build.proj : warning : ScriptCs.Tests.Acceptance.Packages.PackageContainsAFrameworkAssemblyReference: Failing with a path length exception
C:\Users\jmusser\Desktop\scriptcs\Build\Build.proj : warning : ScriptCs.Tests.Acceptance.ScriptLibraries.UsingAMethodInAScriptLibraryInTheRepl: Failing with a path length exception
    Tests: 101, Failures: 0, Skipped: 2, Time: 64.802 seconds
  Building NuGet packages...
  Could not find a part of the path 'C:\Users\jmusser\Desktop\scriptcs\src\lib'.
C:\Users\jmusser\Desktop\scriptcs\Build\Build.proj(87,5): error MSB3073: The command ""C:\Users\jmusser\Desktop\scriptcs\Build\..\.nuget\NuGet.exe" pack "C:\Users\jmusser\Desktop\scriptcs\Build\..\src\Scrip
tCs.Engine.Roslyn\ScriptCs.Engine.Roslyn.csproj" -Version 0.17.0 -Symbols -Verbosity quiet -NoPackageAnalysis -OutputDirectory "C:\Users\jmusser\Desktop\scriptcs\Build\..\artifacts\Release" -p Configuration
=Release" exited with code 1.
```

**Comment by glennblock** [comment]
It looks like it compiled and ran the build fine, but it failed to build
packages. I wonder if the pathname is too long. Never seen that before.

**Comment by jnm2** [comment]
I tried again at `C:\`, same thing:

```
Test assembly: C:\scriptcs\test\ScriptCs.Tests.Acceptance\bin\Release\ScriptCs.Tests.Acceptance.dll
C:\scriptcs\Build\Build.proj : warning : ScriptCs.Tests.Acceptance.Packages.PackageContainsAFrameworkAssemblyReference:
 Failing with a path length exception
C:\scriptcs\Build\Build.proj : warning : ScriptCs.Tests.Acceptance.ScriptLibraries.UsingAMethodInAScriptLibraryInTheRep
l: Failing with a path length exception
```

You can't get the path much shorter than that. :) Anyway, to verify my case, all you have to do is execute `scriptcs -i newtonsoft.json` and make sure that it succeeds, right?

**Comment by glennblock** [comment]
That works for me. Can you check what branch you are in? "git branch"

**Comment by jnm2** [comment]
```
C:\s>git branch
* 1213
  master
```

**Comment by glennblock** [comment]
can you do `git log -n 3` and send the output?

**Comment by jnm2** [comment]
```
C:\s>git log -n 3
commit fce84286efe290df7e73e475b3e5dfecdf979f90
Author: Glenn Block <glenn.block@gmail.com>
Date:   Fri Feb 17 01:43:43 2017 -0800

    Adding logic to autodetect framework version. Thanks to @daveaglick

commit 84e4ca95c178208cf7349fa21aed5952bf8bdc61
Author: Glenn Block <glenn.block@gmail.com>
Date:   Thu Feb 16 00:34:27 2017 -0800

    Adding custom package manager to allow forcing framework target version

commit 4f199307ef3c5ae252f0e2b69245d9e31092fce0
Author: Glenn Block <glenn.block@gmail.com>
Date:   Sun Feb 12 23:37:28 2017 -0800

    Ignoring failing acceptance tests
```

**Comment by glennblock** [comment]
OK, well that's the most current.

And you are getting errors when you do `scripts -i newtonsoft.json` ? Sorry for the all the questions, if you can head to our slack we can talk at higher bandwidth :-)

**Comment by glennblock** [comment]
It is still failing at the "Build packages" step?

**Comment by jnm2** [comment]
`scripts -i newtonsoft.json` works great with 0.17.0 which I got from chocolatey.
How do I find the slack channel?

Yes:
```
  Building NuGet packages...
  Could not find a part of the path 'C:\s\src\lib'.
C:\s\Build\Build.proj(87,5): error MSB3073: The command ""C:\s\Build\..\.nuget\NuGet.exe" pack "C:\s\Build\..\src\Scrip
tCs.Engine.Roslyn\ScriptCs.Engine.Roslyn.csproj" -Version 0.17.0 -Symbols -Verbosity quiet -NoPackageAnalysis -OutputDi
rectory "C:\s\Build\..\artifacts\Release" -p Configuration=Release" exited with code 1.
```

**Comment by glennblock** [comment]
https://scriptcs-slack.herokuapp.com/

**Comment by jnm2** [comment]
I'm looking for a script runner which
 - can be bootstrapped from any computer using a Windows `.cmd` file without installing Chocolatey
 - can transitively reference assemblies from NuGet using a single directive and without introducing a file separate to the .csx file
 - can be understood by OmniSharp (code fixes, go to definition, debugging)

How close is scriptcs to this?

**Comment by filipw** [comment]
@jnm2 https://github.com/filipw/dotnet-script can do all of this

It will all eventually become part of scriptcs too, however there are certain limitations with the current scriptcs design vs the Roslyn extensibility points

**Comment by jnm2** [comment]
Oh perfect! Felt like I was missing one I remembered... wonder how I couldn't find that. Thanks!

**Comment by jjwilliams42** [comment]
Whatever happened to this?
