### ISSUE TITLE
private classes are accessible

### ISSUE THREAD

**Issue by phest** [scriptcs/scriptcs#1083]
This does not throw an error:

```csharp
class A { private class B {}}

class C {
  public void F() {
    A.B obj = new A.B();
  }
}
```

Is this part of the relaxed syntax mentioned in `README.md`? If so is there a reference for the differences? Thanks.

**Comment by glennblock** [comment]
Looks like this is a mono specific issue / may be mono bug or an issue with our engine.

Running the same on Windows using the Roslyn engine gets this:
```
C:\test> scriptcs test.csx
ERROR: Script compilation failed: C:\test\test.csx(7,19): error CS0122: 'A.B' is inaccessible due to its protection level.
```

@ztone @filipw any ideas?

**Comment by phest** [comment]
For what it's worth:
```
class A { private class B {}}

public class Test {
  static public void Main () {
    A.B obj;
  }
}
```


```
mcs test.csx
test.csx(5,7): error CS0122: `A.B' is inaccessible due to its protection level
Compilation failed: 1 error(s), 0 warnings
```

**Comment by glennblock** [comment]
And this works....

```csharp
private class A { 
    private class B { 
        public void Foo() {
        }
    } 
}

class C
{
    public void F()
    {
        A.B obj = new A.B();
        obj.Foo();
    }
}
```

**Comment by ztone** [comment]
It's a mono bug not our engine.
![image](https://cloud.githubusercontent.com/assets/3028306/9452144/7fbc5d94-4aaa-11e5-9294-09ac97d0326a.png)

**Comment by glennblock** [comment]
Closing as this is not a scriptcs issue
