### ISSUE TITLE
dynamic is available only with mono, but mono fails on DLL

### ISSUE THREAD

**Issue by denfromufa** [scriptcs/scriptcs#1092]
Hi, 
I'm try to load pythonnet runtime dll from scriptcs and it does not work with roslyn backend because `dynamic` is not supported, and mono backend chokes with the following error:

```
$ scriptcs -modules mono
scriptcs (ctrl-c to exit or :help for help)

> #r "F:\Python\Python27\Lib\site-packages\Python.Runtime.dll"
error CS0009: Metadata file `F:\Python\Python27\Lib\site-packages\Python.Runtime.dll' does not contain valid metadata
```

**Comment by denfromufa** [comment]
I have a bounty open on SO:

http://stackoverflow.com/questions/32471727/for-scriptcs-dynamic-is-not-supported-by-roslyn-and-available-only-with-mono

**Comment by adamralph** [comment]
@denfromufa I see two issues coming out of this:

* Support the `dynamic` keyword in the Roslyn engine - this has been done in #1057, but not yet released
* The mono engine chokes on Python.Runtime.dll

Regarding the latter, is Python.Runtime.dll a managed (.NET) assembly or is it native?

**Comment by denfromufa** [comment]
Python.Runtime.DLL should be completely managed assembly, at least the
embedding bits of it. Pythonnet uses PInvoke to call into native CPython
API with unsafe blocks.

clr.pyd (extending CPython with .NET) is a different story.

**Comment by adamralph** [comment]
@denfromufa thanks. In that case, I'll close this issue and spin off a bug for that.
