### ISSUE TITLE
Passing c# as a command line argument

### ISSUE THREAD

**Issue by richorama** [scriptcs/scriptcs#1096]
Is it possible to pass code as a command line argument. For example:

```
scriptcs -Script "Console.Beep()"
```

This kind of functionality is available in node (`node -e "console.log('hello world');"`) and python (`python -c "print 'hello world'"`)

**Comment by adamralph** [comment]
@richorama thanks for raising this. It has been talked about before and I thought we already had an issue raised but I couldn't find one, so it's good that you raised this so we have the idea captured.

**Comment by glennblock** [comment]
I believe I filed an issue for this

**Comment by glennblock** [comment]
Closing as this is a dup of #1085
