### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by WenningQiu** [scriptcs/scriptcs#1101]
I am using scriptcs 0.15.0 installed from Chocolatey to convert one of our existing Powershell scripts to C#, but ran into a File Not Found error. From the scriptcs output there is no clue as to what file is missing. 

C:\work\Git\stathub\Scripts\StatHub\Windows>scriptcs configure-stathub-indexes.csx -loglevel debug
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IAppDomainAssemblyResolver
DEBUG: [ScriptCs.Hosting.InitializationServices] Registering initialization services
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IFileSystem
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IAssemblyUtility
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageContainer
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageAssemblyResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IAssemblyResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IInstallationProvider
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageInstaller
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Hosting.IModuleLoader
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IAppDomainAssemblyResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IFilePreProcessor
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Autofac to version:3.3.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Autofac.Integration.Mef to version:3.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Common.Logging to version:2.1.2.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ICSharpCode.NRefactory.CSharp to version:5.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ICSharpCode.NRefactory to version:5.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Microsoft.Web.XmlTransform to version:2.1.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Mono.Cecil to version:0.9.5.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Mono.CSharp to version:4.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Newtonsoft.Json to version:6.0.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly NuGet.Core to version:2.8.60717.93
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly PowerArgs to version:2.0.4.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Roslyn.Compilers.CSharp to version:1.2.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Roslyn.Compilers to version:1.2.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Contracts to version:0.15.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Core to version:0.15.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Engine.Mono to version:0.15.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Engine.Roslyn to version:0.15.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly ScriptCs.Hosting to version:0.15.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly scriptcs to version:0.15.0.0
DEBUG: [ScriptCs.AssemblyResolver] Found assembly in bin folder: Castle.Core.dll
DEBUG: [ScriptCs.AssemblyResolver] Found assembly in bin folder: Castle.Windsor.dll
DEBUG: [ScriptCs.AssemblyResolver] Found assembly in bin folder: CSG.Framework.dll
DEBUG: [ScriptCs.AssemblyResolver] Found assembly in bin folder: log4net.dll
DEBUG: [ScriptCs.AssemblyResolver] Found assembly in bin folder: Newtonsoft.Json.dll
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Castle.Core to version:3.2.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Castle.Windsor to version:3.2.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly CSG.Framework to version:15.4.0.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly log4net to version:1.2.13.0
DEBUG: [ScriptCs.AppDomainAssemblyResolver] Mapping Assembly Newtonsoft.Json to version:7.0.0.0
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IModuleLoader
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IFileSystem
DEBUG: [ScriptCs.Hosting.ModuleLoader] Only CSharp module is needed - will skip module lookup
DEBUG: [ScriptCs.Hosting.ModuleLoader] Initializing module: System.Reflection.RuntimeAssembly
DEBUG: [ScriptCs.Hosting.ScriptServicesBuilder] Resolving ScriptServices
DEBUG: [ScriptCs.Hosting.ScriptServicesBuilder] Registering runtime services
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IFileSystem
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IAssemblyUtility
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageContainer
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageAssemblyResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IAssemblyResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IScriptHostFactory
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IFilePreProcessor
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IScriptPackResolver
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IInstallationProvider
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IPackageInstaller
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.ScriptServices
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IObjectSerializer
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IConsole
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IFileSystemMigrator
DEBUG: [ScriptCs.Hosting.ScriptServicesRegistration] Registering default: ScriptCs.Contracts.IScriptLibraryComposer
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IAssemblyResolver
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IAssemblyUtility
DEBUG: [ScriptCs.FileSystemMigrator] Not performing migration since directory 'scriptcs_bin' already exists.
DEBUG: [ScriptCs.Hosting.InitializationServices] Resolving IInstallationProvider
DEBUG: [ScriptCs.FileSystemMigrator] Not performing migration since directory 'scriptcs_bin' already exists.
DEBUG: [ScriptCs.AssemblyResolver] Found assembly in bin folder: Castle.Core.dll
DEBUG: [ScriptCs.AssemblyResolver] Found assembly in bin folder: Castle.Windsor.dll
DEBUG: [ScriptCs.AssemblyResolver] Found assembly in bin folder: CSG.Framework.dll
DEBUG: [ScriptCs.AssemblyResolver] Found assembly in bin folder: log4net.dll
DEBUG: [ScriptCs.AssemblyResolver] Found assembly in bin folder: Newtonsoft.Json.dll
DEBUG: [ScriptCs.ScriptExecutor] Initializing script packs
DEBUG: [ScriptCs.FilePreProcessor] Starting pre-processing
DEBUG: [ScriptCs.FilePreProcessor] Processing configure-stathub-indexes.csx...
DEBUG: [ScriptCs.FilePreProcessor] Pre-processing finished successfully
DEBUG: [ScriptCs.ScriptExecutor] Starting execution in engine
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Starting to create execution components
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Creating script host
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Creating session
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to System
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to System.Core
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to System.Data
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to System.Data.DataSetExtensions
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to System.Xml
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to System.Xml.Linq
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to System.Net.Http
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to C:\ProgramData\chocolatey\lib\ScriptCs\tools\ScriptCs.Core.dll
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to C:\ProgramData\chocolatey\lib\ScriptCs\tools\ScriptCs.Contracts.dll
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to C:\work\Git\stathub\Scripts\StatHub\Windows\scriptcs_bin\Castle.Core.dll
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to C:\work\Git\stathub\Scripts\StatHub\Windows\scriptcs_bin\Castle.Windsor.dll
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to C:\work\Git\stathub\Scripts\StatHub\Windows\scriptcs_bin\CSG.Framework.dll
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to C:\work\Git\stathub\Scripts\StatHub\Windows\scriptcs_bin\log4net.dll
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to C:\work\Git\stathub\Scripts\StatHub\Windows\scriptcs_bin\Newtonsoft.Json.dll
DEBUG: [ScriptCs.Engine.Roslyn.RoslynScriptEngine] Adding reference to System.Collections.Generic
ERROR: [ScriptCs.Command.ExecuteScriptCommand] Error executing script 'configure-stathub-indexes.csx' [System.IO.FileNotFoundException] Assembly not found.
   at Roslyn.Scripting.CommonScriptEngine.CreateMetadataReference(String assemblyDisplayNameOrPath, FileResolver fileResolver)
   at ScriptCs.Engine.Roslyn.RoslynScriptEngine.Execute(String code, String[] scriptArgs, AssemblyReferences references, IEnumerable`1 namespaces, ScriptPackSession scriptPackSession)
   at ScriptCs.ScriptExecutor.EngineExecute(String workingDirectory, String[] scriptArgs, FilePreProcessorResult result)
   at ScriptCs.Command.ExecuteScriptCommand.Execute()

**Comment by khellang** [comment]
Well, what files are you referencing? Could you share your `configure-stathub-indexes.csx` script?

**Comment by WenningQiu** [comment]
Looks like it cannot handle the reference to "System.Diagnostics". The error can be reproduced with the script below:

#r "System.Diagnostics"

Console.WriteLine("Hello world!");

**Comment by adamralph** [comment]
The .NET framework does not include an assembly named "System.Diagnostics", so the error message is correct.

The `System.Diagnostics` namespace is contained in both the "System" and "mscorlib" assemblies. Both of these are referenced by default in scriptcs so you can just add a using:

```C#
using System.Diagnostics;

...
```

**Comment by WenningQiu** [comment]
Thanks! I apparently had confused #r with using.
