### ISSUE TITLE
move official chat away from JabbR

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#1104]
- [ ] decide what to use
- [ ] change readme.md
- [ ] change website
- [ ] change JabbR topic to redirect people to the new chat home

**Comment by khellang** [comment]
Y NO SLACK? :cry:

**Comment by adamralph** [comment]
Is it free? I :heart: slack.

**Comment by khellang** [comment]
Yes, yes it is. There is the invite model, tho. We're discussing moving the Nancy chat to Slack using [Slackin](https://github.com/rauchg/slackin). It essentially removes the invite model by allowing anyone to automatically "invite" themselves. We've already moved our team chat and it's lovely!

**Comment by adamralph** [comment]
The only downside is that it is a separate site for every team. E.g. I already have slacks for xunit, Particular, and a few others. With Gitter the chats for all my OSS projects live in one browser tab. With Slack, it would be a browser tab explosion.

**Comment by khellang** [comment]
It's not that bad...

![image](https://cloud.githubusercontent.com/assets/582487/10631585/3d476f50-77df-11e5-930c-5af636be4a45.png)

If you use the desktop client, it's even better :smile:

**Comment by adamralph** [comment]
That doesn't really offer much. It's still a site switch. E.g. I can't see new message notifications from the previous site after I switch.

**Comment by adamralph** [comment]
And it gets worse with direct messages, all of a sudden I might have 3 different khellang's in three difference slack sites :smile:

**Comment by RichiCoder1** [comment]
Facebook moved to (Discord)[http://facebook.github.io/react/blog/2015/10/19/reactiflux-is-moving-to-discord.html] and some have started looking into either Mattermost or rocket.chat. But popular opinion seems to be moving against Slack both for the friction introduced by the invite system and the "closedness" around it.

Sincerely, Some Random Dude

**Comment by adamralph** [comment]
@RichiCoder1 (a.k.a. Some Random Dude) thanks for chiming in :smile:.

Following your link, I just signed up for Discord. It looks interesting! I created a scriptcs server to play around with - https://discord.gg/0cNcBvr6t9XqWQOA

**Comment by jrusbatch** [comment]
My vote is for Gitter. We already have a room set up, and I think all of us are in it. For open source projects, I prefer that over Slack.

**Comment by adamralph** [comment]
Mv vote goes with Gitter too.

**Comment by hmemcpy** [comment]
There's been some ranting recently about how [slack is bad for OSS projects](https://drewdevault.com/2015/11/01/Please-stop-using-slack.html). I think gitter is better for interacting on projects on github, because it's so well integrated.

p.s. discord looks nice!

**Comment by SimonCropp** [comment]
I would prefer a native client but the gitter one is pretty cumbersome and shows no indication of it being improved or evolving

**Comment by damianh** [comment]
We're thinking same for Nancy. At least for our private room first, before the community room. The team went for slack.

Personally I prefer gitter for oss because it's more accessible to a community and relates well with github. Yeah, the mobile client is not as slick as slack :(

**Comment by phillip-haydon** [comment]
@damianh i actually prefer gitter, i just hate gitter android client.

**Comment by mydigitalself** [comment]
@phillip-haydon found this via Twitter - we've neglected the Android app and have started shipping improvements every 2 weeks for the last couple of months. Have you used it recently and is it getting better? Feel free to get in touch on team at gitter im

**Comment by phillip-haydon** [comment]
@mydigitalself have you fixed notifications. I asked on twitter and was told to turn off notifications at the android application settings. 

I wanted to get ONLY notifications of mentions to myself for 1 room I'm in, on my phone. Because I feel those are important, but the rest are annoying, on my phone...

**Comment by mydigitalself** [comment]
@phillip-haydon that's coming next alongside a big change to notifications in general across both mobile and web.

**Comment by phillip-haydon** [comment]
Ok, until notifications are implemented properly I wont try it. Sorry.

**Comment by adamralph** [comment]
@mydigitalself thanks for chiming in. It's great to hear that you're improving Gitter on Android. It's been a while since I tried it so I'll give it another try and report back.

**Comment by phillip-haydon** [comment]
:+1: @adamralph

**Comment by glennblock** [comment]
Same on gitter. We are always there anyway so I am biased :-). I like the
idea of one client even though there mobile client has lots of issues

**Comment by damianh** [comment]
I dont disagree

**Comment by glennblock** [comment]
Hmm @damianh gives a double negative response.....how to interpret....

**Comment by damianh** [comment]
it was directed at Phillip regarding the gitter mobile experience ;)

**Comment by khellang** [comment]
I don't not agree either :wink:

**Comment by engelgabriel** [comment]
What are your thoughts on going and supporting a free open source project like our Rocket.Chat?
We may be not as mature as Gitter and Discord, but we are growing really fast, and the more communities join and help us make it better, all the OSS community wins.

You guys can test your own server at http://scriptcs.rocket.chat/ and give us some feedback?

I've create a user for @glennblock (password sent via email) and made him admin. He can make anyone admins too :)
