### ISSUE TITLE
Unable to find any package using -install

### ISSUE THREAD

**Issue by gregoks** [scriptcs/scriptcs#1108]
Hi,

Doesnt matter which package I try to install using the "scriptcs -install" command, it always gives me error "Unable to find package". I'm using v0.15.0.

I've tried ScriptCs.Nancy, MongoDB, ScriptCs.WebAoi

Here is an error example:

ERROR: Error installing package. [InvalidOperationException] Unable to find pack
age 'mongodb'.
ERROR: Package installation failed: System.AggregateException: One or more error
s occurred. ---> System.InvalidOperationException: Unable to find package 'mongo
db'.
   at NuGet.PackageRepositoryHelper.ResolvePackage(IPackageRepository sourceRepo
sitory, IPackageRepository localRepository, IPackageConstraintProvider constrain
tProvider, String packageId, SemanticVersion version, Boolean allowPrereleaseVer
sions)
   at NuGet.PackageManager.InstallPackage(String packageId, SemanticVersion vers
ion, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at ScriptCs.Hosting.Package.NugetInstallationProvider.InstallPackage(IPackage
Reference packageId, Boolean allowPreRelease)
   at ScriptCs.Hosting.Package.PackageInstaller.InstallPackages(IEnumerable`1 pa
ckageIds, Boolean allowPreRelease)
   --- End of inner exception stack trace ---
   at ScriptCs.Hosting.Package.PackageInstaller.InstallPackages(IEnumerable`1 pa
ckageIds, Boolean allowPreRelease)
   at ScriptCs.Command.InstallCommand.Execute()
---> (Inner Exception #0) System.InvalidOperationException: Unable to find packa
ge 'mongodb'.
   at NuGet.PackageRepositoryHelper.ResolvePackage(IPackageRepository sourceRepo
sitory, IPackageRepository localRepository, IPackageConstraintProvider constrain
tProvider, String packageId, SemanticVersion version, Boolean allowPrereleaseVer
sions)
   at NuGet.PackageManager.InstallPackage(String packageId, SemanticVersion vers
ion, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at ScriptCs.Hosting.Package.NugetInstallationProvider.InstallPackage(IPackage
Reference packageId, Boolean allowPreRelease)
   at ScriptCs.Hosting.Package.PackageInstaller.InstallPackages(IEnumerable`1 pa
ckageIds, Boolean allowPreRelease)<---

Thanks,

Greg

**Comment by adamralph** [comment]
@gregoks I have the same problem on my machine which only has VS2015 (and therefore NuGet 3.x installed).

The problem is that NuGet 3.x installs a packages.config file containing something like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <activePackageSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
  <disabledPackageSources />
</configuration>
```

scriptcs uses the NuGet.Core 2.x package and that must be ignoring the `nuget.org` entry due to `protocolVersion="3"`.

The only thing I can suggest is that you add an extra package source for `nuget.org v2`, e.g.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org v2" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <activePackageSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
  <disabledPackageSources />
</configuration>
```

I've confirmed that this works for me.

**Comment by adamralph** [comment]
Alternatively you could add a file to your local directory named `scriptcs_nuget.config`, containing:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org v2" value="https://www.nuget.org/api/v2/" />
  </packageSources>
</configuration>
```

**Comment by adamralph** [comment]
I've moved these instruction to the wiki - https://github.com/scriptcs/scriptcs/wiki/NuGet-v3 filed under "Known Issues" in the TOC.

**Comment by adamralph** [comment]
@gregoks thanks very much for raising this and bringing it to our attention.

**Comment by gregoks** [comment]
@adamralph Thanks for the quick fix! Indeed I have VS 2012 installed.

I've tried adding scriptcs_nuget.config to my working directory and it works.

**Comment by adamralph** [comment]
@gregoks you're welcome!

(I presume you mean VS 2015?)

**Comment by gregoks** [comment]
Actually no..I had this error with VS 2012 and your solution fixed it but when installed VS 2015 and the nuget changed to version 3, it worked without your solution..

**Comment by adamralph** [comment]
Hmmm... interesting. Perhaps your `%appdata%\NuGet\NuGet.config` was in a funny state before you installed VS 2015.

On my VS 2015 machine, however, the fresh NuGet 3 installation rendered a NuGet.config which did not have the v2 source in it. Generally, nothing surprises me with NuGet these days, there seems to be little pattern to its behaviour.

**Comment by gregoks** [comment]
Yeah perhaps..well as long as it works now, I can forgive Nuget for all their funny states :)
