### ISSUE TITLE
Use the same engine as VisualStudio 2015 Update 1 Interactive Window

### ISSUE THREAD

**Issue by regisbsb** [scriptcs/scriptcs#1122]
With the https://github.com/dotnet/roslyn/wiki/Interactive-Window release it will be a good idea to update the project to use the same library or event the same "csi" executable but with the nice additions like the package instalation. Or maybe contribute to the "csi"?

Cheers.

**Comment by khellang** [comment]
We have updated the bits a long time ago, with #1064. It's just not been released yet.

**Comment by khellang** [comment]
> with the nice additions like the package instalation

What does this mean? AFAIK, csi doesn't support package installtion? scriptcs has had support for package installation a long time.

**Comment by glennblock** [comment]
As we understand it, csi is planning to add package support. As to the
library, csi relies on the Roslyn scripting API as does scriptcs. We aren't
using the latest bits yet, but we will be.

**Comment by glennblock** [comment]
Package management is a host responsibility, hence it each host like csi,
Roslyn interactive, scriptcs etc is responsible to provide their own.

**Comment by adamralph** [comment]
We won't upgrade to the latest Roslyn bits purely for the sake of it.

When there is a compelling reason to upgrade, such as "to support X" or "fix Y", we'll do it, and we will have issues raised representing those reasons.

**Comment by thoemmi** [comment]
> We have updated the bits a long time ago, with #1064. It's just not been released yet.

The bug was fixed more than two month ago. Do you know when the next release will be published? Or are there any pre-release packages at MyGet (I couldn't find any feed though)?

**Comment by khellang** [comment]
> Or are there any pre-release packages at MyGet (I couldn't find any feed though)?

https://myget.org/gallery/scriptcsnightly :smile:

**Comment by thoemmi** [comment]
Thanks @khellang :+1:

**Comment by adamralph** [comment]
@thoemmi at the moment, the upgrade to Roslyn packages 1.0.0 rc2 is only scheduled to be part of scriptcs 1.0 which is going to have considerable changes and probably won't be released for some time.

We may consider backporting the upgrade to a 0.x version in the meantime. It just depends on finding the time to do it.

**Comment by glennblock** [comment]
We've device to get the rc2 Roslyn bits out there sooner, as in now :-)
