### ISSUE TITLE
Need a way to specify binding redirects in C# Interactive

### ISSUE THREAD

**Issue by eiriktsarpalis** [scriptcs/scriptcs#1124]
I'm facing this issue in C# Interactive, as bundled with VS 2015 Update 1. Not sure whether it is appropriate to post in the scriptcs repo.

When trying to load [FsPickler.CSharp](https://www.nuget.org/packages/FsPickler.CSharp/) from C# Interactive:
```csharp
#r "../../packages/FSharp.Core/lib/net40/FSharp.Core.dll"
#r "../../packages/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll"
#r "../../packages/FsPickler/lib/net45/FsPickler.dll"
#r "../../packages/FsPickler.Json/lib/net45/FsPickler.Json.dll"
#r "../../packages/FsPickler.CSharp/lib/net45/FsPickler.CSharp.dll"

var serializer = Nessos.CsPickler.CsPickler.CreateJsonSerializer();
```
I get the following error:
```
System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Nessos.CsPickler.JsonSerializer.Create(Boolean indent, Boolean omitHeader)
   at Nessos.CsPickler.CsPickler.CreateJsonSerializer(Boolean indent, Boolean omitHeader)
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```
This happens because I'm referencing FSharp.Core 4.4.0.0, whereas FsPickler.CSharp has been compiled against FSharp.Core 4.3.0.0. I can make the problem go away by either
  1. Stop using FSharp.Core 4.4 and roll back to 4.3 or
  2. Add an explicit binding redirect to FSharp.Core 4.4 in `InteractiveHost.exe.config` at the Visual Studio installation folder.

The problem is that solution (1) might be impossible depending on what type of dependencies I need to load for my session and solution (2) is simply wrong, enforcing a redirect policy that really depends on the type of application I'm working on in the current session.

So I was wondering whether there might be an easier way to dynamically specify binding redirects from a user perspective. Coming from an F# background, my expectation was that adding an explicit reference to an FSharp.Core at the top of my script would also introduce an implicit binding redirect to that particular assembly version. Thoughts?

**Comment by khellang** [comment]
"C# Interactive, as bundled with VS 2015 Update 1" has nothing to do with scriptcs.

scriptcs has dynamic "binding redirects" at runtime, so it picks the latest version when you reference an NuGet package.

**Comment by eiriktsarpalis** [comment]
My mistake. I thought that the codebases were related.

**Comment by khellang** [comment]
@eiriktsarpalis there is some overlap. We're using the Roslyn scripting APIs, but this problem is host related. csi.exe, interactive window and scriptcs are 3 different hosts :smile:
