### ISSUE TITLE
CI build fails because paths are too long

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#1127]
I guess something must have changed on the build agents (and you've gotta love Windows).

E.g.

http://teamcity.codebetter.com/viewLog.html?tab=buildLog&buildTypeId=Scriptcs_CI&buildId=204147

> [01:14:25][ScriptCs.Tests.Acceptance.dll] ScriptCs.Tests.Acceptance.Packages.PackageContainsAFrameworkAssemblyReference() [01.01.02] When I install a package which contains a framework assembly reference (1s)
> [01:14:26]
[ScriptCs.Tests.Acceptance.Packages.PackageContainsAFrameworkAssemblyReference() [01.01.02] When I install a package which contains a framework assembly reference] ScriptCs.Tests.Acceptance.Support.ScriptCsException : scriptcs.exe exited with code 1. The output was: Installing packages...
> ERROR: Error installing package. [PathTooLongException] The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

**Comment by adamralph** [comment]
I guess we've no choice but too shorten the scenario names somehow so that the working folders for the acceptance tests have a shorter path.

**Comment by glennblock** [comment]
If that works let's do it

**Comment by adamralph** [comment]
I think this probably may have gone away. Perhaps the codebetter guys shortened the working dir paths.

The current test failures are genuine and were introduced with the merge of #1134.

**Comment by adamralph** [comment]
Woot! All (mergeable) pull requests are :green_heart: 

![image](https://cloud.githubusercontent.com/assets/677704/13404462/f7d81094-df19-11e5-9995-5ed031cfe2d5.png)

I worked around the problem by restricting our builds to `JetBrains-dotnet-agent02` only. (Only 'JetBrains-dotnet-agent01' seems to have the too-long path problem.)
