### ISSUE TITLE
Just compile script code without executing it

### ISSUE THREAD

**Issue by vladislav-karamfilov** [scriptcs/scriptcs#1128]
I couldn't find a method in the public API or a command-line option that can be used to just compile the script code without executing it. Is it possible to add such method/option?

**Comment by glennblock** [comment]
Thanks for the suggestion. It would be nice to have, though it would probably be non-trivial to do it right. We're planning a major refactoring of scriptcs soon, so we should probably hold off for now.

If you are hosing scriptcs, one thing you could do is to put the code that you want to execute in a function, and then return from the script a lambda which invokes that function. The code will be compiled, and the caller can then invoke that lambda whenever they need to.

**Comment by glennblock** [comment]
For example, the code below returns a delegate to a Log function which is compiled in the script. If this script is invoked from our executor, the caller will get a reference to Log which can they invoke. 

```csharp
public void Log(string message) {
	Console.WriteLine(message);
}

Action<string> log = m => Log(m);
log
```

**Comment by vladislav-karamfilov** [comment]
That's an interesting solution. Thanks for the quick answer. :)
The problem is that I wanted to use the "-cache" command-line option functionality to store the compiled DLL (without executing it) and then execute the file with the default `scriptcs <path-to-file>` command. Something like `scriptcs <path-to-file> -cache -c` (-c == compile-only) and then execute `scriptcs <path-to-file> -cache` which will find the file in .scriptcs-cache folder and execute it.

**Comment by glennblock** [comment]
I see.

Well how about a simple pattern like this. It uses a custom script arg to indicate whether to just compile or execute. Works right from the command line.

```csharp
//start.csx

//only execute if 'c' was not passed as the first arg
if (Env.ScriptArgs.FirstOrDefault() != "c")
{
	Console.WriteLine("I am cached");
}
```

Now running like this will compile it.

```
PS C:\src\cache> scriptcs start.csx -cache `-- c
```

And then if you run it without the c param, it will execute

```
PS C:\src\cache> scriptcs cached.csx -cache
I am cached
```

**Comment by vladislav-karamfilov** [comment]
Hmm, I think this should do the trick. Thank you very much! :smile:

**Comment by glennblock** [comment]
Thinking about this more....

If you wanted you could write a custom [module](https://github.com/scriptcs/scriptcs/wiki/Modules) that replaces our FilePreProcessor and wraps all the code in the csx within an if-block like this. Then if the module is installed, it will give the behavior that you want. Writing the module would not be that hard to do. The module could be published on NuGet so others could install it. Happy to advise on how you could do that if you want to try it.

**Comment by glennblock** [comment]
Glad to help!

**Comment by glennblock** [comment]
Out of curiosity, have you found that the compilation / startup is taking too long? Did you profile and see that you got a significant benefit using the cached version?

**Comment by vladislav-karamfilov** [comment]
Yes! The cached version of a simple script with only `Console.WriteLine(Console.ReadLine())` executes 2-3 times faster than the in-memory one. It takes average of ~1247 ms when I use in-memory execution and ~457 ms when I use caching. I really like the `-cache` option. :)

**Comment by glennblock** [comment]
Great to hear! Hopefully we'll have it xPlat in the future.

**Comment by glennblock** [comment]
What are you using it for btw? (If you don't mind sharing)

**Comment by vladislav-karamfilov** [comment]
I am trying to integrate execution of C# scripts in a system that executes user code in a sandbox environment and compares the output from it to an expected one. It's name is [Open Judge System](https://github.com/NikolayIT/OpenJudgeSystem) and it's used for online algorithm competitions. Code execution is time limited and I'm trying to maximize the speed of the scriptcs code execution so it's comparable to the other execution types (C#, C++, Java, NodeJS, PHP). Unfortunately even with the `-cache` option 450 ms for this code is too much compared to other execution types (C# - 17 ms, Java - 23 ms, NodeJS - 149 ms)... Is there some other performance optimizations in scriptcs I could use? :)

**Comment by adamralph** [comment]
@glennblock why is this marked as `breaking-api`?

**Comment by glennblock** [comment]
Because it would likely be a breaking change to incorporate it. I am guessing you want me to remove it though as this is not a PR.

**Comment by glennblock** [comment]
@vladislav-karamfilov Very cool. 

What kind of code is executing? Is it relying on any 3rd party packages, or just pure C# code.

**Comment by vladislav-karamfilov** [comment]
Pure C# with the only exception of the [PowerCollections](https://powercollections.codeplex.com/) library.

**Comment by glennblock** [comment]
Gotcha.

Well one thing you could do is use #r to load the PowerCollections library and give it the path, rather than installing as a package.

If you want to have the maximum control of what loads, I'd consider self-hosting.

**Comment by glennblock** [comment]
One explicit goal for our re-arch will be to be very intentional about performance.

**Comment by vladislav-karamfilov** [comment]
I see. I look forward to playing with the new version when it's out. :) Thank you very much for the help and advices!
BTW, I really like the idea of creating a module for the compile-only functionality I need and publishing it in NuGet. As soon as I'm back on this project these days, I'll try writing it. :+1: Thanks again for the great help! :smile:

**Comment by glennblock** [comment]
@vladislav-karamfilov great! Feel free to reach out if you need advice on authoring the module.

"Thanks again for the great help! "

Sure, you are more than welcome. Thanks for using scriptcs!

**Comment by adamralph** [comment]
@vladislav-karamfilov that's great to hear. If there's no objection, I suggest closing this as a 'question' and we'll make improved start up time a general goal of our re-write for version 1.0.

BTW @glennblock - `breaking-api` is fine on issues, but we can discuss that offline.

**Comment by glennblock** [comment]
@adamralph this is more than startup time though. It is a request for the ability to pre-compile a script without executing it, so it is a feature.

**Comment by vladislav-karamfilov** [comment]
@adamralph, no objection. Just want to suggest implementing built-in compile-only command-line option too. :)

**Comment by glennblock** [comment]
@vladislav-karamfilov :+1:

**Comment by adamralph** [comment]
@vladislav-karamfilov if the start up time was sufficient, would you even use the compile only option?

**Comment by glennblock** [comment]
@adamralph I can still see benefit, especially if we could get to a point where the compile only version needed far less dependencies / footprint to execute.

**Comment by vladislav-karamfilov** [comment]
@adamralph I would use the option combined with `-cache` option which improves the performance.

**Comment by glennblock** [comment]
@adamralph imagine a build step which pre-compiles and then the DLL is deployed somewhere. This is a lot of hand waviness of course.

**Comment by glennblock** [comment]
@adamralph if the compilation / pre-processing was un-noticeable it would be less useful, however unless we are going to remove pre-processing altogether, I have my doubts.

**Comment by adamralph** [comment]
I think we're doing a good job of exploring this. So far, these considerations have been mentioned:

* Performance
* Dependencies
* Footprint

Performance I think we should leave for now since, as mentioned above, the v1 re-architecture could have a huge effect. I'd rather only spend time on solving a performance problem only when it is confirmed to exist and to what extent.

@glennblock you mentioned "less dependencies/footprint" can you expand on that?

**Comment by glennblock** [comment]
@adamralph agreed that we should not be focusing on perf now, we should address it in the rewrite.

As to less dependencies/footprint, this was the idea that I could pre-compile a dll and then somehow deploy that without requiring scriptcs or Roslyn present. It would require other 3rd party dependencies / packages obviously. As I said...a lot of hand waviness in this statement.

**Comment by adamralph** [comment]
@glennblock it seems like an exe would be more natural than a dll, since a script has an entry and exit point, equivalent to a `Program.Main()`.

**Comment by glennblock** [comment]
Yes an exe, or even a standard launcher exe which is bin-deployable that
can generically launch the dll. Either could work.

**Comment by vladislav-karamfilov** [comment]
Hi, guys! I started implementing `ScriptCs.CompileOnlyOption` module but I can't debug it... I tried the method described in the [documentation](https://github.com/scriptcs/scriptcs/wiki/Modules) but it doesn't work... I tried debugging the sample module `helloworld` like described in the wiki but it doesn't load... I tried debugging the module with executing an external process from Visual Studio but it doesn't work... Didn't find any information about it in StackOverflow too... Can you please help me debug a scriptcs module with Visual Studio?

**Comment by vladislav-karamfilov** [comment]
I found [this topic](https://groups.google.com/forum/?fromgroups#!topic/scriptcs/Na62jzC8k9I) and saw that loading modules from `bin` folder is no longer supported. I made my VS project output folder to be the `scriptcs` main folder and now I'm able to debug my module. It would be great if the wiki is updated accordingly. :)

**Comment by vladislav-karamfilov** [comment]
Hi, again! I implemented my module and put it here on Github: [ScriptCs.CompileOnlyOption](https://github.com/vladislav-karamfilov/scriptcs-compile-only-option)! :) I would be very grateful if you take a fast look at it. :)

**Comment by glennblock** [comment]
@vladislav-karamfilov thanks. I'll update the wiki, good catch.

Nice job on getting the module done. I'll take a look and send you feedback if/any tonight.

**Comment by vladislav-karamfilov** [comment]
Great! Any feedback is welcome. :) 

As soon as you approve the module I'll make a NuGet package and upload it on [nuget.com](https://www.nuget.org/).

I was wondering do you have a place where you list scriptcs modules from the community and, if you like ScriptCs.CompileOnlyOption, would you add a link to the repo and the nuget package? :)

**Comment by filipw** [comment]
@vladislav-karamfilov  thanks a lot! I added your module to the scriptcs WIKI - https://github.com/scriptcs/scriptcs/wiki/Modules-master-list#scriptcscompileonlyoption

**Comment by vladislav-karamfilov** [comment]
Thank you! 😺
