### ISSUE TITLE
scriptcs -script "VALUE" does not accept path with spaces

### ISSUE THREAD

**Issue by wjdavis5** [scriptcs/scriptcs#1132]
The following command fails to locate the correct .csx:

```
PS D:\scriptcsrunner> scriptcs -script 'C:\Users\William Davis\Downloads\vscode-scriptcs-runner-master\vscode-scriptcs-runner-master\testscript.csx'
```
Also fails:

```
PS D:\scriptcsrunner> scriptcs -script "C:\Users\William Davis\Downloads\vscode-scriptcs-runner-master\vscode-scriptcs-runner-master\testscript.csx"
```

Works fine:

```
PS D:\scriptcsrunner> scriptcs -script 'D:\vscode-scriptcs-runner-master\testscript.csx'
```

![image](https://cloud.githubusercontent.com/assets/2580575/12822284/62072f3e-cb35-11e5-9e95-7e129073378a.png)

**Comment by khellang** [comment]
What if you don't pass `-script`, just the path?

**Comment by filipw** [comment]
the space is the problem, ugh

**Comment by khellang** [comment]
I don't think we do any tokenizing ourselves, we rely only on the .NET `string[] args`, which should pass in a single string if it's quoted. I see you're using PowerShell there, this leads me to believe that PoSH is doing some string magic before passing the args to the exe. Can you verify that the same scenarios fail with CMD?

**Comment by wjdavis5** [comment]
Same behavior in CMD, and also removing -script

![image](https://cloud.githubusercontent.com/assets/2580575/12824313/9d747938-cb3e-11e5-8257-f8bdf8cdd904.png)

![image](https://cloud.githubusercontent.com/assets/2580575/12824335/b079f670-cb3e-11e5-933f-b0695008e082.png)

**Comment by wjdavis5** [comment]
This appears to work fine when built from dev.

**Comment by filipw** [comment]
I don't think anything changed in argument handling between dev and master to be honest though; I can't recall anything being added

**Comment by wjdavis5** [comment]
Retested on another fresh machine - recorded steps to recreate, please let me know if you'd like me to grab something (log wise). May not even be worth it considering it works in the dev branch.

[https://youtu.be/4BzTKAJOJuw](video)

**Comment by TAGC** [comment]
I've just started using scriptcs (`brew install scriptcs`) and this is an issue for me. I'm on macOS High Sierra and it's being used by [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) in VS Code:

```
[Running] scriptcs "/Users/me/Documents/VS Code/experiment/temp.cs"
Unexpected argument: Code/experiment/temp.cs

[Done] exited with code=1 in 0.685 seconds
```

**Comment by chinm3** [comment]
@TAGC Yes, I am still having this issue. Anyone fixed it yet?
