### ISSUE TITLE
ScriptCs Unexpectedly Clutters the Current Directory with Temporary Files

### ISSUE THREAD

**Issue by hypersw** [scriptcs/scriptcs#1136]
I'm running `scriptcs` to execute a simple isolated script, giving a full path to its file.
If the current directory (which is actually unrelated to the script, just a random cwd) contains certain directories or files, like `bin` (full list in `FileSystemMigrator::.ctor`), it gets cluttered with some sudden files and directories related to scriptcs operations.

I believe this might be useful in certain scenarios, but when running a simple isolated helper script or REPL these are totally unexpected consequences. 
The main negative points:
- Unexpected modification of the directory when just a simple execution of an independent script were intended.
- The directory gets a dirty status with the source control (and you don't want to modify the ignore list if that were just a helper script not related to the repository).
- The `bin` folder might be large, in which case the startup time of the script is also degraded.

I believe there should be a mode for noninvasive execution of simple scripts, otherwise it gets a tightly coupled semantic rather than being a general-purpose scripting engine.

**Comment by filipw** [comment]
You are absolutely right, I think at this point we can change the migrator to opt-in only.
It was well intended, but I can see how it can create a mess.

**Comment by filipw** [comment]
This would be a breaking change for the EXE but at this point most folks should be off `packages.config`. Not to mention it's future is in the air anyway 👹

**Comment by filipw** [comment]
Related to #1279
