### ISSUE TITLE
Custom Printing

### ISSUE THREAD

**Issue by gregoryyoung** [scriptcs/scriptcs#1137]
I wanted to send a PR to support custom printing of repl return values (an example can be seen in F# with fsi.AddPrinter). I found the place in scriptcs code to add this functionality pretty easily. I have not been able to figure out however is how I can call internal scriptcs code (to handle the mapping) from a script. Ideally what I would want to be able to do is something like:

``` code
repl.AddCustomPrinter<MyType>(x => String.Format("My Stuff:\t{0,8:c}", x.Baz)
```

What I am mainly missing is how to be able to expose say the repl object there back to the repl instance.

Cheers,

Greg

**Comment by adamralph** [comment]
hi @gregoryyoung, sounds good.

I guess the key thing is to add a `Repl`property to https://github.com/scriptcs/scriptcs/blob/dbebf1e8bf61f33d49aebbd432ece69453eb69f7/src/ScriptCs.Contracts/IScriptHost.cs and take it from there. It's questionable whether we would want this property on the general host which is also used for running script file, but I guess it can't really hurt. 

@scriptcs/core thoughts?
