### ISSUE TITLE
How to capture the console output of a running script when hosting?

### ISSUE THREAD

**Issue by jmcginty** [scriptcs/scriptcs#1138]
Following the examples for hosting, I have created an application to run custom scripts. The logging only captures output from the host application though. 
I would like to allow script writers to use code like so:

```c#
    Console.WriteLine("information");
    Console.Error.WriteLine("This is an Error");
```

Which would then end up in the log as information / errors.
Any idea how to achieve this?

**Comment by glennblock** [comment]
One idea, you could overwrite the output stream on the console object
(SetOut) in your hosting layer and then pipe that wherever.

**Comment by glennblock** [comment]
Also you should look at the Logger script pack. It provides a simple
logging facility that might work.

**Comment by jmcginty** [comment]
Thanks for the quick reply Glenn - I tried redirecting the output from the console in the hosting layer, but that did not capture the output from the script layer.
I looked at the logger script pack, but from what I can tell it also just outputs to the console in the script layer. I thought there could be a way to pass a reference to the logger in the hosting layer _into_ the script layer using a script pack, but how to do this is beyond me.

**Comment by glennblock** [comment]
Aaaah got it.

Yes you can do that. With a custom IScriptHost registered you can expose
the logger into the scripting env as an ambient property / method.

Alternative though ugly is a static method.

**Comment by jmcginty** [comment]
Could you give me a small example of this? I don't really know where to start .

**Comment by glennblock** [comment]
I could probably in about 12 hours. I am doing touristy stuff in downtown
Delhi today and I have crappy mobile Internet :-)

@scriptcs-core can you point him in the direction?

**Comment by glennblock** [comment]
You can try starting with this wiki page:
https://github.com/scriptcs/scriptcs/wiki/Modules

I believe it mentions / links to a post on replacing the script host.

You would then need a way to get the script host access to the logger so it
can expose it. One way is to create a
custom script host factory which creates the host and which passes the
logger into the host constructor.

If no one responds, I will get you something later.

Glenn

**Comment by jmcginty** [comment]
I couldn't find the link/mention of replacing the script host in the Modules wiki. It mentionss you *can* introduce a custom script host, but not really how. 
Could you possibly shoot me the example for a custom script host factory you mentioned?

Here's a link to my bare bones script host https://github.com/jmcginty/ScriptRunner for reference

James

**Comment by glennblock** [comment]
@jmcginty you are right, I could find anything either :-). I'll describe what you need to do below. 

* You should create a custom host which derives from [`ScriptHost`](https://github.com/scriptcs/scriptcs/blob/dev/src/ScriptCs.Core/ScriptHost.cs). Add whatever properties or methods you'd like to this object. They will project into the scripting environment as ambient members similar to `Env`.
* Then create a custom [`ScriptHostFactory`](https://github.com/scriptcs/scriptcs/blob/dev/src/ScriptCs.Core/ScriptHostFactory.cs) which returns your host. 
* Register this factory using the [`ScriptCsServicesBuilder.ScriptHostFactory<T>()`](https://github.com/scriptcs/scriptcs/blob/dev/src/ScriptCs.Hosting/ServiceOverrides.cs#L27) method where T is your factory.

That should be it. Within your scripts / the REPL (if you are hosting the REPL) you should be able to access the new members.

**Comment by glennblock** [comment]
I just added my comment below to the Hosting wiki page [here] (https://github.com/scriptcs/scriptcs/wiki/Hosting#creating-a-custom-script-host), which is the more appropriate place than in the modules page.

**Comment by jmcginty** [comment]
Thanks @glennblock I will try this in the morning.

**Comment by jmcginty** [comment]
THANKS GLENN, IT WORKS !

**Comment by glennblock** [comment]
EXCELLENT! Please blog on it :-)
