### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by awb99** [scriptcs/scriptcs#1157]
CommonScriptEngine.cs(22,13): error CS0012: The type 'System.ValueType' is defined in an assembly that is not reference
I am trying to compile scriptcs on a brand new Windows7 machine with .net 4.5.2 
via build.cmd. The machine is x64.

This is the error that I get:

```
You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50
a3a'. [C:\Users\test\Desktop\scriptcs-dev\src\ScriptCs.Engine.Roslyn\ScriptCs.Engine.Roslyn.csproj]
CommonScriptEngine.cs(22,13): error CS0012: The type 'System.Collections.Generic.IList`1<T0>' is defined in an assembly
 that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, Public
KeyToken=b03f5f7f11d50a3a'. [C:\Users\test\Desktop\scriptcs-dev\src\ScriptCs.Engine.Roslyn\ScriptCs.Engine.Rosly
n.csproj]
CommonScriptEngine.cs(22,13): error CS0012: The type 'System.Collections.Generic.ICollection`1<T0>' is defined in an as

```

When I add References to the RoslynEngine Project then it works. Strange, that they are not included out of the box... The references that are missing are:
1. System.RUntime
2. System.Text.Encoding
3. System.Threadng.Tasks
4. System.IO

**Comment by khellang** [comment]
You can see the list of default references [here](https://github.com/scriptcs/scriptcs/blob/a252cd4bb7977989afa2583b57582534dc91a68f/src/ScriptCs.Core/ScriptExecutor.cs#L17-L24). These are the default references of a standard .NET console application. It might be time to look at this list and maybe include a couple more?

**Comment by khellang** [comment]
You can also see (just below the references) the included namespaces. Among these are `System.Threading.Tasks`, `System.IO` and `System.Text`. I'm not so sure we want to include `System.Text.Encoding`, but we might want to take a look at `System.Runtime`.

**Comment by awb99** [comment]
@khellang I beieve this list of default references is relevant when one runs a SCRIPT. I  my case I just try to compile the solution that I downloaded from github. I believe the project file is somehow bad. Why would it not compile without me adding references to the project.

**Comment by khellang** [comment]
Are you using scriptcs to compile a project? How does that even work? :confused:

**Comment by awb99** [comment]
@khellang  I am trying to build the complete solution of scriptcs.  I ave downloaded the zip file here from github;and then when I clicked on build.cmd, then it got lots of errors. I then opened the solution, and found out, that there are some errros related to missing assembly references.  So the version how it is on github today cannot compile!

**Comment by filipw** [comment]
This should be resolved by now. The minimum .NET framework version needed to compile scriptcs is .NET 4.6.1. ValueTuple will be restored from nuget.
