### ISSUE TITLE
scriptcs -Install Newtonsoft.Json fails trying to resolve 'Microsoft.CSharp'

### ISSUE THREAD

**Issue by david-driscoll** [scriptcs/scriptcs#1169]
I'm working on some scripts for work, where powershell is all but banned, and wanted to work with ScriptCs instead (or at least have parts be ScriptCs).

I'm running into an issue where `scriptcs -Install` fails to run correctly.

```
λ C:\test\.svm\bin\tools\scriptcs.exe -Install Newtonsoft.Json
Installing packages...
ERROR: Error installing package. [InvalidOperationException] Unable to resolve dependency 'Microsoft.CSharp (≥ 4.0.1)'.
ERROR: Package installation failed. [AggregateException] One or more errors occurred.
```

It appears the resolver is trying to fetch the dependencies for the `netstandard` version of Newtonsoft.Json.

---
More details....  So I did a little more digging.

* I also get a failure with `scriptcs -install Microsoft.AspNet.Mvc`.

If I add an empty `NuGet.config` to my working directory... then `scriptcs -install Microsoft.AspNet.Mvc` works and installs `v5.2.3` as expected.

The install error for Newtonsoft.Json changes to...
```
λ c:\test\.svm\bin\tools\scriptcs -Install Newtonsoft.Json
Installing packages...
ERROR: Error installing package. [InvalidOperationException] 'Microsoft.CSharp' already has a dependency defined for 'System.Dynamic.Runtime'.
ERROR: Package installation failed. [AggregateException] One or more errors occurred.
```

---
Finally if I navigate to `C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\Newtonsoft.Json` and remove the folder for `9.0.1` (if it exists).  Then the install works as expected!

---
I feel like this might be more of a nuget issue, and less of an issue of ScriptCs.  If I find a related issue I'll reference it here as well.

**Comment by glennblock** [comment]
It looks like this is only related to the latest JSON.NET package. It works with 8.0.3. I debugged and the exception is being thrown in NuGet.Core.

This will work

```
-install newtonsoft.json -p 8.0.3
```

See this #1171 for more.

**Comment by glennblock** [comment]
Closing as this appears to be related to Nuget.Core

**Comment by ABajpaiAmphora** [comment]
Install nuget package manager for Visual studio 2013 from below link:
https://www.visualstudiogallery.msdn.microsoft.com/4ec1526c-4a8c-4a84-b702-b21a8f5293ca

and restart the Visual Studio 2013.

For me this worked.
