### ISSUE TITLE
Passing command line arguments to your .csx file

### ISSUE THREAD

**Issue by dotfelixb** [scriptcs/scriptcs#1175]
what is the best way to pass command line arguments to your .csx file in scriptcs, when you run it with your script, like

scriptcs lexer.csx test.lang 

where lexer.csx is my script and test.lang is the file am passing to my lexer.csx script through command line as an argument

sample code:

```csharp
// do the readling of file content
void OpenFile(string path)
{
    Console.WriteLine(path);
}

// entry point
void Run()
{
    // get the immediate argument after script
    // scriptcs lexer.csx test.lang
    var filename = Environment.GetCommandLineArgs()[2];
    OpenFile(filename);
}


// script main
Run();
```

**Comment by khellang** [comment]
You can access the arguments passed to the script with `Env.ScriptArgs`. This is a `string[]` :smile:

**Comment by khellang** [comment]
Also, if you're having trouble getting the arguments passed to the script, you can try separating the scriptcs.exe arguments and the script arguments with `--`, like this: `scriptcs lexer.csx -- test.lang`

**Comment by dotfelixb** [comment]
got it, thankx

[https://github.com/scriptcs/scriptcs/wiki/Writing-a-script#passing-arguments-to-a-script](url)
