### ISSUE TITLE
NETStandard.Library error while installing a specific NuGet package library

### ISSUE THREAD

**Issue by justinyoo** [scriptcs/scriptcs#1176]
Hi, all.

I got a weird error message when installing `FluentAssertions` using the command:

```
scriptcs -install FluentAssertions
```

The error message says:

> ERROR: Error installing package. [InvalidOperationException] 'NETStandard.Library' already has a dependency defined for 'Microsoft.NETCore.Platforms'.
> ERROR: Package installation failed. [AggregateException] One or more errors occurred.

I suspect `FluentAssertions` uses .NET Starndard Library since 4.5+. If I install `FluentAssertions` of version 3.5 (far older version), it's fine.

How can we sort this out?

**Comment by glennblock** [comment]
Can you try cloning our latest source using master? It contains a more recent NuGet.Core which supports .NET Standard.

I meant to push this live, but did not yet due to travis CI errors. They don't appear to be related to the code, so I may just push anyway.

**Comment by justinyoo** [comment]
@glennblock Here's what I've done.

1. Cloned the repo, checked out to the `master` branch and build it using `build.cmd`.
1. Uninstalled my existing scriptcs 0.16.1 through the command `svm remove 0.16.1`.
1. Ran the executable `artifacts/Release/bin/scriptcs.exe -install FluentAssertions`

However, it still shows the same error message.

**Comment by richardgavel** [comment]
I get the same error. I have also tried building my own copy of scriptcs from master and using it to the same effect though I was trying to install NEST.

**Comment by enzian** [comment]
@glennblock actually it's only merge to `dev` for now! I built from `dev` and it works fine! Big thumbs up!

**Comment by glennblock** [comment]
Sure. I thought it had been fixed as it relies on the newer nuget.core
