### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by ygoe** [scriptcs/scriptcs#1181]
Check out the latest version in the dev or master branch, or the v0.16.1 tag, and run build.cmd. It will generate lots of warnings (yellow colour) and one failed test (red colour).

How should I build this?

Running on Windows 7 x64 with Visual Studio 2015.

Actually I don't need to build it myself. Is there a binary download available somewhere? I don't like these custom package managers, I prefer a solid Setup.exe or at least an archive with the program files so I can build my own setup from it and deploy it on dev and build machines.

**Comment by khellang** [comment]
If you just want to download the binaries, without installing [chocolatey](https://chocolatey.org/), you can just pull the nupkg directly from https://chocolatey.org/packages/ScriptCs (or use this [direct link](https://chocolatey.org/api/v2/package/ScriptCs/0.16.1)).

A nupkg is just a glorified zip-file. Just rename the package to `ScriptCs.0.16.1.zip`, pop it open and extract the `tools` folder. That should contain the binaried needed.

And yes, we should definitely get some binaries uploaded the the release section here in this repo.

**Comment by glennblock** [comment]
@ygoe please try again. A bunch of the warnings were StyleCop related. I disabled StyleCop for our tests and for some class files that were "imported" externally like liblog. You shouldn't be getting any errors anymore.
