### ISSUE TITLE
Using scriptcs with .net core

### ISSUE THREAD

**Issue by asyschikov** [scriptcs/scriptcs#1183]
Is it possible?

**Comment by glennblock** [comment]
Not currently. It's a big refactoring to get scriptcs to work on .NET core. We determined it would basically take a rewrite. As there is a better scripting story in .NET core, we've de-prioritized supporting it (at least for now).

**Comment by ygoe** [comment]
@glennblock Please tell me more about that “better scripting story in .NET core”.

**Comment by glennblock** [comment]
https://github.com/filipw/dotnet-script

**Comment by israelpgjm** [comment]
> @glennblock Please tell me more about that “better scripting story in .NET core”.

**Comment by israelpgjm** [comment]
> Not currently. It's a big refactoring to get scriptcs to work on .NET core. We determined it would basically take a rewrite. As there is a better scripting story in .NET core, we've de-prioritized supporting it (at least for now).
