### ISSUE TITLE
using static directive fails to compile

### ISSUE THREAD

**Issue by do-adams** [scriptcs/scriptcs#1184]
Whenever I try to write a script with the `using static` directive (C# 6) I get the following error: 

> ERROR: Script compilation failed. [CompilationErrorException] error CS0246: The type or namespace name 'static System' could not be found (are you missing a using directive or an assembly reference?)

Here's the simple code I am trying to get to work with scriptcs:

```
using static System.Console;

WriteLine("Hello World!");
```

**Comment by filipw** [comment]
This is a rather nasty bug. It's caused by how scriptcs tries to extract the directives from the script prior to running it. Definitely needs fixing.
