### ISSUE TITLE
Comments in the head of a script file must not throw the error "Encountered directive after the start of code"

### ISSUE THREAD

**Issue by Zuriel-C** [scriptcs/scriptcs#1185]
The Visual Studio 2015 C# Interactive (CSI.exe) and the Roslyn assemblies don't generate this error thus it seems that it is generated by scriptcs.

Typically the copyright information is in the header of the file as comments. It seams more natural to have those above the #r and #load directives.

**Comment by glennblock** [comment]
Hi @Zuriel-C, we only allow Roslyn / scriptcs directives at the beginning of the file. I believe we initially did this because it was in the Roslyn specification.

**Comment by glennblock** [comment]
nevermind, I see the bug you are reporting here is related to comments at the beginning of the file. Can you share an example of the code that is blowing up?

**Comment by Zuriel-C** [comment]
Example:

File: dependency.csx
`
/* Copyright 2016 - Tempuri.org */
#r "System.Web"

Console.WriteLine("from dependency");
`

File: main.csx
`
// Copyright 2016
#load "dependency.csx"

Console.WriteLine("from main");
`

**Steps:**

- Run scriptcs.exe "main.csx"
Actual result: Throws an exception

- Run "C:\Program Files (x86)\MSBuild\14.0\Bin\csi.exe" "main.csx"
Actual result: The script runs as expected.

- In VS 2015 C# interactive, #load "main.csx" 
Actual result: The script runs as expected.

scriptcs version 0.16

**Comment by glennblock** [comment]
Ok, the issue here is not the comment, it is the #r after the comment. Currently as I said we require that directives are before any code. Supporting comments at the beginning makes sense, but there's a bunch of complexity in making this work right for multiline. Single line comments would be relatively easy.

**Comment by glennblock** [comment]
What if we supported initially 

```
// Line1
// Line1
```

in the header, would that work for you?

**Comment by Zuriel-C** [comment]
That would work. Thanks.

**Comment by glennblock** [comment]
@Zuriel-C fix is in. This should now work for example.

```csharp
// This a comment
// This is another comment

#load foo.csx
```
