### ISSUE TITLE
Execute a method in loose script and return value

### ISSUE THREAD

**Issue by rbmanian75** [scriptcs/scriptcs#1186]
Hi,

I have a code with a method test accepting two arguments and return a value.  for example

i have the loose script
public static class main
{
pubic static string test( string p1, string p2){
return p1+p2;
}
}

I would like to load the code and execute the method main.test("A","B") and get the result by using scriptcs hosting. How do i do it?

Thanks

**Comment by glennblock** [comment]
Hey

Take a look at this example and see if it works for you:
https://github.com/glennblock/scriptcs-hosting-example

**Comment by rbmanian75** [comment]
Thank you, i looked at the same and replaced the loose script with
 @"public static class Test {  public static string Method1() { return ""test"";} }  return Test.Method1(); ";
and it throws up error

Could you please help me in solving the issue.

**Comment by glennblock** [comment]
Change the last line to just Test.Method1(); with no return. If you are
trying to return a value, you do not use return, you just put the value and
a ;

**Comment by rbmanian75** [comment]
Hi,

Thank you for the quick reply. It works. But assume i have this code
class Dynamic
{
    public static int Main (int x,int y)
    { 
        return x+y;
    }
}

using executor i want to call something Dynamic.Main(1,2). How do i achieve that. How to i  pass parameters to executor.

Thanks

**Comment by rbmanian75** [comment]
Hi,
Any way to do this?...

Thanks

**Comment by glennblock** [comment]
Apologies for the delay. Where does that static class live, is it defined within your script?

**Comment by glennblock** [comment]
@rbmanian75 yes. If you look at the [Execute Script](https://github.com/scriptcs/scriptcs/blob/dev/src/ScriptCs.Core/ScriptExecutor.cs#L188) method, you can pass args to the script when it is invoked. These args are then available off of the `Env` object.

**Comment by rbmanian75** [comment]
Thank you for the reply. I was able to identify that. But the parameters are limited to string type. It would be convenient if we can pass other data types also as a parameter. I see that from the documentation we can do lots of customization. But i am not getting an idea how to achieve this

**Comment by glennblock** [comment]
There are a few possibilities.

One way is to create a static method / member that the caller and the
script can both access. This works because they are in the same process.

A second way is to return a delegate as the return value of the script. So
you example you return a Func<string,string,string> which the caller then
invokes. The func params can be any type, not just string, even dynamic. I
have used this approach multiple times.

The third way is the hardest. You create a custom IScriptHost that exposes
properties which can be set by the caller. This example shows how to do
that: https://github.com/scriptcs-contrib/scriptcs-ambient

For your use case I would probably go with option 2 and have the script
return a func.

On Wed, Dec 28, 2016 at 11:42 PM rbmanian75 <notifications@github.com>
wrote:

Thank you for the reply. I was able to identify that. But the parameters
are limited to string type. It would be convenient if we can pass other
data types also as a parameter. I see that from the documentation we can do
lots of customization. But i am not getting an idea how to achieve this











> On Dec 29, 2016, at 3:54 AM, Glenn Block <notifications@github.com> wrote:


>


> @rbmanian75 yes. If you look at the Execute Script method, you can pass
args to the script when it is invoked. These args are then available off of
the Env object.


>


> —


> You are receiving this because you were mentioned.


> Reply to this email directly, view it on GitHub, or mute the thread.


>






—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/scriptcs/scriptcs/issues/1186#issuecomment-269593377>,
or mute the thread

**Comment by rbmanian75** [comment]
Thank you for the quick reply. The second method is working fine.

Thanks a lot.

**Comment by glennblock** [comment]
Great!

**Comment by glennblock** [comment]
@rbmanian75 would be great for you to blog on the solution

**Comment by pwhe23** [comment]
This worked for me where I want my script to return a Dictionary<string, string> to the caller:

HelloWorld.csx:
```
public static Dictionary<string, string> Main() {
    var dict = new Dictionary<string, string>();
    dict["Key"] = "value";
    return dict;
}

Main();
```

Program.cs:
```
var result = executor.Execute("HelloWorld.csx");
var dict = (Dictionary<string, string>)result.ReturnValue;
```

**Comment by pwhe23** [comment]
I also just realized the last line's value is returned if there is **no** semicolon, duh.

```
var console = new ScriptConsole();
var scriptExecutor = new ScriptServicesBuilder(console, new ColoredConsoleLogProvider(LogLevel.Info, console))
    .ScriptEngine<CSharpScriptEngine>().Build().Executor;

scriptExecutor.Initialize(Enumerable.Empty<string>(), Enumerable.Empty<IScriptPack>());

var script = @"""returned string no semicolon""";
var result = scriptExecutor.ExecuteScript(script);
Console.WriteLine(result.ReturnValue);
```

**Comment by pwhe23** [comment]
I was looking over the Ambient example Glenn sent and came up with this as a simple solution to pass data back and forth to a hosted script using Dynamic. You can use an ExpandoObject or custom object with the properties you want to share. This was the simplest thing I could come up with for my needs.

```
public class GlobalObj
{
    public string Name { get; set; }
    public string Message { get; set; }
}

void Main()
{
    //var globals = new GlobalObj();
    dynamic globals = new ExpandoObject();
    globals.Name = "Foo";

    var console = new ScriptConsole();
    var builder = new ScriptServicesBuilder(console, new ColoredConsoleLogProvider(LogLevel.Info, console))
        .SetOverride<IScriptHostFactory, DynamicScriptHostFactory>(new DynamicScriptHostFactory(globals))
        .ScriptEngine<CSharpScriptEngine>().Build();
    
    var executor = builder.Executor;
    executor.Initialize(Enumerable.Empty<string>(), Enumerable.Empty<IScriptPack>());

    var result = executor.ExecuteScript(@"Console.WriteLine(1234); Globals.Message = ""Hello "" + Globals.Name; Globals.Message");
    Console.WriteLine(globals.Message);
    Console.WriteLine(result.ReturnValue);
}

public class DynamicScriptHost : ScriptHost
{
    public DynamicScriptHost(IScriptPackManager scriptPackManager, ScriptEnvironment environment) : base(scriptPackManager, environment) {}
    public dynamic Globals { get; set; }
}

public class DynamicScriptHostFactory : IScriptHostFactory
{
    private DynamicScriptHost _scriptHost;
    
    public DynamicScriptHostFactory(object globals = null)
    {
        Globals = globals ?? new ExpandoObject();
    }
    
    public dynamic Globals { get; private set; }
    
    public IScriptHost CreateScriptHost(IScriptPackManager scriptPackManager, string[] scriptArgs)
    {
        _scriptHost = new DynamicScriptHost(scriptPackManager, new ScriptEnvironment(scriptArgs, null, null));
        _scriptHost.Globals = Globals;
        return _scriptHost;
    }
}
```

**Comment by glennblock** [comment]
👍
