### ISSUE TITLE
Named argument error

### ISSUE THREAD

**Issue by abhi18av** [scriptcs/scriptcs#1188]
Hi @scriptcs team

I've run into an error with `scriptcs` while trying it out with the [vscode-code-runner](https://github.com/formulahendry/vscode-code-runner/issues/46#issuecomment-269945102) and this issue seems to be related with an older version of scriptcs as mentioned in [scriptcs-sublime](https://github.com/scriptcs/scriptcs-sublime/issues/26)

But I installed the latest version on macOS, `brew install scriptcs` and I currently have `scriptcs 0.16.1` installed. Any idea what might be causing the error?

Happy New Year 😄

**Comment by xx5ko** [comment]
Same problem as well.

**Comment by glennblock** [comment]
@filipw ?

**Comment by glennblock** [comment]
Most likely this is due to the runner needing to get updated. I'd file a bug in that repo.

**Comment by xx5ko** [comment]
personally, this error does show me after fresh, clean and for first time installation

**Comment by TAGC** [comment]
Same happens for me with 0.17.1 via VS Code on High Sierra.

**Comment by TAGC** [comment]
Same problem occurs if I try to run the command outside of VS Code in a normal terminal. Seems to be an issue with scriptcs, not the code runner.

**Comment by ShiWill** [comment]
I have same problem with 0.17.1 via Visual Studio Code on High Sierra 10.13.2

**Comment by formher** [comment]
why this issue is closed? it doesn't seem to have solution

**Comment by formher** [comment]
same here. why is this issue closed? it doesn't seem to have resolution yet.

**Comment by filipw** [comment]
it is closed because the issue is already fixed on the dev branch and will be released with the next release 🙂

**Comment by formher** [comment]
great! and when is the next release planned may I ask?

**Comment by filipw** [comment]
unfortunately, turns out the problem is still possible to get, so I will reopen the issue.
The workaround is the following: 

 - instead of doing `mono scriptcs.exe /path/to/foo.csx`do `mono scriptcs.exe -script /path/to/foo.csx`

**Comment by shisaq** [comment]
The issue stands still...
@filipw I tried your solution, it worked as expected.
The only preparation is to compile the `*.cs` file by using `$ csc *.cs` first, which will work out a `*.exe` file to let `mono` use it.

**Comment by filipw** [comment]
I am working on a fix right now. The issue is in the argument parsing library we have, which doesn't work well on Mono. We'll move to a different one as part of 1.0.

**Comment by filipw** [comment]
this will be addressed in https://github.com/scriptcs/scriptcs/pull/1289

**Comment by Jps2310** [comment]
I downloaded the newest version of scriptcs and get the same problem which should be fixed already. I'm working with vscode-code-runner

**Comment by filipw** [comment]
that version with a fix has not been officially released

**Comment by Jps2310** [comment]
When will it be released?

**Comment by sballay8734** [comment]
What are our other options here?  I'm a beginner and this has been driving me crazy.  I can't get the scripts to run. "Unexpected named argument:"  What IDE are you guys using in the meantime?

**Comment by jeffmadison** [comment]
> What are our other options here? I'm a beginner and this has been driving me crazy. I can't get the scripts to run. "Unexpected named argument:" What IDE are you guys using in the meantime?

For VS Code with the Code Runner extension: open your user settings, switch to JSON mode, then add this:
```
"code-runner.executorMap": {
      "csharp": "scriptcs -script" // temp workaround until next release. https://github.com/scriptcs/scriptcs/issues/1188#issuecomment-410728346
}
```

**Comment by khaled-zbidat** [comment]
> > What are our other options here? I'm a beginner and this has been driving me crazy. I can't get the scripts to run. "Unexpected named argument:" What IDE are you guys using in the meantime?
> 
> For VS Code with the Code Runner extension: open your user settings, switch to JSON mode, then add this:
> 
> ```
> "code-runner.executorMap": {
>       "csharp": "scriptcs -script" // temp workaround until next release. https://github.com/scriptcs/scriptcs/issues/1188#issuecomment-410728346
> }
> ```
 hi how can i add to the code runner those lines what is the way ??

**Comment by AntonioCoppe** [comment]
Stil having the same issue mentioned above, where can i find the user setting where to add:

"code-runner.executorMap": { "csharp": "scriptcs -script" }

Thank you

**Comment by zengzx0427** [comment]
> Stil having the same issue mentioned above, where can i find the user setting where to add:
> 
> "code-runner.executorMap": { "csharp": "scriptcs -script" }
> 
> Thank you

just resolved the problem.
go to settings -> extensions -> run code configuration 
then find the ExecutorMap -> edit in json.
find the line  "csharp": "scriptcs" ,  replace it with "csharp": "scriptcs -script"  
I recommend just // the original line instead delete

**Comment by Umair-max** [comment]
for begginners : click on extention icon in vs code and select code runner , beside of uninstall button click on setting icon -> extention setting -> find code runner : executor map then click on edit in setting.json . In line 27 replace this  "csharp": "scriptcs" by this "csharp": "scriptcs -script"

**Comment by BuPo69** [comment]
> for begginners : click on extention icon in vs code and select code runner , beside of uninstall button click on setting icon -> extention setting -> find code runner : executor map then click on edit in setting.json . In line 27 replace this "csharp": "scriptcs" by this "csharp": "scriptcs -script"

I've tried to do that and scriptics runs but i dont get any output in terminal when tryna print "hello world"
