### ISSUE TITLE
Update to Roslyn 2.0.0

### ISSUE THREAD

**Issue by filipw** [scriptcs/scriptcs#1194]
We are currently at Roslyn `1.0.0-rc`, however, there is already `1.3.2` stable and `2.0.0-rc2`.
This issue is a suggestion to update to latest Roslyn.

It should not be a lot of work (the major work was to move from old Roslyn to `1.0.0-rc`)

### Pros

 - C# 7 support
 - cross platform (we will be able to delete the Mono engine)
 - new extensibility points in Roslyn which we could leverage (i.e. customizable `#load`)
 - better assembly loading experience (for example built-in GAC support which will allow us to delete more code)
 - a bunch of Roslyn-level bugs addressed

### Cons
 - it will require a bump in scriptcs to `net461` rather than the current `net45`. However, `net45` is not supported by Microsoft since January 2016 anyway

**Comment by filipw** [comment]
cc @glennblock

**Comment by glennblock** [comment]
So this only requires updating to .NET 4.6? My only worry there is how much
it will block in terms of existing users. I wonder if we could support both.

What do we gain in moving?

**Comment by filipw** [comment]
I think the benefits that I listed speak for themselves - the upgrade should be a no brainer imho.
As far as using scriptcs with .NET 4.5 - I think that's like regular software releases, who wants it, will keep using an older version, who wants the new features will need to upgrade .NET version (which, by the way, was pushed by Windows Updates anyway)

**Comment by glennblock** [comment]
Mono works on 27 platforms. I think we still should keep it for those that want it. 

OK, fair. How much work is it to upgrade our code, is it a drop in replacement?

**Comment by filipw** [comment]
> Mono works on 27 platforms. I think we still should keep it for those that want it.

I think you are misunderstanding. When we upgrade to latest Roslyn scriptcs will still work on mono because Roslyn itself does work on mono 4.6. 

If anything, we will have a *better* experience because instead of a hand-rolled engine we have now, which is severely limited, we will offer full Roslyn experience.

**Comment by glennblock** [comment]
OK sounds good.

So let's do this, let's get 0.17.0 out without this, then in release with pure Roslyn as 1.0! 

Thoughts?

**Comment by glennblock** [comment]
We are past due on 1.0 release. We're just shy of 4 years in, I think it is time and this would be a good fit.

**Comment by filipw** [comment]
yes, great. Roslyn is currently at `2.0.0-rc2` which we can already stuff into our dev branch, and as soon as 2.0.0 RTM is there, this could be the basis for scriptcs 1.0.

**Comment by glennblock** [comment]
OK. So can you commit to do the work of updating the Roslyn bits and we'll ship that as 0.18.0 ?

**Comment by filipw** [comment]
yes - sounds like a plan

**Comment by glennblock** [comment]
👍
