### ISSUE TITLE
Is there a way to change the colors for output?

### ISSUE THREAD

**Issue by StingyJack** [scriptcs/scriptcs#1198]
I really cant read the errors without selecting and pasting into a text editor, and even the selection colors are hard. 

![image](https://cloud.githubusercontent.com/assets/15381181/22003835/bfdc584a-dc24-11e6-8381-22a5a94df554.png)

**Comment by glennblock** [comment]
Currently we fix it to red and dark-red depending on the level. I'll look
at what we can do here.

**Comment by glennblock** [comment]
OK, I looked into this. Changing to "red". Should work better...see below.

![screen shot 2017-01-21 at 12 06 06 am](https://cloud.githubusercontent.com/assets/141124/22173093/7a25b322-df6d-11e6-9fee-e0e89f72b0dc.png)
