### ISSUE TITLE
Documentation Tracking Progress on Linux and Anticipation of PWD support

### ISSUE THREAD

**Issue by BryanWilhite** [scriptcs/scriptcs#1207]
I wrote a scriptcs Blog post, “[First Encounter with scriptcs => @scriptcsnet](http://songhayblog.azurewebsites.net/#/entry/first-encounter-with-scriptcs-scriptcsnet)” from my [markdown source](https://github.com/BryanWilhite/Blog/blob/master/2017-01/First%20Encounter%20with%20scriptcs.md) here on GitHub. [Glenn Block re-tweeted it](https://twitter.com/BryanWilhite/status/824769599606489089) via @scriptcsnet a few hours ago.

This Blog post brings up a couple of issues:

- PWD (present working directory) support
- interpretation-time errors on mono/Linux

To deal with the PWD issue this was my workaround (Glenn does not like it):

    public static string GetScriptFolder()
    {
        var pathToScript = Environment
            .GetCommandLineArgs()
            .FirstOrDefault(i => i.EndsWith(".csx"));
        if(pathToScript == null)
            throw new Exception("GetScriptFolder(): The expected command-line argument is not here.");

        pathToScript = Path.GetFullPath(pathToScript);
        var folder = Path.GetDirectoryName(pathToScript);
        Console.WriteLine("GetScriptFolder(): script folder: {0}", folder);

        return folder;
    }

**Comment by glennblock** [comment]
Not saying I don't like it. It is a great work around barring anything in
the box!

My concern with this approach is if the script is a relative path and if
the CWD has been changed prior to that code running, then it will not have
the right path.

I have implemented a baked in solution in the latest in the dev branch. The
env object exposes ScriptPath and LoadedScripts properties that have the
full paths for the main and child scripts. This solution stores the path
name at the time the file is actually read and before any code is executed
so it is not dependent on the CWD at runtime.

Make sense?

**Comment by glennblock** [comment]
Looking at this more I misunderstood your request. I thought you want to
get the path of the scripts. It sounds like you are asking for just the
working directory? Is that right?

**Comment by filipw** [comment]
> interpretation-time errors on mono/Linux

this is due to scriptcs using a custom lexer on Mono which has a bunch of limitations. 

This will go away when https://github.com/scriptcs/scriptcs/issues/1194 is implemented as it will ring the Linux/OS X experience right on par with Windows.

**Comment by BryanWilhite** [comment]
...all of this is great news guys! ...yes @glennblock I want the PowerShell equivalent of `$PSScriptRoot ` in fact I wrote [another post](http://songhayblog.azurewebsites.net/#/entry/you-can-t-effectively-replace-cmd-scripts-with-ps1-scripts-without-these-key-powershell-ingredients) about the five things I need to use PowerShell instead of CMD---these five things may apply to scriptcs...

**Comment by glennblock** [comment]
Great. You'll be able to get it now with ScriptPath but then it has both the folder and the name. If you prefer I can add a new property which also has the directory, maybe ScriptDirectory?

**Comment by glennblock** [comment]
This PR adds ScriptPath and LoadedScripts. ScriptPath is the main script and LoadedScripts are any that were `#load` ed. But let me know if you want the other property. It is very easy to add.

**Comment by glennblock** [comment]
https://github.com/scriptcs/scriptcs/pull/1192

**Comment by BryanWilhite** [comment]
@glennblock I would not need it; I would resort to `System.IO.Path.GetDirectoryName()` first. I would not design “helper” classes that ‘hide’ the .NET Framework from the developer. My bias is to do the minimal possible and encourage the developer to learn more details about .NET.

For over a decade, I have been curating/developing [a collection of Extension Methods](https://github.com/BryanWilhite/SonghayCore/tree/master/SonghayCore/Extensions) for the “core” of .NET. I’ve had to obsolete a few things (since .NET 1.1) as Microsoft releases new “core” functionality.

The reason why I am bringing this up is because I am thinking of your [`FileSystem`](https://github.com/scriptcs/scriptcs/blob/dev/src/ScriptCs.Core/FileSystem.cs) class which _feels_ like a wrapper for `System.IO` and `System.Environment` to me.

**Comment by glennblock** [comment]
Got it.

Yes, our Filesystem call is a wapper that serves multiple purposes. 1. It
makes scriptcs itself easier to unit test. 2. It allows scriptcs to operate
off of alternate file systems, we have had folks implement their own.
Testability was the main driver.

**Comment by BryanWilhite** [comment]
@glennblock  I now understand your intent... and this kind of slides me back into the need for [extension methods in scriptcs](https://github.com/dotnet/roslyn/issues/141).

**Comment by glennblock** [comment]
That's currently a Roslyn limitation as you cannot add extension methods to
an inner class or at least couldn't. Still I wouldn't look to extension
methods to address what we created IFilesystem for.
