### ISSUE TITLE
[InvalidOperationException] for Markdig and MoreLinq packages (version 0.17.0)

### ISSUE THREAD

**Issue by BryanWilhite** [scriptcs/scriptcs#1213]
Upgraded to new released via `ChocolateyGUI` and ran `scriptcs -install Newtonsoft.Json` this process completed without errors but installed several packages that were not expected (not dependencies of `Newtonsoft.Json`. Then I ran `scriptcs -install Markdig` and `scriptcs -install MoreLinq` both threw `Unable to find package` errors (see screenshot attached).
![clipboard01](https://cloud.githubusercontent.com/assets/5226627/22955169/8e8a26a2-f2cf-11e6-867d-38417b9b220d.png)

**Comment by glennblock** [comment]
Thanks for reporting. Looking into this now. Glad Errors are now at least more readable this release. :-)

**Comment by glennblock** [comment]
It looks like these are .NET Core / .NET Standard assemblies. For some reason it is pulling down a ton of packages. I am guessing it is due to us updating to the latest NuGet.Core and that the way we were calling NuGet before now is no longer correct. This is just a guess at this point, but I can see it is pulling the kitchen sink of packages.

**Comment by glennblock** [comment]
Interesting, same is happening with 0.16.1 (previous release)

**Comment by glennblock** [comment]
@scriptcs/core any ideas on this one? It looks like this behavior was in our previous release as well.

**Comment by glennblock** [comment]
OK I've debugged it now, it happens within the NuGet.Core APIs so there must be a way to tell it to install for .NET 4.5 and not get all the .NET Standard packages.

**Comment by glennblock** [comment]
OK making progress......

**Comment by glennblock** [comment]
@BryanWilhite can you test out my 1213 branch (pr #1215). I believe I fixed it.

**Comment by BryanWilhite** [comment]
@glennblock this is my first time checking out a pr branch. I have tried these so far:

```
$ git clone https://github.com/scriptcs/scriptcs.git -b glennblock:1215
$ git clone https://github.com/scriptcs/scriptcs.git -b pr/1215

```

**Comment by glennblock** [comment]
You can just clone my fork

```
git clone https://github.com/glennblock/scriptcs.git
git checkout 1215
```

After you check out, you should see it checking out files. If you don't then do these 2 commands.

```
git pull origin 1215
```

Then you should be able to run the build script in `scriptcs/build.cmd`

**Comment by BryanWilhite** [comment]
I ran `scriptcs -install MoreLinq` and `scriptcs -install Markdig` directly in the Debug folder and got package-not-found exceptions
![songhay14v-2017-02-16-21-16-02](https://cloud.githubusercontent.com/assets/5226627/23053342/8e6c9dfc-f48d-11e6-927c-d07ec82c4ee0.png)

**Comment by glennblock** [comment]
Can you try running outside of the debug folder and point to scriptcs via
relative path?

Also you did 'git checkout 1213' ?

**Comment by glennblock** [comment]
Fixed in 0.17.1

**Comment by BryanWilhite** [comment]
yup I downloaded 1213... will try a run outside the `\Debug` folder...

**Comment by BryanWilhite** [comment]
I am sure this is fixed in the next release but for 1213 repeated the same test from my default PowerShell folder; got same results...
![clipboard01](https://cloud.githubusercontent.com/assets/5226627/23081302/05590ef2-f509-11e6-84e6-8a8abccd4772.png)

**Comment by glennblock** [comment]
At the risk of sounding back, I think this is something with your
configuration or nuget cache or something. I had @jrusbatch just install
fresh our dev branch and he got the same result that I had / everything
worked.

**Comment by BryanWilhite** [comment]
In your “defense” I will offer that scriptcs is already installed on the systems I used to test. So these environments were not “clean.” However, from my point of view, your code should be able to defend itself from these conditions and provide meaningful error messages to demonstrate this awesome power, this level of control. I am well aware how my point of view is received in this context.

**Comment by glennblock** [comment]
@BryanWilhite I just tested with our now back online chocolatey nightly build, and it works. I am going to assume it is safe to release 0.17.1.

**Comment by glennblock** [comment]
If you want to test with that command try `choco install scriptcs -pre -source https://www.myget.org/F/scriptcsnightly/ --force`

**Comment by BryanWilhite** [comment]
This issue is not closed. As I mentioned before, I know showing the simplicity of reporting the following will be useless. Another more “trustworthy” report from an actual person will have to corroborate with what I am seeing in the screenshot below. I have done nothing here but try to help. I am done.
![clipboard01](https://cloud.githubusercontent.com/assets/5226627/23284825/779394c8-f9e2-11e6-9cd0-3905268452aa.png)

**Comment by glennblock** [comment]
Do you have NuGet.exe? Can you try using NuGet directly to install the
package? This error generally means NuGet cannot find the package. Do you
know how your package sources are configured?

**Comment by glennblock** [comment]
Maybe we can pair up via Google Hangouts and diagnose together?

**Comment by BryanWilhite** [comment]
I do not have the time to go further into this investigation. Again, I would design the code to fail with meaningful error messages (based on an intimate understanding of NuGet) to prevent all of this manual testing. To dismiss this as not possible would be typical yet unusual for a developer of your caliber. Someone has defined what an **expected** NuGet environment is and someone has or will design code and build automated tests based on this formal definition—and then someone will express this formal knowledge in scriptcs.

**Comment by glennblock** [comment]
Bryan, I have tried to repro your issue unsuccessfully as have others on
the team. The error that we are returning "Unable to find package" IS from
the NuGet API we call into. I realize you are frustrated, but without a
repro there's not much we can do.

**Comment by glennblock** [comment]
Btw you can run scriptcs with -loglevel debug to see more detailed log
messages.

**Comment by BryanWilhite** [comment]
@glennblock `-loglevel debug` is useless for this issue. The frustration is centered around framing this issue as _my_ issue. This is _your_ issue. I repeated the same test as the previous one today on a different machine and got the same results: errors. The fact that these errors are coming from NuGet is not my concern. Either NuGet will improve or scriptcs will improve---or both.

Speaking of NuGet, I continued my manual testing (for the last time until there is a new release) and actually _respected_ what you wrote to me and tested with NuGet directly. I got the expected (positive) results when I ran NuGet directly. The first question I ask myself is why does scriptcs not produce the same verbose-but-helpful output?
![clipboard01](https://cloud.githubusercontent.com/assets/5226627/23290756/26a3bdb0-fa08-11e6-8890-d62f8ff2d9b1.png)

**Comment by glennblock** [comment]
I am saying your issue in the sense that you are the one who ran into this
and reported. I am not saying there is not an issue with scriptcs, just
that we have not been able to repro it. Forgive me if it sounded like I was
implying YOU caused this. I do want to solve it, which is why I offered to
pair up with you.

I tried manually to reproduce it several times, as did others on my team.
My guess is there is something different configuration wise which is
resulting in this.

As to logging more detail for NuGet that is something we can look into and
it is a great suggestion and would be helpful. It is not that we
deliberately left it out ;-), there is probably a way to have the NuGet
APIs surface the verbose details that we are just not capturing. This
wasn't raised as a concern before, otherwise we would have addressed it.

One last request, can you run the command "nuget sources list" and send me
the results?

Thanks again!
Glenn

**Comment by glennblock** [comment]
Ok @BryanWilhite looking at your output, I have an idea what MAY be happening and I can repro. scriptcs relies on NuGet V2, but when NuGet V3 is installed, you do not get the V2 feed setup. You can read about that in this write up [here](https://github.com/scriptcs/scriptcs/wiki/NuGet-v3), which I was unaware of.

If I edit my `%APPDATA%\NuGet\NuGet.config`, I see that the V2 source is there under package sources:

```
  <packageSources>
    <add key="local" value="C:\src\scriptcs\artifacts\Release" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
```

If I remove the 3rd entry for V2, and then run `scriptcs -install` I will get the same error that you have for any package.

i.e.

```
PS C:\test> scriptcs -install Markdig
Installing packages...
ERROR: Error installing package. [InvalidOperationException] Unable to find package 'Markdig'.
ERROR: Package installation failed. [AggregateException] One or more errors occurred.
PS C:\test> scriptcs -install Newtonsoft.Json
Installing packages...
ERROR: Error installing package. [InvalidOperationException] Unable to find package 'Newtonsoft.Json'.
ERROR: Package installation failed. [AggregateException] One or more errors occurred.
PS C:\test>
```

So the solution I believe for now would be for you to edit your %APPDATA%\NuGet.Config and then add this one line under package sources.

```
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
```

Then it should work. Can you verify this?

**Comment by glennblock** [comment]
You can also just use this command from the nuget cli:

```
nuget sources add -Name "nuget.org v2" -Source "https://www.nuget.org/api/v2/"
```

**Comment by BryanWilhite** [comment]
This makes sense. I will check this.

**Comment by BryanWilhite** [comment]
@glennblock, I used the CLI command above and it is working as expected (see screenshot). Well done! Now, scriptcs can _define_ its expected NuGet 2.x environment and verify that it is actually in place by opening a text file (`%APPDATA%\NuGet\NuGet.Config`) and inspecting it or you can just forget it and succumb to the pressures and demands of daily life. I consider this issue closed because you can refer to the workaround in this thread as well.

![clipboard01](https://cloud.githubusercontent.com/assets/5226627/23343502/77788f5c-fc21-11e6-963a-e530c9bac186.png)

**Comment by glennblock** [comment]
Great! I may add in logic to automatically register v2 if it is not there,
so we can mitigate this until we move to v3.

Thanks for your patience. Glad we figured it out, your screenshot helped.
Had I seen the list of package sources it probably would have been more
immediately obvious.

**Comment by glennblock** [comment]
You can also inspect using the cli: "nuget sources list"
