### ISSUE TITLE
Consider supporting configuration files

### ISSUE THREAD

**Issue by jrusbatch** [scriptcs/scriptcs#123]
Should configuration files, as recognized by Visual Studio, be supported in a scriptcs environment?

**Comment by boneyexperion** [comment]
hi Glenn, 
I have added an application in scriptcs and added  some references to assemblies 
which have the version v2.0.50727. So while running the scriptcs file it returns as Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime.Setting attribute useLegacyV2RuntimeActivationPolicy="true" in app.config may resolve the issue in asp.net web application. but in scriptcs its not working. further searching reveals that above  attribbute useLegacyV2RuntimeActivationPolicy="true" should be added as scriptcs.exe.config. I have an application file named FMUpgrade.csx and how can we reference this  scriptcs.exe.config in the  FMUpgrade.csx  file.scriptcs docs doesn't say much about scriptcs.exe.config.
Thanks 
Boney
