### ISSUE TITLE
build fails on windows 10 using the cmd terminal program

### ISSUE THREAD

**Issue by dcu-sharepoint** [scriptcs/scriptcs#1237]
as usual; these beautiful programs fail in one way or another when used with windows 10 or any other windows OS, only the mac rules.... hurray let's kill windows..... yay....

![script-error](https://cloud.githubusercontent.com/assets/22737071/25572524/ea5d7342-2e09-11e7-8465-d405cd1b4d36.png)

**Comment by glennblock** [comment]
@dcu-sharepoint it should work on Windows, though if you are using our latest bits, you will need to upgrade to the latest MSBuild. Is this the dev branch?

**Comment by glennblock** [comment]
I use Windows 10 to develop scriptcs so it definitely works :-)

**Comment by dcu-sharepoint** [comment]
@glennblock Thanks Glen; I just downloaded the bits from this site and then it failed when running the build.cmd script. where do I get the MSBUILD from? and how? with nuget? or NPM?

what I don't get is why should a "hellow world" program with a new version? it just don't make sense...

Thanks again...

**Comment by glennblock** [comment]
You can get the latest MSBuild from here:
https://www.microsoft.com/en-us/download/details.aspx?id=48159

The reason this is needed is because if you use our dev branch, we have
upgraded to a newer Roslyn and version of .NET.

The quickest path for you to try scriptcs is to just install from chocolatey
<https://chocolatey.org/packages/scriptcs> (assuming you've installed
chocolatey) or use svm <https://github.com/scriptcs-contrib/svm>.

If you want to build the source of our latest release, you can do that
building against the master branch (which won't require newer MSBuild).

**Comment by dcu-sharepoint** [comment]
@glennblock Thank Glenn; great and timely answer; I will work full time on this in the next couple of days. I really want this to work on my system, I think it will make it easy to personalize my terminal environments.

will post my results status; thanks again, great help.

**Comment by glennblock** [comment]
No problem, glad to help! Let us know how it goes.

One advantage of the newer release (which is currently in our dev branch)
is it has full symmetry code wise in terms of Mac, Linux and Windows. The
current release uses Mono's compiler (not Roslyn) for Mac/Linux and not
everything that works on Windows works the same and vice versa. Hopefully
we'll get this shipped soon.

**Comment by dcu-sharepoint** [comment]
@glennblock  I just downloaded the new msbuild.exe version and when I clicked on it, it was installed into my VS 2105 IDE. quick ?; why do I need chocolatey then; I installed it as well, do I need to use chocolatey to re-install the MSBuild over the VS-2015 install? confusing...

Anywho: thanks for your help. It's great you're there to help.

**Comment by glennblock** [comment]
Chocolatey is for installing apps. If you use chocolatey it will install
the binaries and you don't need to build source. SVM which I linked to is
similar. Both provide ways to install the binaries without having to build
anything.

You only need the latest msbuild installed if you want to build our source
that is in the dev branch.

**Comment by dcu-sharepoint** [comment]
Getting install errors with choco. I downloaded the MSbuild to my directory, navigated to my directory, run a term window with admin privs and BOOM FAILURE.

I navigated to my directory, run a PowerShell window with admin privs and BOOM FAILURE.

what am I doing wrong, the msbuild site just says "click the exe and it will be installed" I did just that and it installed it with VS. Do I need to install the msbuild with choco as well?

**Comment by glennblock** [comment]
No. MSBuild has nothing to do with chocolatey.

What chocolatey errors did you get?

**Comment by dcu-sharepoint** [comment]
![choco-error](https://cloud.githubusercontent.com/assets/22737071/25672008/05123266-3000-11e7-98a0-e9976b334ff7.png)

build errors
![scripting-error](https://cloud.githubusercontent.com/assets/22737071/25672036/1ad1b310-3000-11e7-9141-3a457971200d.png)

it has to be me; but the experience is NOT pleasant... and I really wanted to use this tool.

I installed the tool before and NEVER had any problems.....

**Comment by glennblock** [comment]
You should be installing scriptcs not msbuild.

choco install scriptcs

**Comment by dcu-sharepoint** [comment]
thanks; that worked; however, it forces you to run the command under the administrator and it saves/stores the scriptscs in administrators account have to run the scripts with privs if your want to use the system. I know it was installed before about two months ago and I didn't use choco then and run some examples and forgot about the tool until now. What I used to install I don't remember....

Anywho: the moral of the story: it did install with a bunch of warnings using the local sys admin and INSTALLED in the admin account and not in the non-priv user account I normally for dev.

@glennblock  Thank you for your help....

**Comment by dcu-sharepoint** [comment]
@glennblock; as per your instructions; the **scriptcs** is finally installed and running. Thanks again

**Comment by filipw** [comment]
This has been resolved
