### ISSUE TITLE
Building & Installing without Chocolatey

### ISSUE THREAD

**Issue by dmumladze** [scriptcs/scriptcs#1239]
Issue: 
NuGet.exe takes existing nuget.config from user's directory, which on my machine is v3, but scriptcs requires v2 so, I was able to add **nuget.config** to **\scriptcs\.nuget** folder similar to below and it works without Chocolatey. 

Justification: 
Our team cannot install Chocolatey locally, but would like to incorporate 'scriptcs' into our toolbox. Would you be able to accept a pull request with this change?

```
<?xml version="1.0" encoding="utf-8"?>
 <configuration>
  <solution>
   <add key="disableSourceControlIntegration" value="true" />
  </solution>
 <packageRestore>
  <add key="enabled" value="True" />
  <add key="automatic" value="True" />
 </packageRestore>
 <packageSources>
   <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
 </packageSources>
 <disabledPackageSources />
 <activePackageSource>
   <add key="Microsoft and .NET" value="https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/" />
 </activePackageSource>
</configuration>
```

**Comment by pldmgg** [comment]
Not sure if this would solve your issue, but you can technically install ScriptCs without installing the Chocolatey cmdline tools.  If you have Windows PowerShell version 5.1 or newer installed, you can use PowerShell's PackageManagement and PowerShellGet Modules to add the Chocolatey PackageProvider source (source is pretty much equivalent to the concept of a repository on Linux), and then you can do the following:

    PS C:\Users\pddomain> Install-PackageProvider "Chocolatey" -Scope CurrentUser -Force

    Name                           Version          Source           Summary
    ----                           -------          ------           -------
    chocolatey                     2.8.5.130        https://onege... Chocolatey...


    PS C:\Users\pddomain> Set-PackageSource -Name Chocolatey -Trusted

    Name                             ProviderName     IsTrusted  Location
    ----                             ------------     ---------  --------
    chocolatey                       Chocolatey       True       http://chocola...
    
    PS C:\Users\pddomain> Install-Package -Name ScriptCs -Source chocolatey

This installs ScriptCs to "C:\Chocolatey\lib\ScriptCs.0.17.1\tools".  Add that path to your system PATH (and your PowerShell $env:Path if you want to use scriptcs within a PowerShell session), and add the line about using NuGet v2 API to your nuget.config as you mentioned your post, and you should be good to go.

For versions of Windows PowerShell older than 5.1, you can use my Update-PackageManagement function to setup package management (installs PowerShellGet and PackageManagement Modules, and adds the Chocolatey PackageProvider source), and then simply run:

    PS C:\Users\pddomain> Install-Package -Name ScriptCs -Source chocolatey

Link to Update-Management function:

https://github.com/pldmgg/misc-powershell/blob/master/MyFunctions/Update-PackageManagement.ps1
