### ISSUE TITLE
ScriptCS includes "broken" version of Microsoft.Web.Xdt

### ISSUE THREAD

**Issue by Desarc** [scriptcs/scriptcs#1244]
I recently started using some functions from the [NuGet.Core](https://www.nuget.org/packages/NuGet.Core/) library in one of our scripts. I've previously noticed that `NuGet.Core` is already referenced by ScriptCS, but in order to resolve our own references I had to add it to the `scriptcs_packages.config` file anyway. `NuGet.Core` depends on [Microsoft.Web.Xdt](https://www.nuget.org/packages/Microsoft.Web.Xdt/), which is also included in ScriptCS.

Running this script on my own machine (Windows 10) works fine, but when i try to run it on one of our build agents (Windows Server 2012 R2), it throws the following error:

![scriptcs_microsoftwebxdt](https://user-images.githubusercontent.com/2356904/28110272-230f3862-66f2-11e7-95a5-2dcdcf905ba5.PNG)

Both machines run the same version of ScriptCS, `0.17.1`.

I searched around the web a bit for possible solutions, and came across this post:
http://www.damirscorner.com/blog/posts/20140502-StrongNameValidationFailedSecurityException.html

`Microsoft.Web.Xdt 2.1.0` has been unlisted from nuget.org, and replaced by `2.1.1`. Comparing the two dlls, `2.1.1` seems to actually be almost exactly the same as `2.1.0` (even the same file version), but the former is signed correctly.

Checking the dll included with ScriptCS with sn.exe yields the following result:
![scriptcs_snexe](https://user-images.githubusercontent.com/2356904/28110464-d406eb6a-66f2-11e7-8d4b-e9e146b66396.PNG)

...while the new (correct) version yields:
![snexe_xmltransform](https://user-images.githubusercontent.com/2356904/28110559-14216cca-66f3-11e7-97eb-88e891daee71.PNG)

I tried explicitly selecting version `2.1.1` of `Microsoft.Web.Xdt` by adding it to the `scriptcs_packages.config` file, but ScriptCS seems to ignore this and attempt to load the included version anyway.

Note that this didn't actually cause us any trouble on our build agents until we started referencing `NuGet.Core` in our scripts.

**Comment by andmos** [comment]
@filipw are you guys working after some sort of release cycle we can plan after? We use ScriptCS alongside Octopus Deploy and had to do some workarounds to fix this issue, and I would like to remove those workarounds as soon as possible 😄 a `0.17.2` would be welcome, but I understand if the cycle is different or you want to put in some more fixes. Cheers!

**Comment by filipw** [comment]
yeah needs to be done. I need to check what makes more sense, back-porting the fix as hotfix, or just releasing the whole `dev` (that was intended to be `1.0.0`). That one is overdue already so will happen soon.
