### ISSUE TITLE
Does Dot-net script replace scriptcs?

### ISSUE THREAD

**Issue by donnyv** [scriptcs/scriptcs#1256]
I know you guys are working on Dot-net script also. Is that a newer version of scriptcs using dotnet core or are you running both projects?

**Comment by filipw** [comment]
At the moment [dotnet-script](https://github.com/filipw/dotnet-script) is a .NET Core 2.0 script runner, and scriptcs is a desktop .NET / Mono script runner.
They will probably converge in the future as .NET SDK and .NET Standard matures, but at the moment, the gap between running scripting on .NET SDK (like `dotnet-script` does) and on full framework is wide enough that we need to maintain both solutions separately.
