### ISSUE TITLE
Basic Scenario in osX not working with full path cs file.

### ISSUE THREAD

**Issue by top2tech** [scriptcs/scriptcs#1264]
Same issue as https://github.com/scriptcs/scriptcs/issues/1188. As there is no place for me to reactivate the issue, so I opened a new one here.

Works well if cs file in current dicrectory:
   scriptcs  a.cs  

Error if using full path:
   scriptcs /Usesr/someUser/someDir/a.cs
Error message:
Unexpected named argument: Usesr/someUser/someDir/a.cs

**Comment by ben9992** [comment]
This issue tested by me.
scriptcs PathToCSX works fine.

**Comment by rmontoya12** [comment]
I'm also having this issue using scriptcs via brew. The -version logo displays as Version: 0.0.0.

**Comment by formher** [comment]
same here

**Comment by filipw** [comment]
This is fixed on the dev branch already, and will be part of 1.0.0 release
