### ISSUE TITLE
Update-Package -reinstall has failures

### ISSUE THREAD

**Issue by BlackFrog1** [scriptcs/scriptcs#1265]
Got the latest code and perform the following command in Package Manager Console:

> Update-Package -reinstall

The following error appears three (3) times:

> Failed to update binding redirects for src\ScriptCs.Engine.Roslyn\ScriptCs.Engine.Roslyn.csproj : Failed to load 'C:\GitHub\Scriptcs\src\ScriptCs.Engine.Roslyn\app.config', while updating binding redirects. Data at the root level is invalid. Line 20, position 1.

Reviewing the source, I found the issue:
![errant character](https://user-images.githubusercontent.com/550820/34538669-40a57da4-f09b-11e7-8001-29fbe5315bf9.png)

I have also included the output of the Package Manager Console.
[reinstall log.txt](https://github.com/scriptcs/scriptcs/files/1601630/reinstall.log.txt)

**Comment by jrusbatch** [comment]
Fixed by #1266.
