### ISSUE TITLE
Build Project has incorrect reference to xUnit Runner for MSBuild

### ISSUE THREAD

**Issue by BlackFrog1** [scriptcs/scriptcs#1268]
In the `Build.proj` it was change to use version 2.3.0 of xunit.runner.msbuild nuget package.  
https://github.com/scriptcs/scriptcs/blob/db30643aab32f77c4e6fb6544184468712dd83e0/build/Build.proj#L3

But the global nuget packages.config is only restoring version 2.2.0.
https://github.com/scriptcs/scriptcs/blob/0f888920190d1eb1a4d31db8240a8ba55aeb62ff/.nuget/packages.config#L4

Also, in version 2.3.0 and higher, the name of the dll was changed to include the framework version `xunit.runner.msbuild.net452.dll`  See xunit/xunit#1606

**Comment by BlackFrog1** [comment]
#1267 was submitted to correct this issue and few other things.

**Comment by filipw** [comment]
This was fixed in the recent batch of changes in the building process.
