### ISSUE TITLE
Project debug output path is different for one project

### ISSUE THREAD

**Issue by BlackFrog1** [scriptcs/scriptcs#1272]
I working on #1260 and I came across this. Is there a technical reason why the Roslyn Engine project debug output path is set differently than all the others?  All the projects have the proper project references, so the output from each will get copy to the correct output location during the build process.  

> **ScriptCs\ScriptCs.csproj:**
> &lt;OutputPath&gt;bin\\debug\\&lt;/OutputPath&gt;
> &lt;OutputPath&gt;bin\\Release\\&lt;/OutputPath&gt;
> 
> **ScriptCs.Contracts\ScriptCs.Contracts.csproj:**
> &lt;OutputPath&gt;bin\\Debug\\&lt;/OutputPath&gt;
> &lt;OutputPath&gt;bin\\Release\\&lt;/OutputPath&gt;
>    
> **ScriptCs.Core\ScriptCs.Core.csproj:**
> &lt;OutputPath&gt;bin\\Debug\\&lt;/OutputPath&gt;
> &lt;OutputPath&gt;bin\\Release\\&lt;/OutputPath&gt;
>    
> **ScriptCs.Engine.Roslyn\ScriptCs.Engine.Roslyn.csproj:**
> &lt;OutputPath&gt;..\\..\\..\\scriptcs\\src\\Scriptcs\\bin\\debug\\&lt;/OutputPath&gt;
> &lt;OutputPath&gt;bin\\Release\\&lt;/OutputPath&gt;
> 
> **ScriptCs.Hosting\ScriptCs.Hosting.csproj:**
> &lt;OutputPath&gt;bin\\Debug\\&lt;/OutputPath&gt;
> &lt;OutputPath&gt;bin\\Release\\&lt;/OutputPath&gt;

**Comment by filipw** [comment]
This was fixed with #1262
