### ISSUE TITLE
Cannot build with VS2015 / MSBuild 14

### ISSUE THREAD

**Issue by BlackFrog1** [scriptcs/scriptcs#1273]
Cannot compile with Visual Studio 2015 because of C# 7 language in  the dev branch.

![failed vs2015](https://user-images.githubusercontent.com/550820/34644883-7df761a8-f30d-11e7-9715-85cb6b962646.png)

https://github.com/scriptcs/scriptcs/blob/a8cf5777ddbdf820ed152360cbd8d80b8ada5705/src/ScriptCs.Contracts/ScriptCs.Contracts.csproj#L16

**Comment by damianh** [comment]
Use VS2017/MSBuild 15 instead.

**Comment by filipw** [comment]
closing per https://github.com/scriptcs/scriptcs/pull/1274#issuecomment-378733736
