### ISSUE TITLE
Documentation is 2+ years old

### ISSUE THREAD

**Issue by runxc1** [scriptcs/scriptcs#1292]
I recently had to rebuild my laptop and don't use scriptcs often but like to use it occasionally for prototyping and am trying to get it setup again so that I can debug a CSX file from VS Code and I don't follow the project too closely but all the examples in the Wiki are 2+ years old talking about how to set it up with Visual Studio 2015.   I am not seeing example of how to load a Nuget file except for at the site www.strathweb.com and it seems that perhaps that has changed.   The site scriptcs.net also seems to give a walk through that is even older and missing how to use it with VS Code.

**Comment by filipw** [comment]
Thanks a lot for the issue and it is definitely unfortunate that things aren't entirely up to date. We are working towards 1.0.0 release which will unify the Mono and Roslyn engines into one. There will be large revamp of documentation needed as part of that, which I started tracking in https://github.com/scriptcs/scriptcs/issues/1287

I would suggest to use that issue for any comments or concerns - or if you'd like to specifically include any topics or areas you feel like need covering. Thanks!
