### ISSUE TITLE
Errors trying to build on Manjaro Illyria

### ISSUE THREAD

**Issue by Miradden** [scriptcs/scriptcs#1301]
I have Mono and the dotnet-sdk, but when i try building using `./build.sh` i get this error

` 1) Building ScriptCs.sln failed with exitcode 1.
  2) : /home/mirad/scriptcs/src/ScriptCs/ScriptCs.csproj(0,0): /home/mirad/scriptcs/src/ScriptCs/ScriptCs.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
  3) : /home/mirad/scriptcs/src/ScriptCs.Contracts/ScriptCs.Contracts.csproj(0,0): /home/mirad/scriptcs/src/ScriptCs.Contracts/ScriptCs.Contracts.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
  4) : /home/mirad/scriptcs/test/ScriptCs.Tests/ScriptCs.Tests.csproj(0,0): /home/mirad/scriptcs/test/ScriptCs.Tests/ScriptCs.Tests.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
  5) : /home/mirad/scriptcs/src/ScriptCs.Core/ScriptCs.Core.csproj(0,0): /home/mirad/scriptcs/src/ScriptCs.Core/ScriptCs.Core.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
  6) : /home/mirad/scriptcs/test/ScriptCs.Core.Tests/ScriptCs.Core.Tests.csproj(0,0): /home/mirad/scriptcs/test/ScriptCs.Core.Tests/ScriptCs.Core.Tests.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
  7) : /home/mirad/scriptcs/test/ScriptCs.Engine.Roslyn.Tests/ScriptCs.Engine.Roslyn.Tests.csproj(0,0): /home/mirad/scriptcs/test/ScriptCs.Engine.Roslyn.Tests/ScriptCs.Engine.Roslyn.Tests.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
  8) : /home/mirad/scriptcs/src/ScriptCs.Hosting/ScriptCs.Hosting.csproj(0,0): /home/mirad/scriptcs/src/ScriptCs.Hosting/ScriptCs.Hosting.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
  9) : /home/mirad/scriptcs/test/ScriptCs.Hosting.Tests/ScriptCs.Hosting.Tests.csproj(0,0): /home/mirad/scriptcs/test/ScriptCs.Hosting.Tests/ScriptCs.Hosting.Tests.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
 10) : /home/mirad/scriptcs/src/ScriptCs.Engine.Roslyn/ScriptCs.Engine.Roslyn.csproj(0,0): /home/mirad/scriptcs/src/ScriptCs.Engine.Roslyn/ScriptCs.Engine.Roslyn.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
 11) : /home/mirad/scriptcs/test/ScriptCs.Tests.Acceptance/ScriptCs.Tests.Acceptance.csproj(0,0): /home/mirad/scriptcs/test/ScriptCs.Tests.Acceptance/ScriptCs.Tests.Acceptance.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format. `

how do i fix this? I tried what the error says to do but the link it provides is dead, so that causes more errors

**Comment by StiliyanKushev** [comment]
this thing is basically dead. This error is happening for a lot of time and no one has done anything. I suggest you use mono and mono develop for your needs

**Comment by filipw** [comment]
you need to have Mono > 5.18.1 installed for the build to work - sorry for your trouble.
