### ISSUE TITLE
Consider refactoring our arg design to use sub commands

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#175]
Per Adam

We should consider not just using flat args, but actually having sub commands similar to git.

https://github.com/adamabdelhamed/PowerArgs#advanced-example

**Comment by adamralph** [comment]
(From https://github.com/scriptcs/scriptcs/pull/868#issuecomment-68596167)

Current command line args:

### Commands
* run a script: implicit by presence of script name
* start REPL: implicit by absence of script name or `-repl` when other args are present (this is confusing but is addressed by https://github.com/scriptcs/scriptcs/issues/869)
* show help `-help`
* install package `-install`
* save packages.config file `-save`
* clean installed packages `-clean`
* show version `-version`

### Options
* drop into REPL after running script file `-repl`
* emit PDB symbols `-debug`
* assembly in memory or filesystem `-cache`
* log level `-loglevel`
* install package globally `-global`
* allow pre-release packages `-allowprerelease`
* watch script file for changes `-watch`
* module to load `-modules`

One thing to note is that if we want to maintain support for `scriptcs foo` to run a script named `foo.csx` then we would have to exclude certain script names from this behaviour, i.e. `help.csx`, `install.csx`, `save.csx`, `clean.csx` and `version.csx`. I guess for these cases we would have to insist on the extension being supplied. Also note that if we ever introduce new commands, we will have to make a *breaking change* to exclude a script with that command name from the extensionless behaviour.

An alternative approach is to move `install`, `save` and `clean` over to a new `spm.exe` and leave just `-help` and `-version` as commands disguised as options in `scriptcs.exe`. This would match the situation with node and npm.
