### ISSUE TITLE
ScriptCatalog

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#203]
This catalog will make it easy for users to extend ANY .NET app using scriptcs. Basically the catalog will search for scripts and automatically load them as MEF plugins.

**Comment by glennblock** [comment]
Hi all i've updated this to a "You Take it". I still think it is useful, and not hard to do, but its pretty low on my priority list.

**Comment by laedit** [comment]
Hi, I am interested in this for [Pretzel](https://github.com/Code52/pretzel), I [searched](https://github.com/Code52/pretzel/issues/217#issuecomment-78512918) a little bit but I don't think I'm doing the right thing.
Can you point me to a direction, to help me start?

Thanks :smiley:

**Comment by adamralph** [comment]
@laedit AFAIK nothing has ever happened in this space, so the concept of a 'script catalog' doesn't currently exist. For now, I'd probably press ahead over with your specific problems over at the Pretzel issue and feel free to ping @scriptcs/core if you need us to chime in. If your work over there ends up expediting the creation of the scripts catalog feature then all the better! :smile:

**Comment by laedit** [comment]
My message was badly written: the ScriptCatalog is the missing thing I need for Pretzel so I want to develop it.
My problem is that I execute scriptcs and after I check every assembly in the AppDomain and I consider that if the assembly name starts with ℛ* it's an assembly generated by scriptcs.
I don't think it is the right thing to do, so I was asking for a little help on how to use scriptcs properly in that case :smiley:

**Comment by glennblock** [comment]
Hi @laedit you convinced me to put some time into this. I'm going to take a stab at it. The use case i'd imagine is you have a folder with scripts and with an optional scriptcs_packages.config / scriptcs_packages folder. You point the catalog at the folder and it takes the scripts and compiles them up and then adds the resulting Assembly to an AssemblyCatalog which it delegates to. I could also expose a filter string if you want to load a specific file or match on a pattern.

Seem reasonable?

**Comment by glennblock** [comment]
I am taking a slight turn in direction here. As MEF on Nuget (Microsoft.Composition) has been designed to be much more lightweight and performant, I am going to use it instead. 

This means it will not be a catalog as in MEF 2 you create a `ContainerConfiguration` which you then configure / add assemblies to using `WithXXX` methods. Based on this, I am thinking I can have an extension method `WithScripts` that will have the same functionality.

**Comment by glennblock** [comment]
And now for something completely different. It's no longer extension methods. It is cleaner to just make it a derived ContainerConfiguration, so ScriptCsContainerConfiguration is born.

**Comment by glennblock** [comment]
OK @laedit after a few hours I have something now. You can clone the repo [here] (https://github.com/scriptcs-contrib/scriptcs-composition) to try it out.

The screenshot below shows how you use it and how it works! You create a script and the new `ScriptCsContainerConfiguration` and add the script. Packages should automatically work, but I haven't tested this yet!

![screen shot 2015-03-16 at 6 44 34 pm](https://cloud.githubusercontent.com/assets/141124/6679928/021b3174-cc0d-11e4-9a02-dd2ceb2a7bb2.png)

Give it a try and let me know if it is heading in a direction that is usable to you.

Thanks!

**Comment by glennblock** [comment]
@dsplaisted you may also be interested in this.

**Comment by dsplaisted** [comment]
Cool! :+1:

**Comment by laedit** [comment]
@glennblock thank you so much, I will test it ASAP! :smiley:

**Comment by glennblock** [comment]
Cool! One thing to note, we have a bug in our mono engine related to atttibutes on a class, so currently it is not working on Linux/Mac but does work on Windows

**Comment by laedit** [comment]
After a quick test I can say it is almost perfect!
Is it possible to add the following methods on ScriptCsContainerConfiguration in order to support the case of a "plugin" folder containing all scripts?
```cs
public ScriptCsContainerConfiguration WithScriptsFolder(string scriptsFolderPath)
{
        if (!_fs.DirectoryExists(scriptsFolderPath))
        {
            throw new DirectoryNotFoundException(string.Format("Scripts directory:{0} does not exist", scriptsFolderPath));
        }

        foreach (var scriptFile in _fs.EnumerateFiles(scriptsFolderPath, "*.csx"))
        {
            _scripts.Add(scriptFile);
        }

        return this;
}

public ScriptCsContainerConfiguration WithReferences(params Type[] references)
{
    _references = references;

    return this;
}
```

And in `Compile()`:
```cs
...
services.Executor.ImportNamespaces("System.Composition");

if (_references != null && _references.Length > 0)
{
     services.Executor.AddReferenceAndImportNamespaces(_references);
}

var result = services.Executor.ExecuteScript(loader);
...
```

Usage:
```cs
var container = new ScriptCsContainerConfiguration()
                .WithScriptsFolder("Scripts")
                .WithReferences(typeof(IGreeter))
                .Compile(AppDomain.CurrentDomain.BaseDirectory)
                .CreateContainer();
```
Test.csx content in "Scripts" folder:
```cs
[Export(typeof(IGreeter))]
public class Greeter : IGreeter {
  public void Greet(string message) {
    Console.WriteLine(message);
  }
}
```

Now I just need to adapt the use of MEF in Pretzel to MEF2 to test a real case, but I think that your solution is awesome.

**Comment by laedit** [comment]
@glennblock sadly I haven't been able to adapt Pretzel to MEF lightweight container.
So I made a [`ScriptCsCatalog`](https://github.com/laedit/ScriptCs.ComponentModel.Composition) for "normal" MEF (System.ComponentModel.Composition) from your code and `DirectoryCatalog`.

I you are ok it can be added to ScriptCs Contrib, I just need to do some cleanup/verification before.

**Comment by glennblock** [comment]
Awesome! Go for it!

**Comment by glennblock** [comment]
Btw, there are still some bugs. Script packs are not working right yet....

**Comment by laedit** [comment]
I have looked for the Script Packs but I have no clues, any ideas are welcome.

Beside of that I have done some cleanup and added several tests.
I think it is good for a first version (sadly without the support of Script Packs).
Since at first it was an issue for scriptcs, do you prefer that I made a Pull Request, or add to the scriptcs contrib, or I keep my repo and make a nuget package?

**Comment by glennblock** [comment]
We should add it as a new project to scriptcs-contrib. I will add a
"scriptcs-mef" repo and add you. As to getting script packs to load. Check
this gist / line and you'll see the missing code.
https://gist.github.com/bitbonk/aea4cb41a21b7d666e80#file-program-cs-L29

**Comment by glennblock** [comment]
@laedit I've created https://github.com/scriptcs-contrib/scriptcs-mef and
added you as an owner.

**Comment by laedit** [comment]
Thanks @glennblock, the project has been transfered and is ready to have his first version created! :smiley: 

About the Script Pack, I have the `Executor.Initialize` since the beginning but `ScriptPackResolver.GetPacks()` return an empty collection, even if a Script Pack (like ScriptCs.WebApi) is present in the scriptcs_packages in the current directory.
And the assemblies are presents in the return of the `AssemblyResolver.GetAssemblyPaths` method.

Do you have any idea of why? A problem with MEF which load files from another directory?

**Comment by glennblock** [comment]
Fabulous. I'll take a look and send you a PR once I figure it out. It is
probably something dumb.

**Comment by laedit** [comment]
The first version of the ScriptCsCatalog is available on [NuGet](https://www.nuget.org/packages/ScriptCs.ComponentModel.Composition/).
Thanks again @glennblock for all your help!

**Comment by adamralph** [comment]
@laedit congrats!

**Comment by glennblock** [comment]
Glad to help @laedit. Congrats!
