### ISSUE TITLE
Access currently running (or possibly main) script

### ISSUE THREAD

**Issue by rossipedia** [scriptcs/scriptcs#225]
It would be very useful to have access to the currently running file in an easy and intuitive way, preferrably as a `System.IO.FileInfo` instance.

Something like:

``` C#
FileInfo thisFile = ScriptCS.CurrentScriptFile;
```

or something similar.

**Comment by SuperJMN** [comment]
:+1: I think this is a very useful feature. I already needed it and I'm just starting to use ScriptCS

**Comment by adamralph** [comment]
@khellang are you working on this, or should we free it up for someone to grab?

**Comment by khellang** [comment]
Well, I had another go at this earlier today, but the amount of stuff I had to touch/break in order for this to work (pass `ScriptEnvironment` through layers and layers of abstractions) made me just give up. If anyone can come up with a better solution, they should just go ahead :+1:

**Comment by glennblock** [comment]
What about just reading Environment.Args? The script name / path should be
there no? At least an assumption that could be made outside the REPL.

**Comment by glennblock** [comment]
After a long hiatus, I am back to working on this and I "think" I have something working. This will let you access the main file that was executed in scriptcs via new `ScriptPath` variable hanging off of `Env`. Screen shot below.

@rossipedia You can easily instantiate a FileInfo from this path. Does this look it would work for you? I could also make it a FileInfo if you "really" want that.

![screen shot 2017-01-08 at 7 25 48 pm](https://cloud.githubusercontent.com/assets/141124/21756668/0a583864-d5d9-11e6-8e5c-90164c47fa51.png)

**Comment by glennblock** [comment]
I am thinking to also add a Files[] array that you can access as well which will show all files that scriptcs loaded

**Comment by glennblock** [comment]
File will always be the main one

**Comment by rossipedia** [comment]
@glennblock this is great! A full path is totally fine, really like the array idea as well.

**Comment by glennblock** [comment]
👍

**Comment by glennblock** [comment]
@rossipedia both will be there now. The main script as well as any child scripts that are loaded.
