### ISSUE TITLE
Introduce script packs as script.

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#238]
Yes we're going there. This will enable to you share scripts in nuget packages as script modules.

It will work very similar to node. Module scriptcs can depend on other modules. All modules will get installed in a modules folder.

Yes, we do love the node module system!

**Comment by glennblock** [comment]
This is still in progress. I have rethought this and am taking a different route now which will be more efficient, remove any extra load-time impact and be cleaner. I hope to make progress in the next month or so.

**Comment by adamralph** [comment]
Dropped in favour of https://github.com/scriptcs/scriptcs/issues/909
