### ISSUE TITLE
Expose a reference to the current script assembly

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#244]
I need this for the Nancy script pack.

Currently I'm doing `Assembly.GetCallingAssembly()`. Whilst this works, it feels fragile and it's not discoverable. I think scriptcs should abstract this away for me.

**Comment by glennblock** [comment]
Now that the ScriptInfo object is in place (#225), I think this is more feasible as it can be injected by whoever needs it including the engine. Let me see what I can do.

**Comment by glennblock** [comment]
Making progress. See below. A beautiful hack makes this work :-)

![screen shot 2017-01-11 at 9 32 45 pm](https://cloud.githubusercontent.com/assets/141124/21878201/8da6a46c-d845-11e6-9510-2b14810c43b2.png)

**Comment by glennblock** [comment]
@khellang @adamralph @filipw

**Comment by glennblock** [comment]
And in the REPL....

![screen shot 2017-01-11 at 9 54 02 pm](https://cloud.githubusercontent.com/assets/141124/21878655/8a13d272-d848-11e6-9a39-bcbabd74e2fb.png)

**Comment by glennblock** [comment]
Works on Mono as well both inside and outside the REPL

OK time for some unit tests....

![screen shot 2017-01-11 at 10 02 51 pm](https://cloud.githubusercontent.com/assets/141124/21878858/c7792c9c-d849-11e6-8c42-727e797d691f.png)
