### ISSUE TITLE
Add support for #show

### ISSUE THREAD

**Issue by filipw** [scriptcs/scriptcs#312]
According to *Interactive C# REPL and script, Code Semantics Spec" 11.5:

`#show` takes one of several arguments and displays information about the execution context. 
`#show` -- displays help text on #show 
`#show` [r|refs|references] -- displays the assemblies that have been #r'd 
`#show` [u|usings] -- displays the imported namespaces 
`#show` [names] -- displays all the named definitions (perhaps with one-liner value or signature information)

**Comment by filipw** [comment]
this is done

**Comment by adamralph** [comment]
We've implemented `#show`?

**Comment by filipw** [comment]
we've implemented the alternative approach - see #830

**Comment by adamralph** [comment]
OK, I'll mark this as a wontfix then.
