### ISSUE TITLE
Host ScriptCS in ASP.Net / Web Console

### ISSUE THREAD

**Issue by khalidabuhakmeh** [scriptcs/scriptcs#325]
I had this idea, but I need some guidance as to how to approach it. I would like to host the ScriptCS engine in an ASP.Net process / my web application and have it sitting on the backend waiting for commands from the client (me / admins). This is how I imagine it would work.

- Attach the Host in the Global.asax.

```csharp
ScriptCs.Web.Init("~/scriptcs/repl", adminRole: "Admins", adminsOnly: true);
```

- Include a reference to JavaScript in your layout

```csharp
@ScriptCs.Web.Scripts()
```

- When the app loads, the ScriptCS engine will load all the dlls in the bin folder and reference them in your ScriptCs context. You can also create small script packs inside your application to add functionality.

- Then on the client you will see a small tab in the bottom right. When you click on it a console appears.

- Now you have a console that is ready to execute any code you have on the server side at your command. Some commands you might want to run.

```csharp

HttpContext.Current.Session["data"]

Db.CreateUser("Khalid Abuhakmeh");

Db.Load<User>("khalid@aquabirdconsulting.com");

Scenarios.SetupFirstScenario();
Scenarios.SetupSecondScenario();

// probably part of an MVC script pack
Url.Action("index", "pages");

```

The nice thing about this approach is I can ask for information about my current application, rather than being presented all the information in my application (glimpse style). 

Just a thought, is this possible?

**Comment by filipw** [comment]
This is all doable but does not belong to the core. Here are some resources that could help:

 - sample scriptcs webhost https://github.com/filipw/sample-scriptcs-webhost
 - Glimpse plugin for scriptcs https://github.com/filipw/Glimpse.ScriptCs
 - Glimpse write up http://www.strathweb.com/2013/10/extend-glimpse-fly-scriptcs-code-execution-tab-glimpse/

**Comment by khalidabuhakmeh** [comment]
:(

**Comment by adamralph** [comment]
Noone is saying it shouldn't be done, it's just that it doesn't belong
here. This repo is for the core scriptcs libraries and executable.

It's an excellent idea, but it belongs in its own repo. If you want to
start the ball rolling, I'm sure we'd be happy to offer assistance. If it
comes to fruition then we'd probably want to bring into the
scriptcs-contrib organisation.
