### ISSUE TITLE
Distribute scriptcs through alternate means

### ISSUE THREAD

**Issue by jrusbatch** [scriptcs/scriptcs#359]
Some users are unable or unwilling to install chocolatey to use scriptcs. We should either provide an installer for those users.

**Comment by adamralph** [comment]
As per @khellang 's suggestion, we could look into using https://github.com/Squirrel

**Comment by jrusbatch** [comment]
Agreed. I was thinking the same thing while watching the presentation on it during dotnetConf.

**Comment by jrusbatch** [comment]
Closing this as its quite out of date. We have SVM now.

**Comment by adamralph** [comment]
And homebrew

**Comment by glennblock** [comment]
+1
