### ISSUE TITLE
Split IScriptEngine.Execute in two, Initialize and Execute

### ISSUE THREAD

**Issue by khellang** [scriptcs/scriptcs#400]
As @filipw mentioned in #391:

Today we pass script args, script pack session and namespaces every time script executes. This made sense when we only supported file scripts, but in the REPL, this gets passed way too many times.  
We should consider splitting the `IScriptEngine.Execute` in two, `Execute` and `Initialize`.

**Comment by filipw** [comment]
done https://github.com/scriptcs/scriptcs/blob/dev/src/ScriptCs.Core/ScriptExecutor.cs#L124
