### ISSUE TITLE
Is there a way to use ScriptCS like the immediate window in Visual Studio

### ISSUE THREAD

**Issue by khalidabuhakmeh** [scriptcs/scriptcs#447]
Here is what I was thinking, not sure if it is possible, but I'll try to explain.

Is there a way to have ScriptCs in the background of an executing application that is currently being debugged. If there was a way to know the current context of the application once you hit a breakpoint, you could run code similar to how the immediate window in Visual Studio functions.

**The advantage that ScriptCS has is you can run multiple line expressions, lambda, and linq queries. All of which the immediate window cannot currently do.**

**Comment by khalidabuhakmeh** [comment]
You can probably close this now, since VS has a REPL.

**Comment by glennblock** [comment]
I am working on an integration that will let you use scriptcs directly in
the interactive. You can of course use the interactive directly, but this
will allow reusing all your existing scriptcs scripts. I have an early
spike here: https://github.com/scriptcs-contrib/scriptcs-interactive. In
its current form it has a bunch of limitations / only allows you to pass
back things you cast to dynamic, but I am working on something better.
