### ISSUE TITLE
Exception thrown when script is empty

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#545]
![image](https://f.cloud.github.com/assets/677704/1886868/b58bffec-79f0-11e3-94a4-c7c2b3d494b4.png)

**Comment by adamralph** [comment]
May be fixed in #1064. We should add a test and then, hopefully, close it.

**Comment by adamralph** [comment]
#1064 does indeed fix it:

![image](https://cloud.githubusercontent.com/assets/677704/10208744/d2a3e426-67d5-11e5-9898-5fe1a77311e0.png)

For this one, I think I would like to add an acceptance test before closing. It's a boundary condition and I want to ensure we never regress and do something strange when presented with an empty script.

**Comment by filipw** [comment]
fixed
