### ISSUE TITLE
Run the script on a STA thread

### ISSUE THREAD

**Issue by lbargaoanu** [scriptcs/scriptcs#572]
UI work requires a STA thread. The main thread of ScriptCS is MTA. The easy way would be to make it STA using the STAThreadAttribute. Marshaling every call to a STA thread is painful :).

**Comment by hypersw** [comment]
Another case is using scriptcs as an entry point for starting some large app in this environment. Many multi-threading models these days actually suppose the main thread to be an STA (whether they assert it or not), as they're doing dispatching on the thread.
