### ISSUE TITLE
Update to latest Roslyn CTP

### ISSUE THREAD

**Issue by regisbsb** [scriptcs/scriptcs#614]
It has just been opensourced so it will be nice to have it updated to use it.

**Comment by laedit** [comment]
Sad news, all the  Roslyn.Compilers.* packages have been [unlisted](http://www.nuget.org/packages/Roslyn.Compilers.Common/) from nuget: they are impossible to find through the search on the website or in Visual Studio.

So it is now impossible to install the ScriptCs.Engine.Roslyn package on a new project.

And the scripting part is available only on [myget](https://www.myget.org/gallery/roslyn-nightly) as a nightly build. :sob:

**Comment by filipw** [comment]
they have been unlisted a long time ago already but it is still possible to install them. See the API call http://www.nuget.org/api/v2/Packages(Id='Roslyn.Compilers.CSharp',Version='1.2.20906.2')

**Comment by adamralph** [comment]
@filipw are we using this issue to track the work over at https://github.com/scriptcs/scriptcs-engines ?

**Comment by filipw** [comment]
I think this should be closed

**Comment by filipw** [comment]
For all questions regarding new Roslyn engine please use this repo - https://github.com/scriptcs/scriptcs-engines
