### ISSUE TITLE
Mono error reporting

### ISSUE THREAD

**Issue by filipw** [scriptcs/scriptcs#664]
Currently the Mono engine uses the built in Mono.CSharp console printer directly.

Should instead implement a custom printer that will capture errors & warnings and allow scriptcs infra to handle them

**Comment by ztone** [comment]
@adamralph Re-open this one as well as @filipw asked me to remove the reporting code from that PR.  I'll submit a new PR with this fix, probably soon.

**Comment by adamralph** [comment]
OK, thanks.

**Comment by filipw** [comment]
Fixed by #1216
