### ISSUE TITLE
Include binstub for *nix in build artifacts

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#675]
via @paulcbetts https://gist.github.com/paulcbetts/e8514a03c6c01d1677cb

```bash
#!/usr/bin/env mono
## Make sure to chmod +x this file!

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mono "$DIR/scriptcs.exe" $@
```

**Comment by mbaker-dev** [comment]
I have a binstub ready in my branch, along with a new line processor to effectively treat a shebang line as a NOOP, but am not sure where the best location in the source would be for the binstub.

Right now it's just sitting in the root of the project as a placeholder. What do you think of the following suggestion?

1. Place it in src/ScriptCs/Properties, alongside chocolateyInstall.ps1. 
2. Update the build scripts to include the binstub in the build output and NuGet package.
3. Update chocolateyInstall.ps1 to exclude the binstub from the Chocolatey install.

This way, the binstub will be included in the build output, but won't impact Windows users by having a potential naming conflict with 'scriptcs'.

Or maybe I'm overthinking it and there is a simpler solution? :)

The way I have it working in my branch is similar to most other scripting languages on *nix. 

For example, a script app.csx:
```C#
#!/usr/bin/env scriptcs

Console.WriteLine("Hello World!");
```

can be run like `./app.csx`.

**Comment by glennblock** [comment]
Cool. Can you send the link to your branch?

**Comment by mbaker-dev** [comment]
Link to branch: https://github.com/mbaker-dev/scriptcs/tree/675

I've verified that all of the standard usages work with the binstub as well, such as:

* Using `scriptcs` to invoke the REPL.
* ScriptCs arguments such as `scriptcs -help`
* Passing a file to ScriptCs like `scriptcs app.csx` and `scriptcs ./app.csx`
* And of course the big one `./app.csx`

The only gotcha would be that people would need to remove any alias they added as per the current *nix wiki documentation, as this would no longer be necessary.

**Comment by adamralph** [comment]
I've raised a PR from @mbaker-dev's branch  to make discussion/review easier - #970
