### ISSUE TITLE
Microsoft.Bcl requires newer NuGet version

### ISSUE THREAD

**Issue by paulbouwer** [scriptcs/scriptcs#688]
Using the current `v0.9.0` version of scriptcs, I get the following error when trying to install the Azure Management Libraries NuGet package:

```
> scriptcs -install Microsoft.WindowsAzure.Management.Libraries
INFO: Installing packages...
ERROR: Installation failed: Microsoft.WindowsAzure.Management.Libraries
ERROR: The 'Microsoft.Bcl 1.1.9' package requires NuGet client version '2.8.1' or above, but the current NuGet version is '2.7.40808.167'.
INFO: Installation completed successfully.
INFO: Saving packages in packages.config...
INFO: Packages directory does not exist!
```

I've had a few people ask me about this since my `ScriptCs.AzureManagement` Script Pack does the same. It seems as though the newer `Microsoft.Bcl` NuGet packages require `NuGet 2.8`.

The `dev` branch of scriptcs does not have this issue since it has upgraded NuGet.Core to `2.8.5`. This solves the problem but I'm not convinced that people should have to run a nightly build to be able to install NuGet packages without error. If it makes sense could we release a `v0.9.1` version of scriptcs with this update?

I have created a branch off `master` and upgraded `NuGet.Core` to `2.8`. I have brought across the minimum set of changes from `dev` to ensure that this still works. 

All the tests are green. I've also tested install, restore, restore on run, save and clean and all work as expected.

**Comment by adamralph** [comment]
@paulbouwer is this still an issue? scriptcs is now using NuGet.Core 2.8.2 (although we do now have the opportunity to move to 2.8.3).

**Comment by paulbouwer** [comment]
@adamralph All looks good now - the install succeeds. 

It may still be worth moving to the latest version of `NuGet.Core` if the opportunity is there and there are no issues with the move.
