### ISSUE TITLE
DependencyResolutionException when running script from VS

### ISSUE THREAD

**Issue by k0stya** [scriptcs/scriptcs#712]
I configured VS proj as described in the wiki however I am getting the following error:

`Autofac.Core.DependencyResolutionException was unhandled
Message: An unhandled exception of type 'Autofac.Core.DependencyResolutionException' occurred in Autofac.dll
Additional information: An exception was thrown while invoking the constructor 'Void .ctor(ScriptCs.Contracts.IScriptHostFactory, Common.Logging.ILog)' on type 'RoslynScriptInMemoryEngine'.`

However debugging works when I attach to the scriptcs process which I run from powershell.

**Comment by filipw** [comment]
not reproducible anymore - likely dll hell
