### ISSUE TITLE
Expressions capturing local vars do not compile in Mono

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#713]
```c#
var x = 123;
Action a = () => x++;
Console.WriteLine(x);
```

![image](https://cloud.githubusercontent.com/assets/677704/3085612/9f41b89a-e515-11e3-9425-a247a55432a5.png)

**Comment by adamralph** [comment]
@ztone you mentioned this over in https://github.com/scriptcs/scriptcs/issues/665#issuecomment-71342609. Do you know how are things looking with the mono compiler fix? Is it released/scheduled for release?

**Comment by ztone** [comment]
@adamralph Unfortunately it is not in the Mono 3.12 release that was released 13 Jan, but it should be in the next release.  There is no specific date set for the next release that I know of.

**Comment by adamralph** [comment]
OK, thanks for the info.
