### ISSUE TITLE
Homebrew Package

### ISSUE THREAD

**Issue by BrendanThompson** [scriptcs/scriptcs#716]
Hey guys,

Would be super swell if we could get a hombrew brew for scriptcs :)

**Comment by spboyer** [comment]
+1

**Comment by filipw** [comment]
https://gist.github.com/filipw/6cbc6394360142a1976e

**Comment by spboyer** [comment]
@filipw :+1:

**Comment by c0ntinuum** [comment]
Hey Guys,

Just as an FYI here's one I built (based on a Gist by [akunzai](https://github.com/akunzai)):

https://github.com/c0ntinuum/homebrew-scriptcs

I'm happy to maintain this for the scriptcs project or you could just take it and make it part of a scriptcs or an associated repo.

Thanks for scriptcs ;)

**Comment by filipw** [comment]
oh great, can we get it in here https://github.com/Homebrew/homebrew/tree/master/Library/Formula?

**Comment by c0ntinuum** [comment]
@filipw I'll contact the Homebrew guys and see if we can get it in there ;)

**Comment by adamralph** [comment]
Note that since the merge of #970 we have a binstub in the artifacts.

**Comment by c0ntinuum** [comment]
@filipw scriptcs easily passes all criteria for inclusion in the primary Homebrew Formulae repository except the last one:

> has a stable, tagged version (i.e. not just a GitHub repository with no versions). See Interesting-Taps-&-Branches for where pre-release and head-only versions belong.

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#basic-instructions

> Formulae in the core repository must have a stable version tagged by the upstream project. Tarballs are preferred to git checkouts, and tarballs should include the version in the filename whenever possible.

> Software that does not provide a stable, tagged version, or had guidance to always install the most recent version, should be put in Homebrew/homebrew-head-only or homebrew/devel-only.

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#stable-versions

Please let me know how you'd like me to proceed? I'm happy to raise an issue against Homebrew and see if they will take PR for the inclusion of the scriptcs.rb but it may well be a bit too early for that right now.

**Comment by adamralph** [comment]
@c0ntinuum we do tag all our releases in GitHub, e.g. https://github.com/scriptcs/scriptcs/tree/v0.13.3

**Comment by adamralph** [comment]
@c0ntinuum we also create a GitHub release for every version too, if that's what you mean. See https://github.com/scriptcs/scriptcs/releases

**Comment by c0ntinuum** [comment]
@adamralph my apologies for being unclear...

I am aware that scriptcs has tagged GitHub releases (I use them in my Formula) I was wondering whether scriptcs was stable enough (yet) to be considered by Homebrew for inclusion in their main Formulae Library as suggested by @filipw?

i.e. https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff

**Comment by filipw** [comment]
absolutely, like Justin mentioned - they have node formula - and it is also
pre 1.0.
So I don't think the version means much.

The only reason why we don't have zip/tar releases here is due to the
license on the old Roslyn packages - they cannot be bundled.
Plus - it is one of the 3 most popular non-MS .NET projects on Github since
2012. I think homebrew hosts a ton of formulae for projects which are
nowhere near scriptcs popualrity.

**Comment by c0ntinuum** [comment]
I'm not sure what pre-1.0 vs post-1.0 has to do with whether a project or codebase is considered stable and analogising the stability of Node.js to ScriptCs seems hard to justify...

In saying all that let me get a PR off over to Homebrew and see what they come back with.

**Comment by glennblock** [comment]
We're still going through changes, but the overall model, yes I'd say its
stable. We've added new things with each release, but fundamentally it has
not changed.

We have big changes coming under the hood in terms of the compiler we use,
but the overall experience will be the same and don't expect the code that
consumers of scriptcs use to change much if at all. We're pretty much the
same we've been for quite a while now.

**Comment by c0ntinuum** [comment]
> We're still going through changes, but the overall model, yes I'd say its
stable.

Off to raise a PR @ Homebrew now.

**Comment by glennblock** [comment]
Kudos!

**Comment by c0ntinuum** [comment]
https://github.com/Homebrew/homebrew/pull/37980

**Comment by adamralph** [comment]
@c0ntinuum does this mean we have to update the homebrew repo each time we release? https://github.com/Homebrew/homebrew/pull/37980/files#diff-4a911339b9531e302a5bc0d5c2e644b5R3

This is not a complaint, just a request for info. If so, we need to add homebrew to our release checklist.

**Comment by c0ntinuum** [comment]
@adamralph correct :) Just a one-liner that I (or anyone) can do.

**Comment by adamralph** [comment]
@c0ntinuum thanks, I'll add it to our standard release checklist so that we remember to maintain it.

**Comment by c0ntinuum** [comment]
Closing the loop... Here it is:

https://github.com/Homebrew/homebrew/blob/e627ecb1303b00a0f53068c3f828e974c2128798/Library/Formula/scriptcs.rb

Please feel free to test as follows:

If you were on my tap then:

`brew untap c0ntinuum/scriptcs && brew update && brew reinstall scriptcs`

Otherwise:

`brew update && brew install scriptcs`

**Comment by filipw** [comment]
awesome - thanks a lot!

**Comment by glennblock** [comment]
Beautiful! Just tested.

Thanks for doing this!

**Comment by c0ntinuum** [comment]
> Beautiful! Just tested.

Good to know it works (not just for me). ;)

> Thanks for doing this!

Easy one.
