### ISSUE TITLE
Error in Samples - nunit-runner

### ISSUE THREAD

**Issue by thardy** [scriptcs/scriptcs#754]
After cloning and running "scriptcs -install" in nunit-runners folder.  I then run "scriptcs start.csx" and receive the following error...

ERROR: Assembly not found. - nunit.core.dll

I see nunit.core.dll in the /packages/NUnit.Runners.2.6.2/tools/lib folder.  I just installed and started messing around with scriptcs, so I have no idea how it finds libraries.

**Comment by filipw** [comment]
moved to https://github.com/scriptcs/scriptcs-samples/issues/23
