### ISSUE TITLE
Automatically generate binding redirects for scriptcs.exe

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#789]
All assemblies that ship with scriptcs.exe should have all versions redirected to the version which ships with scriptcs.exe and this should happen automatically as we update packages.

E.g.

```xml
<dependentAssembly>
  <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-65536.65536.65536.65536" newVersion="3.0.0.0" />
</dependentAssembly>
```

**Comment by adamralph** [comment]
IIRC this was to deal with the problem of a newer version being present in `packages/`. AFAIK this has been fixed by #793 but I'll run some tests to confirm that. If the tests are successful then I'll close this issue.

**Comment by adamralph** [comment]
Superseded by #793

**Comment by adamralph** [comment]
FTR, I installed some later version of the packages used by scriptcs.exe into a script folder, referenced the libs from the script and then executed the script. The dynamic assembly resolver worked as designed and there were no conflicts. The script executed successfully.

**Comment by glennblock** [comment]
Awesome! Maybe we should have an acceptance test for redirects? Seems like
a good use case.

**Comment by adamralph** [comment]
:+1: for an acceptance test. I've raised a tech debt task - https://github.com/scriptcs/scriptcs/issues/943
