### ISSUE TITLE
Investigate mono support

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#80]
Figure out if we could get scriptcs working for mono. Roslyn allows you to pass host objects into the running script. Ideally this feature which script packs rely on will also work.

**Comment by mika76** [comment]
I see this was merged to core, but see no references to linux or OS X in docs. Did I miss it somewhere? How to install and run under different platforms?

**Comment by khellang** [comment]
@mika76 You didn't see this empty page? :stuck_out_tongue_closed_eyes:

**Comment by c0ntinuum** [comment]
@mika76 check out the following:

https://github.com/scriptcs/scriptcs#building-from-source

https://github.com/scriptcs/scriptcs/wiki/Building-on-Mac-and-Linux

**Comment by khellang** [comment]
@mika76 The easiest way to get it is probably by installing SVM and getting it from there: https://github.com/scriptcs-contrib/svm/wiki/Installing-svm. It has instructions on installing on OSX and Linux :smile:

**Comment by adamralph** [comment]
https://github.com/scriptcs/scriptcs/wiki/Installation

**Comment by mika76** [comment]
Cool, thanks guys. May I recommend you put a link or description of that wiki page on the main pages (github readme and the github site) since it's all very Windows based. (I'm talking about installing and running, not so much building)

**Comment by adamralph** [comment]
Agreed. I've already raised an issue to sort out the readme https://github.com/scriptcs/scriptcs/issues/1023

I've just raised an issue to update the website https://github.com/scriptcs/scriptcs/issues/1024

Thanks for prompting!
