### ISSUE TITLE
Add AsyncContext evaluation

### ISSUE THREAD

**Issue by georgiosd** [scriptcs/scriptcs#822]
With reference to previous discussion here: https://github.com/scriptcs/scriptcs/issues/570#issuecomment-53046265

It would be great to allow top-level `await`s in ScriptCS which would mean evaluating code within an async context.

**Comment by masaeedu** [comment]
Has this already been fixed? I just tried `await`ing a `FromResult` task at the top level in the REPL and it seems to work!

    PS C:\Users\Asad> scriptcs -modules mono
    scriptcs (ctrl-c to exit or :help for help)

    > var result = await Task.FromResult(1);
    {
      "Result": {},
      "Id": 1,
      "Exception": null,
      "Status": 5,
      "IsCanceled": false,
      "IsCompleted": true,
      "CreationOptions": 0,
      "AsyncState": null,
      "IsFaulted": false
    }
    > result
    1

**Comment by filipw** [comment]
only in Mono

**Comment by glennblock** [comment]
We should add this now for Roslyn. In our latest release you can use async/wait but you still have to access the result of the top-level task.

**Comment by filipw** [comment]
This is fixed by #1216. Top-level tasks will be allowed when that is merged.

**Comment by filipw** [comment]
Fixed by #1216
