### ISSUE TITLE
Namespace aliasing causes an exception to be thrown

### ISSUE THREAD

**Issue by bchavez** [scriptcs/scriptcs#826]
Hi there,

By default, System.IO namespace is added to every script.

Problem is I have an assembly that defines Fluent.IO.Path that conflicts with System.IO.Path.

So, I'd need to write something like this:

using Path=Fluent.IO.Path;

However, when I try to run my script, I get the following error:
"error CS0246: The type or namespace name 'Path' could not be found (are you missing a using directive or an assembly reference?)"

Any help would be great.

Running scriptcs in debug mode, I can confirm the assembly is being found and loaded.

Thank you,
Brian

https://groups.google.com/forum/m/?fromgroups#!topic/scriptcs/7YiOeeGgaZw

**Comment by bchavez** [comment]
Hi @glennblock , unfortunately, no, the fully qualified reference doesn't work either.

     var inline = PreMailer.Net.PreMailer.MoveCssInline(layout, true);
     File.WriteAllText("Layout.Inline.html", inline.Html);

Produces error:

`error CS0103: The name 'PreMailer' does not exist in the current context`

I'm using latest version on choco v0.12

**Comment by glennblock** [comment]
Brian I submitted a fix several weeks ago to not recursively walk dirs
which was merged into Dev.
