### ISSUE TITLE
Some way too suppress dumping objects that are returned from an async function

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#831]
If a method is async returns an object that is captured by a variable, we still dump the object. This can be annoying as can be seen in this screenshot after the ExportSearchResultsAsync method is called.

![splunkpack](https://cloud.githubusercontent.com/assets/141124/4281079/e504cdf0-3d39-11e4-8b29-99d937a4e35c.png)

It appears to only be happening when the "async" keyword is used.

**Comment by filipw** [comment]
fixed by https://github.com/scriptcs/scriptcs/pull/1216

**Comment by filipw** [comment]
Closing as resolved
