### ISSUE TITLE
Let's back chocolatey!

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#839]
Let's face it, without chocolatey we'd have a lousy install experience and probably far less people using us.

I just backed their kickstarter, and if you love scriptcs, I'd recommend you should too :-) No I don't get anything but satisfaction knowing we are supporting this project: https://www.kickstarter.com/projects/ferventcoder/chocolatey-the-alternative-windows-store-like-yum

**Comment by adamralph** [comment]
It got backed! Thanks to everyone who joined in :trophy:
