### ISSUE TITLE
Deprecate Common.Logging usage in favour of our own logging API

### ISSUE THREAD

**Issue by filipw** [scriptcs/scriptcs#847]
Let's drop Common.Logging which is an extra dependency that has already caused a number of issues in terms of assembly versioning, binding redirects and what not.

I propose we just use LibLog (https://github.com/damianh/LibLog) which is a single class file that you just copy paste.

**Comment by adamralph** [comment]
Bumping up to P1.

Common.Logging has long crossed the threshold into DLL-hell. E.g. I can't update ConfigR to the latest version because it clashes with the version in scriptcs. I think the sooner we get rid of Common.Logging, the better.

**Comment by adamralph** [comment]
Words cannot describe the mess I'm in trying to fix my Common.Logging dependencies in ConfigR :rage:

**Comment by jrusbatch** [comment]
:+1:

**Comment by filipw** [comment]
I wholeheartedly agree. I have been saying to avoid Common.Logging from the very beginning! :wink:

**Comment by damianh** [comment]
I hope LibLog is up to expectations! :s

**Comment by glennblock** [comment]
I am good with this.

**Comment by adamralph** [comment]
As mentioned in #996, we are breaking the API here anyway, so there is no point keeping the `ILog` parameters in our public API. Custom loggers should be set using `LogProvider.SetCurrentLogger()`.

This change can be made ahead of whether we choose to re-introduce Common.Logging for a transitionary release - see https://github.com/scriptcs/scriptcs/issues/996#issuecomment-87377620

**Comment by adamralph** [comment]
We should also keep an eye on https://github.com/damianh/LibLog/issues/48

If the decision is made to go ahead with LibLog 4, we should upgrade before releasing 0.15.

**Comment by adamralph** [comment]
After trying it on for size, I'm u-turning on the idea of switching to using static `ILogProvider` configuration `ILog` creation and and I think we should keep the current container based mechanism as it is.

However, I think we should switch from passing around an `ILog` to passing around an `ILogProvider` instead so that each consuming class can create it's own logger with an appropriate name. This way, when logging at debug or trace level, we can include the logger name in the console output so we can see which class is logging each message.

**Comment by adamralph** [comment]
The remaining change which is required to close this issue is to move the logging interfaces from ScriptCs.Core to ScriptCs.Contracts. This is addressed in https://github.com/scriptcs/scriptcs/pull/1009

**Comment by adamralph** [comment]
As detailed in https://github.com/scriptcs/scriptcs/issues/996#issuecomment-96946803 this is now a deprecation, rather than removal, of Common.Logging.

Removal of Common.Logging will be scheduled for a later release.

**Comment by adamralph** [comment]
Oops! I missed one member when restoring the `Common.Logging overloads`:

```C#
MonoScriptEngine.Logger
```

Kudos to the folks who built https://github.com/ParticularLabs/APIComparer - it worked like a charm. I ran the console app for each of our output assemblies, e.g.

```batch
APIComparer.exe --source C:\Users\Adam\.svm\versions\0.14.1\ScriptCs.Hosting.dll --target C:\code\scriptcs\scriptcs\src\ScriptCs\bin\Release\ScriptCs.Hosting.dll
