### ISSUE TITLE
Cannot install ScriptCS via Chocolatey for multiple user accounts.

### ISSUE THREAD

**Issue by aarondandy** [scriptcs/scriptcs#874]
After ScriptCS is downloaded to `C:\ProgramData\chocolatey\lib\ScriptCs...` I think `chocolateyInstall.ps1` is run which copies the files to the `LOCALAPPDATA\scriptcs` folder for the current user. This works for the first account but when I log into the system as another user and attempt to install for that user it fails because ScriptCS is already installed. Because of how our security here is set up I can't elevate my account but instead run programs as a different accounts with different privileges. I know this is an inconvenient setup but my employer has lots of computers so I don't think I am unique in this situation.

As a short term (or possibly "short term") work around would it be safe for me to add `C:\ProgramData\chocolatey\lib\ScriptCs.{version}\tools\scriptcs` to the system path?

**Comment by tillig** [comment]
Just ran into this myself. Dos there need to be any user-specific portion to the install? If scriptcs doesn't care where it's run from, could it use the built-in Chocolatey mechanism to add a batch redirect to the `chocolatey/lib/scriptcs.*/scriptcs.exe`?

I could be over-simplifying here, I just see stuff like the `putty.portable` package able to put in a near-zero install and magic happens.

**Comment by adamralph** [comment]
@scriptcs/core can anyone chime on this? The choco package was put together before my time.

I think the current behaviour may have been driven by the desire for the installer to not require admin rights.

**Comment by aarondandy** [comment]
With an MSI it can detect if you are elevated (or ask) and install to the appropriate location. Also, the "this user" or "all users" question can be asked. But that is going down the WiX road. On a related note @dealproc mentioned in JabbR that they have experience with WiX ;)

**Comment by tillig** [comment]
I found a solution to this (PR #903) by modifying the Chocolatey package contents so the new Chocolatey package should enable a single install on the machine to work for multiple users. No WiX required.

**Comment by aarondandy** [comment]
I think that PR closes this issue for sure and will satisfy the majority of people. I still think there will be a small group that for one reason or another will prefer an msi file but I wont push that as I don't think the complexity is worth it. Perhaps a zip distribution would satisfy them as an alternative, should that issue be raised in the future.

**Comment by khellang** [comment]
This should be resolved with #903 :smile:
