### ISSUE TITLE
scriptcs crashes when native DLL's are present

### ISSUE THREAD

**Issue by sbedford** [scriptcs/scriptcs#913]
I'm getting a BadImageFormatException when trying to load the LibGit2Sharp library in a csx file.

I'm running ScriptCS version 0.13 on Windows 8.1 x64 - see https://gist.github.com/sbedford/472d9fa63a8304ce0b2f for a reproduction.

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'git2-e0902fb.dll' or one of its dependencies. The module was expected to contain an assembly manifest. ---> System.BadImageFormatException: Could not load file or assembly 'git2-e0902fb.dll' or one of its dependencies. The module was
expected to contain an assembly manifest.
   --- End of inner exception stack trace ---
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at ScriptCs.AppDomainAssemblyResolver.AddAssemblyPaths(IEnumerable`1 assemblyPaths)
   at ScriptCs.ScriptServicesBuilderFactory.Create(ScriptCsArgs commandArgs, String[] scriptArgs)
   at ScriptCs.Command.CommandFactory.<>c__DisplayClass2.<CreateCommand>b__0()
   at ScriptCs.Command.DeferredCreationCommand`1.Execute()
   at ScriptCs.Command.CompositeCommand.Execute()
   at ScriptCs.Program.Main(String[] args)

**Comment by glennblock** [comment]
I got this....

**Comment by glennblock** [comment]
Good news @sbedford. I see exactly where this is happening and it should be an easy fix. Also I am happy that it is NOT a MEF issue :p

**Comment by glennblock** [comment]
The issue occurs as the assemblies which are added to the MEF catalog. I am adding a check now that will only load it IF it is a managed assembly.

**Comment by nulltoken** [comment]
Indeed, `git2-e0902fb.dll` is a native dll.

@glennblock Thanks a lot for taking care about this :heart_eyes:

**Comment by glennblock** [comment]
My fix works :-). I'm going to commit to my branch so you can try it out.

**Comment by glennblock** [comment]
@sbedford @nulltoken I have a fix here: https://github.com/glennblock/scriptcs/tree/913. I have not sent a PR yet as tests are breaking, but if you grab it and build you should be able to run your sample fine.

**Comment by sbedford** [comment]
Weird, I'm getting a different error this time? Possibly environmental?

WARN: Some assemblies failed to load. Launch with '-loglevel debug' to see the details
ERROR: error CS0009: Metadata file 'c:\bin\LibGit2Sharp\packages\LibGit2Sharp.0.21.0.176\lib\net40\NativeBinaries\x86\git2-e0902fb.dll' could not be opened -- 'MetadataReaderException: COR20HeaderTooSmall'

//DEBUG dump

ERROR: error CS0009: Metadata file 'c:\bin\LibGit2Sharp\packages\LibGit2Sharp.0.21.0.176\lib\net40\NativeBinaries\x86\git2-e0902fb.dll' could not be opened -- 'MetadataReaderException: COR20HeaderTooSmall'
DEBUG: Roslyn.Compilers.CompilationErrorException: error CS0009: Metadata file 'c:\bin\LibGit2Sharp\packages\LibGit2Sharp.0.21.0.176\lib\net40\NativeBinaries\x86\git2-e0902fb.dll' could not be opened -- 'MetadataReaderException: COR20HeaderTooSmall'
   at Roslyn.Scripting.CommonScriptEngine.CompilationError(DiagnosticBag localDiagnostics, DiagnosticBag diagnostics)
   at Roslyn.Scripting.CommonScriptEngine.Compile(String code, String path, DiagnosticBag diagnostics, Session session, Type delegateType, Type returnType, CancellationToken cancellationToken, Boolean isInteractive, Boolean isExecute, CommonCompilation& compilation, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.CompileSubmission[T](String code, Session session, String path, Boolean isInteractive)
   at ScriptCs.Engine.Roslyn.RoslynScriptEngine.Execute(String code, Session session) in c:\development\git\scriptcs\src\ScriptCs.Engine.Roslyn\RoslynScriptEngine.cs:line 119

**Comment by glennblock** [comment]
Are you on Linux or Windows? I am not seeing this on Widows. It looks like the error is as it inspects the metadata. I may be able to fix with a try/catch.

**Comment by sbedford** [comment]
Win 8.1 x64

**Comment by glennblock** [comment]
Weird. Is this using just the sample? How are you running it?

**Comment by sbedford** [comment]
I have the gist in a csx file (along with packages.config) which I've copied into the artefacts/Release/bin directory and running it like

scriptcs --install
scriptcs app.csx

**Comment by glennblock** [comment]
I wouldn't run that way.

**Comment by glennblock** [comment]
Have scriptcs in a separate folder from your scripts. It should migrate your packages.config to scriptcs_packages.config the first time you run. Then you'll need to run again.

**Comment by glennblock** [comment]
We don't test / having scriptcs in the same folder as your script.

**Comment by glennblock** [comment]
Can you try testing with separate folders?

**Comment by glennblock** [comment]
I think you may have found another area where we are not checking for non-native dlls. We automatically load all binaries in the scriptcs folder as we have modules that we include in the box. 

We don't really test / support this scenario, so it might be good for us to add validation that throws an exception if you try to run a script in that folder.

**Comment by glennblock** [comment]
@sbedford same error, or it went away?

**Comment by sbedford** [comment]
Ok, this is really dumb but im going to spell it out anyway..

I pulled your repo down (https://github.com/glennblock/scriptcs.git), then pulled down branch 913, ran build.cmd.

Change directory to where my test script is: c:\development\gists\libgittest

Then I ran:  C:\development\git\glennblock_scriptcs\artifacts\Release\bin\scriptcs.exe app.csx

But I'm back where we started and I'm thoroughly confused :)

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'git2-e0902fb.dll' or one of its dependencies. The module was expected to contain an assembly manifest. ---> System.BadImageFormatException: Could not load file or assembly 'git2-e0902fb.dll' or one of its dependencies. The module was
expected to contain an assembly manifest.
   --- End of inner exception stack trace ---
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at ScriptCs.AppDomainAssemblyResolver.AddAssemblyPaths(IEnumerable`1 assemblyPaths) in c:\development\git\glennblock_scriptcs\src\ScriptCs.Core\AppDomainAssemblyResolver.cs:line 79
   at ScriptCs.ScriptServicesBuilderFactory.Create(ScriptCsArgs commandArgs, String[] scriptArgs) in c:\development\git\glennblock_scriptcs\src\ScriptCs\ScriptServicesBuilderFactory.cs:line 27
   at ScriptCs.Program.Main(String[] args) in c:\development\git\glennblock_scriptcs\src\ScriptCs\Program.cs:line 17

**Comment by sbedford** [comment]
ERROR: error CS0009: Metadata file 'c:\development\gist\libgittest\packages\LibGit2Sharp.0.21.0.176\lib\net40\NativeBinaries\x86\git2-e0902fb.dll' could not be
opened -- 'MetadataReaderException: COR20HeaderTooSmall'
DEBUG: Roslyn.Compilers.CompilationErrorException: error CS0009: Metadata file 'c:\development\gist\libgittest\packages\LibGit2Sharp.0.21.0.176\lib\net40\NativeBinaries\x86\git2-e0902fb.dll' could not be opened -- 'MetadataReaderException:
COR20HeaderTooSmall'

**Comment by glennblock** [comment]
I am seeing this error now as well. It looks like it may be a Roslyn CTP issue from what I am seeing.

**Comment by glennblock** [comment]
@sbedford making progress on this. It doesn't appear to be a Roslyn issue, it appears that we've passed the assembly to Roslyn as a reference. Its metadata reader fails (the error) as it should. I am going to add further filtering logic to prevent that!

**Comment by glennblock** [comment]
I think I've nailed it.....

![libgit](https://cloud.githubusercontent.com/assets/141124/6057461/3d482daa-acd3-11e4-9dcb-a6d881c78609.PNG)

**Comment by glennblock** [comment]
w00t!
