### ISSUE TITLE
scriptcs 0.13.1 crashes when a package has a framework assembly reference

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#922]
If the packages folder contains a package which has a framework assembly reference, e.g. ScriptCs.Contracts, which references `System.ComponentModel.Composition`, then scriptcs.exe crashes and dies.

This is because, as part of the fix for #913, it's now passing all the assemblies through `AssemblyUtility.IsManagedAssembly()`, which in turn calls `AssemblyName.GetAssemblyName(path)`, but `"System.ComponentModel.Composition"` is not a path, so a `FileNotFoundException` is thrown, and unhandled.

`AssemblyUtility.IsManagedAssembly()` is already catching `BadImageException` and returning false in that case, so I guess it should also catch `FileNotFoundException` and also return false in that case.

Note, that the script pack acceptance test is passing, even with this bug present, because ScriptCs.Adder doesn't take a dependency on ScriptCs.Contracts but ships the DLL in the package instead.

I thought perhaps we'd like to try a 'patch master' approach for this (so dev is free to progress independently in the meantime):

- [x] draft GitHub release (@adamralph)
- [x] raise PR to master (including version bump) (@glennblock and @adamralph)
- [x] merge PR to master (@adamralph)
- [x] publish GitHub release (@adamralph)
- [x] announce (@adamralph)
- [x] merge master to dev (@adamralph)

**Comment by glennblock** [comment]
I will get this fixed before I go to bed! Scout's honor.

**Comment by glennblock** [comment]
So on patch master, you are suggesting I fix this in the master branch and push it both to master and dev right?

**Comment by adamralph** [comment]
Send a PR as usual, but branch from master instead of dev, and PR back to master.  We'll sort out dev after the release.

**Comment by glennblock** [comment]
Just sent it.
