### ISSUE TITLE
Unable to install Script CS v0.13.2 - Get-EnvironmentVariable not recognized

### ISSUE THREAD

**Issue by shanselman** [scriptcs/scriptcs#936]
I don't believe that there is a PowerShell cmdlet called "Get-EnvironmentVariable." They are usually gotten via things like "$Env:os"

This is on Choco (v0.9.8.23). Perhaps it adds that method in a later version? Perhaps the *.ps1 script should block.

[image](https://cloud.githubusercontent.com/assets/2892/6343682/e10671a4-bba1-11e4-9870-56ec65a1ef2f.png)

**Comment by shanselman** [comment]
Confirmed. ScriptCS needs at LEAST Choco v0.9.8.33 to work. You should either block, or don't use that Get-EnvironmentVariable helper.

**Comment by adamralph** [comment]
Yep, I saw this a couple of days ago. Agreed, we should take some action. Thanks for raising!

**Comment by glennblock** [comment]
Thanks for reporting @shanselman. Agreed we should look at making this backward compatible!

**Comment by glennblock** [comment]
It looks like this PR introduced this: https://github.com/scriptcs/scriptcs/commit/b3b7519fb97dd83f79eb92c0582db7e0cbbe5cbc

**Comment by glennblock** [comment]
@adamralph the PR I linked to adds usage of Get-EnvironmentVariable here: https://github.com/scriptcs/scriptcs/commit/b3b7519fb97dd83f79eb92c0582db7e0cbbe5cbc#diff-7674fdc3653e4152a7b1055ce488febfR38

**Comment by adamralph** [comment]
@glennblock what your thoughts?

We can patch to 0.13.3 by swapping out `Get-EnvironmentVariable` and `Set-EnvironmentVariable` with `[Environment]::GetEnvironmentVariable()` and `[Environment]::SetEnvironmentVariable()` as per https://technet.microsoft.com/en-us/library/ff730964.aspx

**Comment by paulbouwer** [comment]
I use `[Environment]::SetEnvironmentVariable` in the `svm` installers and haven't had any issues with that to date.

**Comment by adamralph** [comment]
Thanks @paulbouwer, I guess we'll go with that

**Comment by glennblock** [comment]
Thanks @paulbouwer 

@adamralph I don't care which mechanism we use as long as it works. Let's get a patch release out there as this is breaking everyone who upgrades via Chocolatey.

**Comment by paulbouwer** [comment]
@adamralph - Have a look at line 117 in `https://github.com/scriptcs-contrib/svm/blob/master/install/installer.ps1` if you want to see the command in action.

**Comment by glennblock** [comment]
@shanselman we just pushed out a patch. Thanks!

**Comment by adamralph** [comment]
https://twitter.com/scriptcsnet/status/570121778405740544

**Comment by adamralph** [comment]
Closed by #937

**Comment by shanselman** [comment]
Amazeballs.

On Mon, Feb 23, 2015 at 11:24 PM, Adam Ralph <notifications@github.com>
wrote:

> https://twitter.com/scriptcsnet/status/570121778405740544
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scriptcs/scriptcs/issues/936#issuecomment-75710711>.
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by tillig** [comment]
My bad on this one. I tested on two different machines (see testing notes from #903) but apparently I have a newer Chocolatey on both. However, given the date on the PR is January 19 and [Choco 0.9.8.32 was released on January 22](https://github.com/chocolatey/chocolatey/wiki/ReleaseNotes), I'm not really sure when that problem method was introduced.

From a going-forward perspective, how would one avoid this sort of thing? Especially with Chocolatey itself [heading into some potentially breaking territory with 0.99](https://github.com/chocolatey/choco/wiki/ReleaseNotes) I imagine potential issues. Do you have to start doing version sniffing? :(

**Comment by adamralph** [comment]
No worries @tillig! We're glad for your contribution, which certainly improved the package. Getting commits into `dev` is a shared responsibility and noone is blaming you :smile:

**Comment by adamralph** [comment]
Going forward, I guess the onus is both on Chocolatey to ensure that it's clear which parts of the API are available in which versions and for us to follow suit, with a minimum required choco version in mind.
