### ISSUE TITLE
Caching of DLL

### ISSUE THREAD

**Issue by ashutoshraina** [scriptcs/scriptcs#941]
DLL caching feature as described here [DLL Caching](https://github.com/scriptcs/scriptcs/wiki/Compiling-%28and-caching%29-to-a-.dll), has the limitation of manually deleting the cache if it is stale.
Since the page is a little old, I wonder if we now have the ability to purge the cache automatically or via args ?

**Comment by adamralph** [comment]
Hi @ashutoshraina 

At the moment no further enhancement has been made in this area. You still have to delete the .scriptcs_cache folder yourself in order to purge the cache.

**Comment by ashutoshraina** [comment]
Side Note : 

```
scriptcs "Main.csx" -cache //Works
scriptcs -cache "Main.csx" //Explodes

scriptcs -install Something //works
```

I think there should be a consistent way of passing arguments i.e. either pass the flags before the script or pass it after the script..What do you guys think ?

**Comment by adamralph** [comment]
@ashutoshraina it's true that this can be confusing. I've been caught out myself on occasion by incorrect ordering of arguments. I've raised https://github.com/scriptcs/scriptcs/issues/942 to at least document the current behaviour. I think once that is done we can think about how to make the behaviour simpler/more obvious.

**Comment by ashutoshraina** [comment]
Thanks :)

**Comment by adamralph** [comment]
@ashutoshraina I've been doing a lot of work with the CLI arguments today and it's struck me that there is probably no ambiguity here. If you run `scriptcs -help` you are told:

![image](https://cloud.githubusercontent.com/assets/677704/6454625/58dcb284-c14b-11e4-93c5-43938b8d4d24.png)

> Script file name, must be specified first

AFAIK there are no other peculiarities with regard to argument order. As long as the script name is first, things should just work.

**Comment by ashutoshraina** [comment]
@adamralph I agree with you. But, I am not talking about just scripts here. I am talking about scriptcs as a complete thing. I would expect either the flags (or commands) to be specified first or at the end. If we are going to make CLI utilities with scriptcs then I would guess we are going tun them something like this

```
scriptcs myfile.csx --bar --baz

```

If there is a uniform way of doing things then the utilities can be shared with greater consistency. 

I also recognise that this may be just my brain going a little crazy and the authors are free to disagree.

**Comment by adamralph** [comment]
It is uniform already. The command line is in the form

```bash
scriptcs.exe -option1 value1 -option2 value2 -option3 value3
```

The script name is passed using the `-script` option, but this is also positional, i.e. it must be first, and then for that reason, you can omit `-script` and just write the script name, followed by other options.

`-install`, on the other hand, is not optional, so it needs to be specified if you want to pass an argument to it, i.e. the name of a package.

**Comment by adamralph** [comment]
```bash
# running a script
scriptcs -script main.csx   # long form
scriptcs main.csx           # short form
````

```bash
# package installation
scriptcs -install           # installs all packages listed in scriptcs_packages.config
scriptcs -install Foo       # installs a package named Foo
````

```bash
# running a script and installing all packages listed in scriptcs_packages.config
scriptcs -script main.csx -install   # long form
scriptcs main.csx -install           # short form
````

If you were to swap the order of  `-install` and `Foo` in the last command then, from the above information, you can deduce the behaviour that will follow:
```bash
scriptcs Foo -install
```
This will runs a script named `Foo` and install all packages listed in `scriptcs_packages.config`.

Does that make sense?

**Comment by ashutoshraina** [comment]
Yes, that does make a lot of sense. Also, I think it would be really nice if we can move this comment to the wiki so that it helps the users going forward.

@adamralph thanks a ton for clearing this up.

**Comment by adamralph** [comment]
How this? https://github.com/scriptcs/scriptcs/wiki/The-command-line :smile:

**Comment by ashutoshraina** [comment]
:+1:
