### ISSUE TITLE
Document valid/invalid argument combinations and ordering

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#942]
Spun off from https://github.com/scriptcs/scriptcs/issues/941#issuecomment-76621372

This should be a new wiki page.

**Comment by srutis90** [comment]
Can I pick this?

**Comment by adamralph** [comment]
@srutis90 do you mean you would like to take on the task? If so, sure please go ahead.

Having thought abot it, I think for now, it's probably not worth trying to get this into `scriptcs -help` since a) PowerArgs doesn't support the kind of help layout required unless we switch to subcommands (https://github.com/scriptcs/scriptcs/issues/175) b) if we do switch to subcommands then the command line will change dramatically. However, the switch to subcommands is still under debate (see https://github.com/scriptcs/scriptcs/issues/175#issuecomment-68596753) since it has other consequences. Hence, I think for now, all we need is a wiki page.

**Comment by adamralph** [comment]
Done https://github.com/scriptcs/scriptcs/wiki/The-command-line
