### ISSUE TITLE
Duplicate references cause script execution to fail

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#953]
![image](https://cloud.githubusercontent.com/assets/677704/6501970/3493faba-c31f-11e4-9f2e-aa78a0662971.png)

This is in the *current release*, i.e. 0.13.3 on Choco.

IIRC, we had some kind of 'de-duplication' of references at one time but it seems to have disappeared. I think what we require is a more general version of the changes that went into the dev branch recently for the scriptcs assemblies (https://github.com/scriptcs/scriptcs/blob/af885ff75cc31736bc60b298ce26c960d70b79b4/src/ScriptCs.Core/ScriptExecutor.cs#L66-L67 and https://github.com/scriptcs/scriptcs/blob/af885ff75cc31736bc60b298ce26c960d70b79b4/src/ScriptCs.Core/ScriptExecutor.cs#L88-L96) which take into account *all* the assemblies currently referenced.

Unless we can push out 0.14 soon I think this should be a patch on master (0.13.4) but I'd prefer someone else to reproduce and confirm the issue first.

**Comment by adamralph** [comment]
The duplicate references are occurring because Microsoft.Net.Http.2.2.29 is specifying System.Net.Http.WebRequest as a framework (GAC) reference but also ships with that DLL in it's lib folder. Whether this is a stroke of genius or the work of a madman is debatable, but in any case, under classic .NET usage this doesn't cause any problems and we need to insulate scriptcs against it too.

**Comment by paulbouwer** [comment]
I saw this issue earlier today on google groups. Was able to reproduce but
haven't had the time to look at it any further.

**Comment by adamralph** [comment]
Given it's not something we've introduced, I'm inclined to say this doesn't have to be a patch, but can go out with 0.14.0.
