### ISSUE TITLE
Ignore shebang on *nix platforms

### ISSUE THREAD

**Issue by vtsingaras** [scriptcs/scriptcs#956]
Make scriptcs don't treat shebang line as preprocessor directive.

**Comment by mbaker-dev** [comment]
I'll take it!

Note: This is pretty similar to #675 (My work in progress on that issue already included this, so this may just be able to be closed as a duplicate?).

**Comment by adamralph** [comment]
Awesome @mbaker-dev!

I think they are two separate features. One is to supply a bin stub. The other is to allow scripts to contain a shebang?
