### ISSUE TITLE
-Output option does not write console output to a file

### ISSUE THREAD

**Issue by srutis90** [scriptcs/scriptcs#957]
I have a csx script that does some Console.WriteLine
When I run the script with -O or -Output option, it does not write to the file. This is what I did.

scriptcs myscript.csx -O dump.txt

The output is still written to the command line, so I know my script is fine.

I tried with both complete file path and just the filename (assuming it would be the current working directory) as values to the Output option.

**Comment by adamralph** [comment]
Hi @srutis90 

The `-output` option only writes messages *from scriptcs.exe itself* to the output file. It does not attempt to intercept `System.Console`, so any message you write using that will not be written to the file.

scriptcs.exe does have it's own `IConsole` abstraction so we could investigate making that available to scripts. Unfortunately there's not an easy way of getting a reference to it right now, but I've raised https://github.com/scriptcs/scriptcs/issues/958 for discussion.

As a workaround right now, you could use the file piping feature to write all console output to a file, e.g. on Windows, this would be:-

```batch
scriptcs myscript.csx > dump.txt
```

The downside of this is that it *redirects* the console output to the file, so you won't see anything in your console window.

**Comment by srutis90** [comment]
Ah thanks! 
I ended up doing the OS file pipe. I think I got a little misled by the `scriptcs -help`.

**Comment by adamralph** [comment]
Yes, that help message is a bit misleading. I've raised https://github.com/scriptcs/scriptcs/issues/961
