### ISSUE TITLE
Expose current IConsole to scripts

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#958]
Spun off from #957 

This would allow messages from scripts to be captured in the same way as messages from scriptcs.exe. This means they will be written to the output file when `-output` is specified and also, if a module introduces a custom console, scripts will/can also write to it.

The other option is to try and intercept stdout (and perhaps stderr) but this is a path fraught with danger.

Assuming this can work, the first choice is whether it is opt-in or opt-out.

If opt-out, we could introduce a `Console` property to `IScriptHost` so that, in a script, `Console.WriteLine("foo");` uses the property instead of `System.Console`. If we went down this route we'd probably need to precisely align the members of `IConsole` to `System.Console` for code portability. The script could still specify `System.Console` explicitly to opt-out.

If we prefer opt-in, we could call the `IScriptHost` property `ScriptConsole`, or we could add the `Console` property to `IScriptEnvironment` instead.

**Comment by adamralph** [comment]
Thoughts?

**Comment by filipw** [comment]
Today you can easily inject it into a script pack and expose from there

**Comment by adamralph** [comment]
True, but it would be nice if it were available in the general case.

**Comment by adamralph** [comment]
In fact, that would be another way of providing opt-in. We could publish a ScriptCs.Console script pack. That's a heavyweight solution though, it would be more natural to provide services from scriptcs.exe somewhere on the script host.

**Comment by glennblock** [comment]
It would be easy enough to expose ScriptServices on IScriptHost. I have
been thinking we need IScriptServices anyway.

**Comment by filipw** [comment]
in principle it's the same issue as #162. That one was for ILogger but
IConsole was discussed there too.

**Comment by adamralph** [comment]
@filipw ah yes, I thought there was one for the logger but I couldn't find it earlier.

@glennblock I think that's a great idea. That would solve opt-in, as well as exposing lots of other useful stuff.

Having thought about it, opt-out is probably overreach. Changing the meaning of `Console.WriteLine();` may end up with a slew of subtle side effects.

**Comment by adamralph** [comment]
Subset of #960
