### ISSUE TITLE
Only scan for modules when -m is specified

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#964]
Currently we scan even when -m is not specified, since our automatic engine selection (Roslyn/Mono) is performed by specifying the module name.

Module scanning takes up the [lions share](https://www.dropbox.com/s/3y85wtznzio5sox/Screenshot%202015-03-07%2010.58.01.png?dl=0) of start up time.

If we special case the Roslyn and Mono modules for the automatic engine selection, we only have to scan for modules when someone specifies -m. This should have a dramatic speed increase when running scripts with specifying modules.

**Comment by filipw** [comment]
I hacked it together quickly and the REPL startup time went from ~1.5 sec to 0.5 sec

![screenshot 2015-03-07 13 11 11](https://cloud.githubusercontent.com/assets/1710369/6541371/8ecc94d0-c4cb-11e4-925e-8109cebbff7a.png)

**Comment by adamralph** [comment]
Win!

**Comment by filipw** [comment]
the problem is how to deal with constructor injections into modules - right now they work since MEF takes care of that. [In here](https://github.com/filipw/scriptcs/blob/af0a00dd96cd09b92ea168c6282b7237d36e8d6c/src/ScriptCs.Hosting/ModuleLoader.cs#L84), I just used `Activator.CreateInstance`.

**Comment by filipw** [comment]
actually I take it back. We never supported constructor injection into modules (I even remember using `System.Console` in mono module since it was not possible to inject `IConsole`).

So `Activator.CreateInstance` is OK, and is a massive perf boost.

**Comment by glennblock** [comment]
Hmm, I don't that is correct that we never supported it. If one puts an
ImportingConstructor on a module, if should work.

That said for the perf gain I think it is acceptable.

**Comment by adamralph** [comment]
I tried the ImportingConstructor thing once (when I was fixing the Mono module logging) but I just couldn't get it to work. Not saying that it doesn't work, but I just couldn't figure out how to do it...

**Comment by glennblock** [comment]
Anyway perf is important so this makes sense regardless.

**Comment by adamralph** [comment]
From #968:


@filipw:
> Following the perf improvement last week we introduced a regression causing module loading based on file extension to no longer work (since you have to explicitly pass the module now).
> 
> This breaks i.e. F# and must be fixed before release.
> 
> The fix would be to explicitly check for CSX extension and only then opt into the "fast path" (no MEF).
