### ISSUE TITLE
Mono engine fails to parse class-level attributes

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#971]
Create a class in the script with an attribute on the class itself and the Mono engine will fail.

**Comment by filipw** [comment]
this is a bug in mono, not in our custom segmenter (where we break code into pieces to be evaluated). 
mono will throw if we pass something like this into the mono evaluator:

```
[Foo]
public class Bar {}
```

**Comment by glennblock** [comment]
Interesting. Is a Mono bug filed?

**Comment by filipw** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=28126

**Comment by glennblock** [comment]
Great, thanks! @migueldeicaza any chance we can get some love on this?

**Comment by ztone** [comment]
@glennblock @filipw @migueldeicaza ... I'm pretty sure I've found the mono bug for this  .. as the the old saying goes "it is working on my local" ... well!!! I got the mono csharp repl to accept class attributes, just want to know if my fix breaks sth else. But I'm having some issues running the mono make on my box (to verify the tests)!  I'll push a PR to mono when I've sorted this out.

**Comment by glennblock** [comment]
Awesome!

**Comment by filipw** [comment]
woohoo it's merged into mono, thanks @ztone

**Comment by glennblock** [comment]
Sweet!

**Comment by ztone** [comment]
:thumbsup:

**Comment by glennblock** [comment]
@ztone you seriously rock!

**Comment by ztone** [comment]
Thanks @glennblock  … FTW :heavy_check_mark:

**Comment by filipw** [comment]
Fixed a long time ago 😀
