### ISSUE TITLE
Should modules be installed globally? 

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#973]
Currently we install modules globally. For example, the F# module is installed globally to enable support for F# by doing `scriptcs -install ScriptCs.FSharp -g`

The downside of this is the package dependencies can create potential conflicts with the packages within the app. When this happens, scriptcs completely breaks.

In the node world, global modules only exist for one purpose, to support the node CLI experience. You do `npm install express-cli -g` for example and you and up with a node app that is a CLI and which is globally available. Those packages however are scoped to that CLI, they are not loaded automatically or scanned when just running a node app.

In scriptcs however, once those modules are installed they can and do in fact effect the app. That is partially by design as they extend scriptcs, but with the side effect that they might break due to dependency issues etc, it may not be worth it.

Inclusion of automatic redirects has helped to mitigate these breakages, but they are still there especially in cases where a dependency's API changed in a breaking fashion.

We could shift to a model that requires you to install the module for each app that uses it. Edge uses this model for node. If I want to use edge from my node app, I include it in my dependencies. In the same way, in this model, I'd include `scriptcs-fsharp` to run FSharp scripts or use it in the REPL. The biggest downside I'd see is for the REPL experience, as today once the FSharp module is installed globally, you can always use it in the REPL without having to install a package from the current folder, but with this model you'd have to install it into the folder where you'd run the REPL.

Thoughts?

**Comment by adamralph** [comment]
I'm all for it. The downside of having to install the module in each folder is outweighed by the upside of isolation and avoidance of conflicts.

**Comment by filipw** [comment]
the obvious upside would be that a broken module doesn't break scriptcs anymore. For example right now if you install scriptcs-fsharp you can't run scriptcs anymore at all since the module blows up.

btw I already suggested allowing a custom module path before - #625

**Comment by glennblock** [comment]
@filipw yes I remember. The proposal here would be to still have global packages for custom CLI use, but they would never be loaded unless in a CLI context. 

Modules would always be local to the app and not "shared" system wide as they are today. Of course they would still be able to be shared across a bunch of scripts in a common folder.

**Comment by glennblock** [comment]
@adamralph @filipw sounds like we're all in agreement. Let's see what others think!
