### ISSUE TITLE
Refactor hosting to make it IoC agnostic

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#977]
@bitbonk pointed out that Hosting takes a hard dependency on Autofac and should support other IoCs. Without this one can have conflicts if they host scriptcs and rely on a diff version of Autofac. 

One concern here is breaking existing hosters when this is addressed

The fundmental issue here is that then InitializationServices and RuntimeServices classes depend on a specific container while the rest of the hosting infra does not.

This can be addressed by doing some
refactoring. 

The container specific pieces are moved / extracted to a new ScriptCs.Hosting.Autofac package.

Then the question is whether to break the current hosting API or extract under it a Hosting.Core and make the current Hosting a facade of sorts over it and the new Autofac package.

Another option is to not have Hosting.Core and instead push some things into ScriptCs.Core. The main benefit here is not needing to create another package however to date we've mostly kept hosting out of core.

Anyyway, we could really use feedback from those hosting scriptcs today like @madstt @adamralph @stirno etc on this.

**Comment by bitbonk** [comment]
I did not check what features of autofac ScriptCs.Hosting actually uses but TinyIoC as a replacement might be an option if all needed features are in TinyIoC. It then might be a solution to quickly get rid of external IoC container dependencies without a big refactoring.

**Comment by glennblock** [comment]
We rely on MEF integration. So that's a big consideration.

**Comment by glennblock** [comment]
We use MEF for discoverability of all 3rd party extensions, modules, script packs, etc.

**Comment by glennblock** [comment]
Autofac integrates with MEF so that MEF services can be injected into Autofac components. I have been considering pulling out MEF altogether, though that is a significant amount of work at the hosting layer.

**Comment by adamralph** [comment]
If we do end up pulling out MEF then the Nancy model of TinyIoC built-in, third party container pluggable, could be a nice solution.

**Comment by glennblock** [comment]
This is a non-trivial piece of work and not really high priority as we have
a lot of other more important fish to fry. I do think it is worth
considering. It can be approached in an incremental fashion, first by
refactoring hosting so that it is IOC agnostic. All the MEF stuff is really
contained right now within the services classes, so nothing in scriptcs
outside of hosting really depends on it either.
