### ISSUE TITLE
scriptcs -debug without -repl does not configure REPL correctly.

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#990]
This is not new in 0.14. It is pre-existing in 0.13.3.

Leads to all kinds of problems, e.g.

```batch
mkdir bug-repro
cd bug-repro
scriptcs -install Nancy
scriptcs -debug
using Nancy;
```

> Index was outside the bounds of the array.

Without `-debug`, there is no error.

**Comment by filipw** [comment]
The `scriptcs -debug` was intended to be used for PDB debugging not for log messages.
If you want debugging log in REPL you should:

 - `scriptcs -log debug`
 - `scriptcs -debug -repl`

Right now the `ArgumentParser` will not set the REPL flag if the only argument is debug.

**Comment by adamralph** [comment]
OK, well, we need to do something about the UX here then. To any user this will just appear as the bug I have described.

Shall we just prevent REPL when `-debug` is passed?

**Comment by filipw** [comment]
the easiest would be just treat single debug argument same way as single log argument - and force repl https://github.com/scriptcs/scriptcs/blob/dev/src/ScriptCs/Argument/ArgumentParser.cs#L30

**Comment by adamralph** [comment]
That line of code redundant, since the command factory now falls back to REPL when no script name is passed. This PR gets rid of it - https://github.com/scriptcs/scriptcs/pull/944

**Comment by adamralph** [comment]
...that is why `scriptcs -debug` works today and goes into REPL.

**Comment by adamralph** [comment]
In which case, I think the bug stands. Either we disable REPL when in debug mode, or we have to fix it.

**Comment by filipw** [comment]
but does it set the REPL flag? the flag is important since that's how the module chooses the appropriate engine.
In this case it doesnt set the engine properly - notice not only using doesn't work, but nothing works in that REPL since the debugger engine can't handle REPL at all.

**Comment by filipw** [comment]
here https://github.com/scriptcs/scriptcs/blob/09bb9afaf113e3b7c3991283c2f1605ce5a504f2/src/ScriptCs.Engine.Roslyn/RoslynModule.cs#L16

Right now this flag is missing, and everything fails. ArgumentParser sets it if the only argument is `log` for example

**Comment by adamralph** [comment]
Ah I see. Yes, that's the problem then.

**Comment by filipw** [comment]
can you make sure the PR in #944 handles this scenario?

**Comment by adamralph** [comment]
Yes, will do.

**Comment by adamralph** [comment]
@filipw PR https://github.com/scriptcs/scriptcs/pull/944 now addresses this
