### ISSUE TITLE
Update homebrew package to 0.14

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#995]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/scriptcs.rb

**Comment by adamralph** [comment]
I can't do it, I don't have a Mac :smile:

**Comment by c0ntinuum** [comment]
I'm really new to Homebrew but I don't think we need a Mac as we just need to update lines 3 and 4 of the script and Travis will take care of the "bottles".

Let me handle this one and we'll see how the process goes - be back soon.

**Comment by adamralph** [comment]
OK, well, I read the docs for homebrew and the first thing it talks about is using the command line tool so I stopped there :smile: 

I guess it is just an edit to the file, but the sha256 entries scared me off. I don't know what they are or what they mean.

**Comment by BrendanThompson** [comment]
Ahh these silly windows users hehe

**Comment by c0ntinuum** [comment]
@adamralph :laughing: the sha256 is just like a sha1 (but better) for the .tar.gz in the releases section and the other three are auto-generated from pre-built binaries and auto-committed by Travis (CI) I suspect...

**Comment by adamralph** [comment]
so that means the sha256 need to change for each release? according to the tar.gz? How would I do that without the command line tool? Or *some* tool to generate it?

**Comment by c0ntinuum** [comment]
simplest way? just let me take care of maintaining the Homebrew package after each new release :+1:

**Comment by c0ntinuum** [comment]
https://github.com/Homebrew/homebrew/pull/38056

**Comment by adamralph** [comment]
OK, thanks very much! :smile: 

But in the case you're not around, it would be good to know the procedure. If it turns out to be simple and is easily do-able without a Mac, that would be good to know.

**Comment by adamralph** [comment]
Thanks for the PR! How did you get the sha256?

**Comment by adamralph** [comment]
I just ran the tar.gz through http://hash.online-convert.com/sha256-generator and got the same hash: 44060C7AE6EB156A0088E0F8C1A3E6523B5CD7D8C6961E628BA8D5A9DF3998EB

It's very easy then.

**Comment by c0ntinuum** [comment]
You need to give people a chance to reply LOL :laughing: 

1. Download the new release package e.g. `scriptcs-0.14.0.tar.gz`.
2. Run `shasum -a 256 scriptcs-0.14.0.tar.gz` which will produce the sha256 e.g. `44060c7ae6eb156a0088e0f8c1a3e6523b5cd7d8c6961e628ba8d5a9df3998eb`.
3. Fork Homebrew/homebrew, update lines 3 and 4 of `Library/Formula/scriptcs.rb` with the URL to the new release and the new sha256, commit, send PR etc.

**Comment by c0ntinuum** [comment]
Online sha256 generator (or another Windows tool) would do just fine ;)

**Comment by adamralph** [comment]
@c0ntinuum awesome, thanks very much!

**Comment by BlackFrog1** [comment]
The index on Brew was updated back in Apr.  Is there anything else to be done?
![brew](https://cloud.githubusercontent.com/assets/550820/7657813/0f068044-fb03-11e4-8b98-d1a6dbd21ec6.png)

**Comment by adamralph** [comment]
Nope, all done :smile:
