### ISSUE TITLE
Add LoadScriptPacks method to ScriptServicesBuilder

### ISSUE THREAD

**Issue by glennblock** [scriptcs/scriptcs#998]
When hosting you have to currently set ScriptName to empty string or set Repl to true in order to get script packs to load.

This is non-intuitive and has thrown off hosters like @laedit.

**Comment by filipw** [comment]
tbh, it has thrown off hosters like @filipw too

**Comment by glennblock** [comment]
Uh yeah and it threw me off a few times and I wrote the builder #facepalm

**Comment by glennblock** [comment]
Fortunately this is a REALLY simple fix

**Comment by glennblock** [comment]
Working on this now. @laedit stay tuned.

**Comment by laedit** [comment]
Excellent, thanks! :)

**Comment by glennblock** [comment]
ping @laedit

**Comment by filipw** [comment]
this is not breaking api though

**Comment by adamralph** [comment]
`IScriptServicesBuilder` has had a member added to it, so anyone deriving from it will break.

**Comment by filipw** [comment]
my point was this is really private scriptcs API since there is no way to plug it yourself or really do anything with it. in fact the interface is probably not needed at all

**Comment by adamralph** [comment]
Fair enough - we should remove it then. But that is also, strictly speaking, a breaking change :wink:

**Comment by filipw** [comment]
yes you are right

**Comment by glennblock** [comment]
The interface is for unit testing.

**Comment by glennblock** [comment]
I think the impact here is low. I could use an extension method and have it
do some casting magic under the hood, bur I don't think that is necessary.

This should not break hosters implementations. What could break is their
unit tests if they have handrolled mocks.

So technically a breaking change but practically not.

**Comment by adamralph** [comment]
Agreed. Extremely low impact. We can just :shipit:

**Comment by filipw** [comment]
imho we should change interface it to just the builder class with virtuals (as it's just for testing) - one less code file to maintain

**Comment by glennblock** [comment]
That is true. This rarely changes, but yes a consideration. Is
